'use strict';
const {test,before,after}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.resolve(__dirname,'..');const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222';
function memory(){const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)};}
function load(files,extras={}){const s={console,structuredClone,crypto:globalThis.crypto,URLSearchParams,AbortController,setTimeout,clearTimeout,location:{search:''},navigator:{onLine:true},...extras};s.window=s;vm.createContext(s);for(const f of files)vm.runInContext(fs.readFileSync(path.join(root,'public',f),'utf8'),s);return s;}
const json=x=>JSON.parse(JSON.stringify(x));
test('cross-tab notification invalidates only and never selects an account from storage',async()=>{const events={},storage=memory();const s=load(['account-core.js'],{localStorage:storage,addEventListener:(name,fn)=>events[name]=fn,fetch:async path=>Response.json(path.endsWith('runtime')?{accountsEnabled:true}:{user:{id:A,username:'owner-a'}})});await s.EvieAccounts.restore();events.storage({key:'unrelated',newValue:B});assert.equal(s.EvieAccounts.current().id,A);events.storage({key:'evie-session-change',newValue:B});assert.equal(s.EvieAccounts.current(),null);assert.throws(()=>s.EvieAccounts.storageKey(),/bloqueada/);});
test('401 locks account but a revision conflict does not log the user out',async()=>{let code=409;const s=load(['account-core.js'],{fetch:async path=>path.endsWith('runtime')?Response.json({accountsEnabled:true}):path.endsWith('session')?Response.json({user:{id:A,username:'owner-a'}}):Response.json({error:'test'},{status:code})});await s.EvieAccounts.restore();await assert.rejects(s.EvieAccounts.request('data/push'),e=>e.status===409);assert.equal(s.EvieAccounts.current().id,A);code=401;await assert.rejects(s.EvieAccounts.request('data/pull'),e=>e.status===401);assert.equal(s.EvieAccounts.current(),null);});
test('session verification never silently switches to another account',async()=>{let id=A;const s=load(['account-core.js'],{fetch:async path=>Response.json(path.endsWith('runtime')?{accountsEnabled:true}:{user:{id,username:'test'}})});await s.EvieAccounts.restore();assert.equal(await s.EvieAccounts.verify(),true);id=B;assert.equal(await s.EvieAccounts.verify(),false);assert.equal(s.EvieAccounts.current(),null);});
test('Electron adapter preserves HTTP status and respects pre-aborted requests',async()=>{let calls=0;const s=load(['account-core.js'],{DOMException,evieDesktop:{account:async()=>{calls++;return {ok:false,error:'conflict',status:409};}}});await assert.rejects(s.EvieAccounts.request('data/push'),e=>e.status===409);const c=new AbortController();c.abort();await assert.rejects(s.EvieAccounts.request('data/pull',{signal:c.signal}),e=>e.name==='AbortError');assert.equal(calls,1);});
test('restoring an expired session clears the former account identity',async()=>{let valid=true;const s=load(['account-core.js'],{fetch:async path=>Response.json(path.endsWith('runtime')?{accountsEnabled:true}:{user:valid?{id:A,username:'test'}:null})});await s.EvieAccounts.restore();assert.equal(s.EvieAccounts.current().id,A);valid=false;await s.EvieAccounts.restore();assert.equal(s.EvieAccounts.current(),null);});
test('username canonicalization and strict account namespaces',async()=>{const {normalizeUsername}=await import('../src/accounts.js');const s=load(['account-core.js']);for(const name of [' DÁLÍ ','Valeria.02','Alex-2'])assert.equal(s.EvieAccounts.username(name),normalizeUsername(name));for(const n of ['x','john@example.com','a/b','a'.repeat(25),'用户'])assert.throws(()=>normalizeUsername(n));assert.notEqual(s.EvieAccounts.scope(A),s.EvieAccounts.scope(B));assert.throws(()=>s.EvieAccounts.scope('../../legacy'));});
test('disabled adapter makes no authentication call and does not manufacture a session',async()=>{const calls=[];const s=load(['account-core.js'],{fetch:async(url)=>{calls.push(url);return Response.json({accountsEnabled:false});}});assert.equal(await s.EvieAccounts.restore(),null);await assert.rejects(s.EvieAccounts.authenticate('signin','user','not-a-real-password'),/desactivadas|habilitadas/);assert.deepEqual(calls,['/api/runtime']);assert.equal(s.EvieAccounts.storageKey(),'dali-os-local-v1');});
test('session restore scopes cached data; clear cancels late responses',async()=>{let resolve;const s=load(['account-core.js'],{fetch:async url=>{if(url.endsWith('runtime'))return Response.json({accountsEnabled:true});if(url.endsWith('session'))return Response.json({user:{id:A,username:'user-a'}});return new Promise(r=>resolve=r);}});await s.EvieAccounts.restore();assert.equal(s.EvieAccounts.storageKey(),'evie-account-'+A);const p=s.EvieAccounts.request('data/pull');s.EvieAccounts.clear();resolve(Response.json({owner:A,rows:[]}));await assert.rejects(p,/cuenta cambió/);assert.equal(s.EvieAccounts.current(),null);});
test('auth API remains closed without configuration, makes no provider request',async()=>{const {createAccounts}=await import('../src/accounts.js');let calls=0;const api=createAccounts({fetcher:async()=>{calls++;throw Error();}});const r=await api.request('http://localhost/auth/signup',{method:'POST',body:'{}'},{});assert.equal(r.status,503);assert.equal(calls,0);const runtime=await (await api.request('http://localhost/runtime',{},{})).json();assert.equal(runtime.accountsEnabled,false);});
test('AES-GCM session storage is authenticated and not plaintext',async()=>{const {seal,unseal}=await import('../src/accounts.js');const secret=crypto.getRandomValues(new Uint8Array(32)),key=Buffer.from(secret).toString('base64');const payload={access_token:'test-only-token',refresh_token:'test-only-refresh'};const value=await seal(payload,key);assert.ok(!value.includes('test-only'));assert.deepEqual(await unseal(value,key),payload);await assert.rejects(unseal(value.slice(0,-4)+'AAAA',key));});
test('module preferences retain hidden data and fixed entry routes',()=>{const s=load(['config.js','personalization.js']);const p=s.Personalization.change({},'hide','libros');assert.ok(!s.Personalization.sections(p).some(x=>x.route==='libros'));assert.throws(()=>s.Personalization.change(p,'hide','perfil'));const next=s.Personalization.change(p,'before','finanzas','agenda');assert.ok(next.sectionOrder.indexOf('finanzas')<next.sectionOrder.indexOf('agenda'));assert.equal(s.Personalization.greeting({preferred:'Alex',greeting_form:'Hola'}),'Hola, Alex.');assert.equal(s.Personalization.greeting({preferred:'Valeria',greeting_form:'Bienvenida'}),'Bienvenida, Valeria.');});
test('favorites lead navigation in module order without duplicate or mutated catalog entries',()=>{const s=load(['config.js','personalization.js']),P=s.Personalization,catalog=json(s.DALI_CONFIG.sections);const p={sectionOrder:['libros','finanzas'],favoriteSections:['finanzas','libros','libros','invalid']};const nav=P.navigation(p);assert.deepEqual(Array.from(nav.slice(0,2),x=>x.route),['libros','finanzas']);assert.ok(nav.slice(0,2).every(x=>x.group==='favoritos'));assert.equal(new Set(nav.map(x=>x.route)).size,16);assert.equal(nav.length,16);assert.deepEqual(json(s.DALI_CONFIG.sections),catalog);assert.deepEqual(p.favoriteSections,['finanzas','libros','libros','invalid']);});
test('manual module reordering changes favorite order without changing the pinned set',()=>{const s=load(['config.js','personalization.js']),P=s.Personalization;let p={favoriteSections:['finanzas','libros']};p=P.change(p,'before','libros','finanzas');assert.deepEqual(Array.from(P.navigation(p).slice(0,2),x=>x.route),['libros','finanzas']);p=P.change(p,'down','libros');assert.deepEqual(Array.from(P.navigation(p).slice(0,2),x=>x.route),['finanzas','libros']);assert.deepEqual(json(p.favoriteSections),['finanzas','libros']);});
test('hidden favorite remains pinned and returns on show without touching other preferences',()=>{const s=load(['config.js','personalization.js']),P=s.Personalization;const p={favoriteSections:['libros'],theme:'dark',mobileShortcuts:['inicio','libros','finanzas','perfil','configuracion']},original=json(p);const hidden=P.change(p,'hide','libros');assert.ok(!P.navigation(hidden).some(x=>x.route==='libros'));assert.deepEqual(json(hidden.favoriteSections),['libros']);assert.deepEqual(json(hidden.mobileShortcuts),p.mobileShortcuts);assert.equal(P.navigation(P.change(hidden,'show','libros'))[0].route,'libros');assert.deepEqual(p,original);assert.equal(hidden.theme,'dark');});
test('favorite maximum is five and removing one releases a slot',()=>{const s=load(['config.js','personalization.js']),P=s.Personalization;let p={};for(const r of ['agenda','finanzas','libros','granja','soma'])p=P.change(p,'favorite',r);assert.throws(()=>P.change(p,'favorite','vision'),/cinco/);p=P.change(p,'favorite','libros');p=P.change(p,'favorite','vision');assert.equal(p.favoriteSections.length,5);assert.ok(p.favoriteSections.includes('vision'));assert.equal(P.normalize({favoriteSections:s.DALI_CONFIG.sections.map(x=>x.route)}).favorites.length,5);});
test('mandatory routes survive malformed hidden/order settings and another account has no inherited pins',()=>{const s=load(['config.js','personalization.js']),P=s.Personalization;const a={hiddenSections:s.DALI_CONFIG.sections.map(x=>x.route),sectionOrder:['libros','libros','invalid'],favoriteSections:['perfil','libros']};assert.deepEqual(new Set(P.navigation(a).map(x=>x.route)),new Set(['inicio','perfil','configuracion']));for(const r of P.mandatory)assert.throws(()=>P.change(a,'hide',r),/accesibles/);const b=P.navigation({});assert.equal(b.length,16);assert.ok(b.every(x=>x.group!=='favoritos'));});
test('navigation markup exposes exactly one current page and safely labels favorites',()=>{const escape=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const s=load(['config.js','personalization.js'],{Domain:{escape},Views:{icon:()=>'<svg aria-hidden="true"></svg>'}});s.DALI_CONFIG.sections.find(x=>x.route==='libros').label='Libros " <script>';const html=s.Personalization.renderNavigation({favoriteSections:['libros']},'libros');assert.equal((html.match(/aria-current="page"/g)||[]).length,1);assert.equal((html.match(/href="#libros"/g)||[]).length,1);assert.match(html,/data-favorite="true"/);assert.match(html,/aria-label="Libros &quot; &lt;script&gt;, favorito"/);assert.ok(!html.includes('<script>'));assert.equal((s.Personalization.renderNavigation({hiddenSections:['libros']},'libros').match(/aria-current/g)||[]).length,0);});
function syncFixture(){const s=load(['sync-engine.js']);const storage=memory();let state={version:4,profile:{name:''},preferences:{},transactions:[]};let listener=()=>{};const store={collections:['transactions'],get:()=>state,validate:()=>true,subscribe:fn=>(listener=fn,()=>listener=()=>{}),save:fn=>{const old=structuredClone(state);fn(state);listener(old,state);}};return {s,storage,store,get:()=>state,set:fn=>store.save(fn)};}
test('offline diff preserves non-UUID IDs and tombstones',()=>{const {s}=syncFixture();const state={version:4,transactions:[{id:'Legacy-ABC-0001',amount:100000,deleted_at:'2026-01-01'}]};const rows=s.EvieSync.rows(state,['transactions']);const changes=s.EvieSync.diff(rows,{});assert.equal(changes[0].record_id,'Legacy-ABC-0001');assert.equal(changes[0].payload.amount,100000);assert.equal(changes[0].payload.deleted_at,'2026-01-01');});
test('same-record conflicts never silently discard unsynced local edits',()=>{const {s}=syncFixture();assert.equal(s.EvieSync.classify({n:2},{n:1},{n:3}),'conflict');assert.equal(s.EvieSync.classify({n:1},{n:1},{n:3}),'remote');assert.equal(s.EvieSync.classify({n:2},{n:1},{n:1}),'local');});
test('sync rejects another owner and cancellation prevents late writes',async()=>{const {s,storage,store,get}=syncFixture();let resolve;const engine=s.EvieSync.create({owner:A,key:'a',storage,store,api:()=>new Promise(r=>resolve=r)});const original=json(get());const pending=engine.sync();engine.stop();resolve({owner:B,rows:[],next:''});await pending;assert.deepEqual(json(get()),original);assert.equal(storage.getItem('a-sync-shadow'),null);});

test('JSONB key ordering does not create false conflicts or writes',()=>{const {s}=syncFixture();assert.equal(s.EvieSync.classify({b:2,a:{y:2,x:1}},{a:{x:1,y:2},b:2},{b:2,a:{x:1,y:2}}),'same');assert.equal(s.EvieSync.classify({list:[1,2]},{list:[1,2]},{list:[2,1]}),'remote');});
function mockSyncServer(){const records=new Map();return {records,api:async(path,{body})=>{if(path==='data/pull')return {owner:A,rows:[...records.values()],next:''};const output=body.changes.map(c=>{const k=c.collection+'/'+c.record_id,old=records.get(k);if((old?.revision||0)!==c.expected_revision)throw Object.assign(Error('conflict'),{status:409});return {...c,owner_id:A,revision:c.expected_revision+1};});for(const r of output)records.set(r.collection+'/'+r.record_id,structuredClone(r));return {owner:A,rows:output};}};}
test('two devices merge different records and surface a same-record conflict',async()=>{const server=mockSyncServer(),a=syncFixture(),b=syncFixture();const left=a.s.EvieSync.create({owner:A,key:'a',storage:a.storage,store:a.store,api:server.api}),right=b.s.EvieSync.create({owner:A,key:'b',storage:b.storage,store:b.store,api:server.api});try{assert.equal((await left.sync()).ok,true);assert.equal((await right.sync()).ok,true);a.set(s=>s.transactions.push({id:'legacy-X',amount:100000}));b.set(s=>s.transactions.push({id:'legacy-Y',amount:200000}));assert.equal((await left.sync()).ok,true);assert.equal((await right.sync()).ok,true);await left.sync();assert.equal(a.get().transactions.length,2);a.set(s=>s.transactions.find(r=>r.id==='legacy-X').amount=300000);b.set(s=>s.transactions.find(r=>r.id==='legacy-X').amount=400000);await left.sync();assert.equal((await right.sync()).conflict,true);assert.equal(b.get().transactions.find(r=>r.id==='legacy-X').amount,400000);right.resolve('transactions/legacy-X','local',right.conflicts()[0].reviewVersion);assert.equal((await right.sync()).ok,true);assert.equal(server.records.get('transactions/legacy-X').payload.amount,400000);assert.ok(b.storage.getItem('b-rollback'));}finally{left.stop();right.stop();}});
test('incomplete acknowledgement never clears pending local mutations',async()=>{const f=syncFixture();const engine=f.s.EvieSync.create({owner:A,key:'a',storage:f.storage,store:f.store,api:async path=>path==='data/pull'?{owner:A,rows:[],next:''}:{owner:A,rows:[]}});try{const result=await engine.sync();assert.equal(result.ok,false);assert.match(result.error,/verificación incompleta/);assert.ok(engine.pending()>0);}finally{engine.stop();}});
test('wrong-owner acknowledgement never enters the durable shadow',async()=>{const f=syncFixture();const engine=f.s.EvieSync.create({owner:A,key:'a',storage:f.storage,store:f.store,api:async(path,{body})=>path==='data/pull'?{owner:A,rows:[],next:''}:{owner:A,rows:body.changes.map(c=>({...c,revision:1,owner_id:B}))}});try{assert.equal((await engine.sync()).ok,false);assert.ok(!f.storage.getItem('a-sync-shadow').includes(B));assert.ok(engine.pending()>0);}finally{engine.stop();}});
test('edit during an in-flight push stays queued after acknowledgement',async()=>{const f=syncFixture(),server=mockSyncServer();let release;let pause=false;const engine=f.s.EvieSync.create({owner:A,key:'a',storage:f.storage,store:f.store,api:async(path,args)=>{const response=await server.api(path,args);if(path==='data/push'&&pause)return new Promise(r=>release=()=>r(response));return response;}});try{await engine.sync();f.set(s=>s.transactions.push({id:'keep-exact-ID',amount:100}));pause=true;const p=engine.sync();while(!release)await new Promise(r=>setTimeout(r,1));f.set(s=>s.transactions[0].amount=200);release();assert.equal((await p).ok,true);assert.equal(f.get().transactions[0].amount,200);assert.ok(engine.pending()>0);}finally{engine.stop();}});
test('repeating pagination fails closed without replacing the Store',async()=>{const f=syncFixture(),before=json(f.get());const engine=f.s.EvieSync.create({owner:A,key:'a',storage:f.storage,store:f.store,api:async()=>({owner:A,rows:[],next:'again'})});try{assert.equal((await engine.sync()).ok,false);assert.deepEqual(json(f.get()),before);}finally{engine.stop();}});

let db;
before(async()=>{const {PGlite}=await import('@electric-sql/pglite');db=new PGlite();await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,raw_user_meta_data jsonb);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;`);await db.exec(fs.readFileSync(path.join(root,'supabase/migrations/202609250001_accounts.sql'),'utf8'));
 // Minimal Supabase Storage catalog emulation. RLS is executed by PostgreSQL;
 // HTTP upload limits/MIME sniffing/signing remain outside this test boundary.
 await db.exec(`create schema storage;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets(id),name text not null,metadata jsonb,unique(bucket_id,name));
 create function storage.foldername(text) returns text[] language sql immutable as $$select (string_to_array($1,'/'))[1:array_length(string_to_array($1,'/'),1)-1]$$;
 alter table storage.objects enable row level security;
 grant usage on schema storage to anon,authenticated;
 grant select,insert,update,delete on storage.objects to anon,authenticated;
 insert into storage.buckets values('user-media','user-media',true,null,null),('other-bucket','other-bucket',true,null,null);
 create policy unrelated_permissive_policy on storage.objects for all to authenticated,anon using(true) with check(true);`);
 for(const migration of ['202609250002_media.sql','202609250003_validation_guards.sql'])await db.exec(fs.readFileSync(path.join(root,'supabase/migrations',migration),'utf8'));
 await db.exec(`insert into auth.users values('${A}','{"username":"user-a"}'),('${B}','{"username":"user-b"}');`);});
after(async()=>{await db?.close();});
async function asUser(id,fn){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id]);await db.exec('set role authenticated');try{return await fn();}finally{await db.exec('reset role');}}
const change=(id,amount=100000,revision=0)=>({collection:'transactions',record_id:id,expected_revision:revision,payload:{id,title:'Venta',type:'income',amount,date:'2026-09-25',category:'Ventas'}});
const apply=items=>db.query('select * from public.evie_apply($1::jsonb)',[JSON.stringify(items)]);
const stateChange=(payload,revision=0)=>({collection:'$state',record_id:'root',expected_revision:revision,payload});
test('SQL rejects SQL NULL, JSON null, empty or malformed mutation batches',async()=>{await asUser(A,async()=>{await assert.rejects(db.query('select * from public.evie_apply($1::jsonb)',[null]),/invalid batch/);for(const value of [null,{},true,12,'batch',[],[null],[[]],[1]])await assert.rejects(apply(value));});});
test('SQL requires typed identity and safe integer expected revisions',async()=>{await asUser(A,async()=>{for(const patch of [{collection:null},{record_id:null},{record_id:123},{payload:null},{expected_revision:null},{expected_revision:'0'},{expected_revision:0.5},{expected_revision:-1},{expected_revision:9007199254740991},{payload:{id:123,amount:100}}])await assert.rejects(apply([{...change('typed-row'),...patch}]));assert.equal((await db.query("select * from crm_records where record_id='typed-row'")).rows.length,0);});});
test('SQL requires integer transaction cents even when amount is absent or JSON null',async()=>{await asUser(A,async()=>{for(const amount of [undefined,null,'100',{},[],true,1.5,-1,9007199254740992]){const c=change('invalid-cents');c.payload.amount=amount;await assert.rejects(apply([c]));}});});
test('SQL state metadata rejects absent or wrong version, profile and preferences shapes',async()=>{await asUser(A,async()=>{const base={version:4,profile:{name:'',preferred:''},preferences:{}};for(const value of [{...base,version:undefined},{...base,version:null},{...base,version:'4'},{...base,profile:null},{...base,profile:[]},{...base,preferences:null},{...base,preferences:[]},{...base,profile:{name:null,preferred:''}},{...base,profile:{name:'',preferred:'',greeting_form:null}}])await assert.rejects(apply([stateChange(value)]));assert.equal((await db.query('select * from user_preferences')).rows.length,0);});});
test('SQL valid metadata keeps a neutral profile and uses the same CAS contract',async()=>{await asUser(A,async()=>{const payload={version:4,profile:{name:'',preferred:'',greeting_form:'Hola'},preferences:{}};const r=await apply([stateChange(payload)]);assert.equal(r.rows[0].record_id,'root');assert.equal(Number(r.rows[0].revision),1);await assert.rejects(apply([stateChange(payload)]),/revision conflict/);});});
test('SQL invalid linked operation rolls back records and metadata together',async()=>{await asUser(A,async()=>{const before=(await db.query('select payload,revision from user_preferences')).rows[0];await assert.rejects(apply([change('rollback-guard'),stateChange({version:4,profile:null,preferences:{}},1)]));assert.equal((await db.query("select * from crm_records where record_id='rollback-guard'")).rows.length,0);assert.deepEqual((await db.query('select payload,revision from user_preferences')).rows[0],before);});});
test('SQL text IDs retain case and the maximum 80-byte identifier',async()=>{await asUser(A,async()=>{const ids=['Case-ID','case-id','X'.repeat(80)];const r=await apply(ids.map(id=>change(id)));assert.deepEqual(new Set(r.rows.map(x=>x.record_id)),new Set(ids));await assert.rejects(apply([change('X'.repeat(81))]));});});
test('SQL constraints reject missing payload identity even for privileged maintenance writes',async()=>{for(const payload of [{amount:1},{id:null,amount:1},{id:123,amount:1},{id:'admin-bad',amount:null}])await assert.rejects(db.query('insert into crm_records(owner_id,collection,record_id,payload) values($1,$2,$3,$4)',[A,'transactions','admin-bad',payload]));});

test('Storage migration makes an existing public user-media bucket private',async()=>{const row=(await db.query("select * from storage.buckets where id='user-media'")).rows[0];assert.equal(row.public,false);assert.equal(Number(row.file_size_limit),10485760);assert.deepEqual(row.allowed_mime_types,['image/webp','image/png','image/jpeg']);});
test('Storage RLS isolates object CRUD even with an unrelated permissive policy',async()=>{await asUser(A,()=>db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['user-media',A+'/Legacy-Photo.webp']));await asUser(B,async()=>{assert.equal((await db.query("select * from storage.objects where bucket_id='user-media'")).rows.length,0);assert.equal((await db.query('update storage.objects set metadata=$1 where name=$2 returning id',[{forbidden:true},A+'/Legacy-Photo.webp'])).rows.length,0);assert.equal((await db.query('delete from storage.objects where name=$1 returning id',[A+'/Legacy-Photo.webp'])).rows.length,0);await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['user-media',A+'/forbidden.webp']),/row-level security/);await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['user-media',B+'/Legacy-Photo.webp']);});await asUser(A,async()=>{const rows=(await db.query("select * from storage.objects where bucket_id='user-media'")).rows;assert.deepEqual(rows.map(r=>r.name),[A+'/Legacy-Photo.webp']);await db.query('update storage.objects set metadata=$1 where name=$2',[{verified:true},A+'/Legacy-Photo.webp']);await assert.rejects(db.query('update storage.objects set name=$1 where name=$2',[B+'/moved.webp',A+'/Legacy-Photo.webp']),/row-level security/);assert.equal((await db.query('delete from storage.objects where name=$1 returning id',[A+'/Legacy-Photo.webp'])).rows.length,1);});});
test('Storage RLS rejects traversal, encoded paths and non-image names',async()=>{await asUser(A,async()=>{for(const name of [A+'/../'+B+'/x.webp',A+'//x.webp',A+'/%2e%2e/x.webp',A+'/a%2fb.webp',A+'/file.svg',A+'/file.html',A+'/folder/x.webp',A+'/','x.webp'])await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['user-media',name]),/row-level security/);});});
test('Storage anonymous requests cannot read or insert user media without blocking other buckets',async()=>{await db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['other-bucket','public.txt']);await db.query("select set_config('request.jwt.claim.sub','',false)");await db.exec('set role anon');try{assert.equal((await db.query("select * from storage.objects where bucket_id='user-media'")).rows.length,0);await assert.rejects(db.query('insert into storage.objects(bucket_id,name) values($1,$2)',['user-media',A+'/anon.webp']),/row-level security/);assert.equal((await db.query("select * from storage.objects where bucket_id='other-bucket'")).rows.length,1);}finally{await db.exec('reset role');}});
test('SQL preserves text identity exactly and account B cannot read A',async()=>{await asUser(A,async()=>{const r=await apply([change('Legacy-ABC-0001')]);assert.equal(r.rows[0].record_id,'Legacy-ABC-0001');assert.equal(r.rows[0].owner_id,A);});await asUser(B,async()=>{assert.equal((await db.query('select * from public.crm_records')).rows.length,0);assert.equal((await db.query("select * from public.evie_pull('')")).rows.length,0);});});
test('SQL RLS forbids owner substitution and anonymous private reads',async()=>{await asUser(B,async()=>{await assert.rejects(db.query('insert into public.contacts(owner_id,display_name) values($1,$2)',[A,'forbidden']),/row-level security/);await assert.rejects(apply([{...change('x'),owner_id:A}]),/invalid fields/);});await db.exec('set role anon');try{await assert.rejects(db.query('select * from public.crm_records'),/permission denied/);await assert.rejects(apply([change('anon')]),/permission denied/);}finally{await db.exec('reset role');}});
test('SQL CAS makes linked batches atomic and rejects stale writes',async()=>{await asUser(A,async()=>{await assert.rejects(apply([change('would-be-new'),change('Legacy-ABC-0001',120000,0)]),/revision conflict/);assert.equal((await db.query("select * from public.crm_records where record_id='would-be-new'")).rows.length,0);const update=await apply([change('Legacy-ABC-0001',120000,1)]);assert.equal(Number(update.rows[0].revision),2);});});
test('SQL rejects non-integer cents, invalid IDs and unknown collections',async()=>{await asUser(A,async()=>{for(const ch of [change('bad-decimal',1.5),change('../path'),{...change('ok'),collection:'secrets'}])await assert.rejects(apply([ch]));});});
test('new SQL profiles contain no owner identity and usernames are unique',async()=>{const r=await db.query('select * from public.profiles where id=$1',[B]);assert.equal(r.rows[0].display_name,'');assert.equal(r.rows[0].preferred_name,'');assert.equal(r.rows[0].greeting_form,'Hola');await assert.rejects(db.query('insert into auth.users values($1,$2)',[crypto.randomUUID(),{username:'user-a'}]),/duplicate key/);});
