'use strict';
window.Agenda=(()=>{
 const e=Domain.escape,b=(label,action,extra='',cls='')=>Views.button(label,'rc-'+action,cls,extra),A=V2Domain.assert;
 const priorities={low:'Baja',medium:'Media',high:'Alta'},areas={personal:'Personal',school:'Escuela',soma:'SOMA',farm:'Granja',finance:'Finanzas',gym:'Gimnasio',learning:'Aprendizaje',alvento:'ALVENTO',content:'Contenido',other:'Otra'};
 const localFormatter=new Intl.DateTimeFormat('sv-SE',{timeZone:DALI_CONFIG.timezone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'});
 const localValue=at=>at==null||at===''?'':localFormatter.format(new Date(at)).replace(' ','T');
 function localCandidates(value){if(!value)return [];A(/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/.test(value)&&V2Domain.date(value.slice(0,10))&&Number(value.slice(11,13))<24&&Number(value.slice(14))<60,'Fecha u hora local inválida.');const nominal=Date.parse(value+':00Z'),offsets=new Set();for(const hours of [-36,-12,0,12,36]){const at=nominal+hours*3600000,local=localValue(new Date(at).toISOString());offsets.add(Date.parse(local+':00Z')-at);}const matches=[...offsets].map(offset=>new Date(nominal-offset).toISOString()).filter(at=>localValue(at)===value);return matches.sort();}
 function toTimestamp(value){if(!value)return null;const matches=localCandidates(value);A(matches.length>0,'Esta hora no existió en México por el cambio histórico de horario. Elige una hora válida.');A(matches.length===1,'Esta hora ocurrió dos veces por el cambio histórico de horario. Importa una fecha ISO con desfase explícito para distinguirla.');return matches[0];}
 // RFC 5545 recurrence policy: skip nonexistent times; use the first occurrence of a repeated local time.
 function occurrenceTimestamp(r,date){const time=r.all_day?'23:59':r.recurrence?.time_local||localValue(r.due_at||r.start_at).slice(11)||'23:59';const at=localCandidates(date+'T'+time)[0];return at?new Date(Date.parse(at)+(r.all_day?59999:0)).toISOString():null;}
 const dateOf=r=>(r.due_at||r.start_at)?Domain.today(new Date(r.due_at||r.start_at)):null;
 function occurrence(r,date){if(!r.recurrence)return dateOf(r)===date;const start=dateOf(r);return !!(start&&Recurrence.latest({date:start,recurrence:r.recurrence},date)===date&&(r.all_day||occurrenceTimestamp(r,date)));}
 function isDone(r,date){return r.status==='done'||(r.recurrence&&r.history.some(h=>h.completed&&h.occurrence===date));}
 function complete(s,id,date=Domain.today(),at=new Date().toISOString()){const r=s.agendaItems.find(r=>r.id===id&&!r.deleted_at);A(r,'Pendiente no encontrado.');if(!r.recurrence)return RCData.completeAgenda(s,id,at);A(occurrence(r,date),'Esta fecha no corresponde a una repetición.');if(isDone(r,date))return false;r.history.push({occurrence:date,completed:true,at});r.completed_at=at;r.updated_at=at;return true;}
 function card(r,date=Domain.today()){const done=isDone(r,date),day=r.recurrence?date:dateOf(r),due=day&&day<date&&!done;return `<article class="panel agenda-card"><div class="agenda-card-heading"><span class="tag ${due?'red':''}">${done?'Completado':due?'Vencido':day?Views.date(day):'Sin programar'}</span><span class="tag">${priorities[r.priority]} · ${areas[r.area]}</span></div><h3><a href="#agenda/${e(r.id)}">${e(r.title)}</a></h3><p class="muted">${r.duration_minutes==null?'Duración sin estimar':r.duration_minutes+' min'}${r.recurrence?' · Recurrente':''}${!r.all_day&&r.start_at?' · '+e(localValue(r.start_at).slice(11)):''}</p><div class="toolbar">${!done?b('Completar','agenda-complete',`data-id="${e(r.id)}" data-date="${date}"`,'primary'):''}${b('Editar','agenda-edit',`data-id="${e(r.id)}"`)}${b('Enfoque','agenda-focus',`data-id="${e(r.id)}"`)}</div></article>`;}
 function suggestions(rows,today=Domain.today()){const rank={high:0,medium:1,low:2};return rows.filter(r=>!r.deleted_at&&!['done','archived'].includes(r.status)&&!isDone(r,today)&&(!r.recurrence||occurrence(r,today))).slice().sort((a,b)=>rank[a.priority]-rank[b.priority]||(dateOf(a)||'9999').localeCompare(dateOf(b)||'9999')||a.id.localeCompare(b.id)).slice(0,3);}
 function suggestedView(rows,today){return '<section class="panel detail-card"><h2>Tus siguientes pasos posibles</h2><p>Opciones por prioridad y fecha registradas. Nada se reprograma automáticamente.</p>'+suggestions(rows,today).map(r=>'<div class="key-value"><a href="#agenda/'+e(r.id)+'">'+e(r.title)+'</a>'+b('Revisar horario','agenda-edit','data-id="'+e(r.id)+'"')+'</div>').join('')+'</section>';}
 function timeline(rows,today=Domain.today()){const timed=rows.filter(r=>!r.all_day&&!['archived','done'].includes(r.status)&&occurrence(r,today)&&!isDone(r,today)).map(r=>({r,time:r.recurrence?.time_local||localValue(r.start_at||r.due_at).slice(11)})).sort((a,b)=>a.time.localeCompare(b.time));return `<section class="panel detail-card"><h2>Tu día, en orden</h2><p class="muted">Hora de México · solo horarios registrados, sin asignar espacios automáticamente.</p><ol id="agenda-timeline" class="agenda-timeline">${timed.map(({r,time})=>`<li data-timeline-time="${time}"><time>${time}</time><a href="#agenda/${e(r.id)}">${e(r.title)}</a><small>${r.duration_minutes?r.duration_minutes+' min':'Duración sin estimar'}</small></li>`).join('')}<li id="agenda-now" class="agenda-now"><time></time><strong>Ahora</strong></li></ol>${timed.length?'':'<p>Sin bloques con hora para hoy. Tus pendientes sin horario siguen abajo.</p>'}</section>`;}
 function clock(){const list=document.getElementById('agenda-timeline'),marker=document.getElementById('agenda-now');if(!list||!marker)return;const time=localValue(new Date().toISOString()).slice(11);marker.querySelector('time').textContent=time;const next=[...list.querySelectorAll('[data-timeline-time]')].find(el=>el.dataset.timelineTime>=time);if(next)list.insertBefore(marker,next);else list.append(marker);}
 function render(id){const list=Store.list('agendaItems'),today=Domain.today(),tab=UI.tab.agenda||'today';if(id){const r=list.find(x=>x.id===id);if(!r)return Views.notFound();return Views.heading(e(r.title),'Tu siguiente paso, con contexto.',`<a class="button" href="#agenda">Volver a Agenda</a>`)+card(r)+`<section class="panel detail-card"><h2>Contexto</h2><p class="body-copy">${e(r.notes||'Sin notas adicionales.')}</p>${b('Vincular con…','links',`data-collection="agendaItems" data-id="${e(r.id)}"`)}${b('Descargar calendario','agenda-ics',`data-id="${e(r.id)}"`)}${Views.button('Archivar','delete','',`data-collection="agendaItems" data-id="${e(r.id)}"`)}<h3>Historial</h3>${r.history.map(h=>`<p>${Views.date(h.at)} · ${e(h.occurrence||'Registro')} · ${h.completed?'Completado':'Estado anterior conservado'}</p>`).join('')||'<p>Aún sin cambios registrados.</p>'}</section>`;}
  let content='';const active=list.filter(r=>!['done','archived'].includes(r.status));if(tab==='week'||tab==='calendar'){const start=UI.agendaStart||today,count=tab==='week'?7:28;content=`<label class="toolbar">Desde<input class="input" id="agenda-start" type="date" value="${start}"></label><div class="agenda-week">${Array.from({length:count},(_,n)=>{const date=V2Domain.addDays(start,n),rows=list.filter(r=>r.status!=='archived'&&occurrence(r,date));return `<section class="agenda-day"><h2>${Views.date(date,{weekday:'long',day:'numeric',month:'short'})}</h2>${rows.map(r=>card(r,date)).join('')||'<p class="muted">Sin compromisos registrados</p>'}</section>`;}).join('')}</div>`;}else{const rows=tab==='inbox'?active.filter(r=>!dateOf(r)):tab==='archive'?list.filter(r=>r.status==='done'||r.status==='archived'||r.history.length):active.filter(r=>occurrence(r,today)||(!r.recurrence&&dateOf(r)&&dateOf(r)<today));content=`<div class="agenda-list">${rows.map(r=>card(r)).join('')||`<section class="panel rc-empty"><span class="module-icon">${Views.icon('calendar-check')}</span><h2>${tab==='inbox'?'Un lugar para liberar tu mente':'Tu día tiene espacio'}</h2><p>Captura un pendiente real. Decide la fecha cuando la conozcas.</p>${b('Capturar pendiente','agenda-edit','','primary')}</section>`}</div>`;if(tab==='today'){content=timeline(active,today)+suggestedView(active,today)+content;const inbox=active.filter(r=>!dateOf(r));content+=`<p class="muted">${inbox.length} pendientes sin programar · <a href="#agenda" data-action="rc-agenda-tab" data-tab="inbox">Revisar bandeja</a></p>`;}}
  return Views.heading('Agenda','Haz espacio para lo importante.',b('Capturar pendiente','agenda-edit','','primary')+b('Exportar .ics','agenda-ics'),'UN DÍA, UNA DIRECCIÓN')+`<nav class="tabs" aria-label="Vistas de Agenda">${[['inbox','Bandeja'],['today','Hoy'],['week','Semana'],['calendar','Calendario'],['archive','Completados']].map(([k,l])=>b(l,'agenda-tab',`data-tab="${k}" aria-current="${tab===k?'page':'false'}"`,tab===k?'primary':'')).join('')}</nav>`+content;
 }
 function edit(id,preset={}){const r={...RCData.defaults('agendaItems'),...Store.list('agendaItems').find(x=>x.id===id),...preset},F=Forms;F.form(id?'Editar pendiente':'Captura tu siguiente paso','Solo el título es obligatorio. Nada se programa ni vincula sin confirmar.',F.field('title','¿Qué necesitas hacer?',r.title,'text','required',true)+F.select('kind','Tipo',[['task','Tarea'],['event','Evento'],['time_block','Bloque de tiempo'],['reminder','Recordatorio']],r.kind)+F.select('priority','Prioridad',Object.entries(priorities),r.priority)+F.select('area','Área',Object.entries(areas),r.area)+F.field('duration_minutes','Duración · minutos (opcional)',r.duration_minutes??'','number','min="1" max="10080" step="1"')+`<details class="form-details" data-neural-essential><summary>Horario y repetición</summary><div class="form-grid">`+F.field('start','Inicio · hora de México',localValue(r.start_at),'datetime-local')+F.field('due','Límite · hora de México',localValue(r.due_at),'datetime-local')+F.check('all_day','Todo el día',r.all_day)+F.select('frequency','Repetición',[['','No repetir'],['daily','Diaria'],['weekly','Semanal'],['monthly','Mensual'],['yearly','Anual']],r.recurrence?.frequency||'')+F.field('interval','Cada N periodos',r.recurrence?.interval||1,'number','min="1" max="365" required')+F.field('end_date','Fin de repetición',r.recurrence?.end_date||'','date')+'</div></details>'+F.select('energy','Energía necesaria',Object.entries(priorities),r.energy)+F.area('notes','Contexto / notas',r.notes)+EntityLinks.pickerMarkup(),d=>{const start=d.start===localValue(r.start_at)?r.start_at:toTimestamp(d.start),due=d.due===localValue(r.due_at)?r.due_at:toTimestamp(d.due);const recurrence=d.frequency?{...r.recurrence,frequency:d.frequency,interval:Number(d.interval),timezone:DALI_CONFIG.timezone,time_local:(d.start||d.due).slice(11)||null,days_of_week:r.recurrence?.days_of_week||[],day_of_month:r.recurrence?.day_of_month||null,end_date:d.end_date||null}:null;
 saveLinked({...r,title:d.title.trim(),kind:d.kind,priority:d.priority,area:d.area,duration_minutes:d.duration_minutes?Number(d.duration_minutes):null,start_at:start,due_at:due,all_day:!!d.all_day,energy:d.energy,recurrence,notes:d.notes,status:r.status==='done'?r.status:(start||due?'scheduled':'inbox')},id,d.linked_endpoint);});EntityLinks.mountPicker(document.querySelector('[data-link-picker]'),id?{collection:'agendaItems',id}:null);}
 function saveLinked(record,id,endpoint){const now=new Date().toISOString();record={...record,id:id||crypto.randomUUID(),created_at:record.created_at||now,updated_at:now};Store.save(s=>{const n=s.agendaItems.findIndex(r=>r.id===record.id);if(n<0)s.agendaItems.push(record);else s.agendaItems[n]=record;if(endpoint)EntityLinks.create(s,{collection:'agendaItems',id:record.id},JSON.parse(endpoint));});}
 function timezoneComponent(firstYear,lastYear){
  A(Number.isInteger(firstYear)&&Number.isInteger(lastYear)&&firstYear>=1&&lastYear<=9998&&lastYear>=firstYear&&lastYear-firstYear<=500,'El calendario recurrente admite hasta 500 años por exportación. Reduce el intervalo.');
  const compact=v=>v.replace(/[-:]/g,''),offset=at=>Math.round((Date.parse(localValue(at)+':00Z')-Math.floor(at/60000)*60000)/60000),offsetText=n=>(n<0?'-':'+')+String(Math.floor(Math.abs(n)/60)).padStart(2,'0')+String(Math.abs(n)%60).padStart(2,'0');
  const start=Date.parse(String(firstYear).padStart(4,'0')+'-01-01T00:00:00Z'),end=Date.parse(String(lastYear+1).padStart(4,'0')+'-01-01T00:00:00Z');let previous=start,current=offset(start);
  const lines=['BEGIN:VTIMEZONE','TZID:'+DALI_CONFIG.timezone,'BEGIN:STANDARD','DTSTART:'+compact(localValue(start))+ '00','TZOFFSETFROM:'+offsetText(current),'TZOFFSETTO:'+offsetText(current),'END:STANDARD'];
  for(let at=start+86400000;at<=end;at+=86400000){const next=offset(at);if(next!==current){let low=previous/60000,high=at/60000;while(high-low>1){const mid=Math.floor((low+high)/2);if(offset(mid*60000)===current)low=mid;else high=mid;}const transition=high*60000,kind=next>current?'DAYLIGHT':'STANDARD',localBefore=new Date(transition+current*60000).toISOString().slice(0,19).replace(/[-:]/g,'');lines.push('BEGIN:'+kind,'DTSTART:'+localBefore,'TZOFFSETFROM:'+offsetText(current),'TZOFFSETTO:'+offsetText(next),'END:'+kind);current=next;}previous=at;}
  lines.push('END:VTIMEZONE');return lines;
 }
 function ics(rows,at=new Date().toISOString()){const esc=v=>String(v||'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,'),utc=v=>new Date(v).toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');const out=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//DALI//Agenda local//ES','CALSCALE:GREGORIAN','METHOD:PUBLISH'];const zoned=rows.filter(r=>!r.deleted_at&&r.recurrence&&!r.all_day&&(r.start_at||r.due_at));if(zoned.length){const first=Math.min(...zoned.map(r=>Number(dateOf(r).slice(0,4)))),last=Math.max(new Date(at).getUTCFullYear()+2,...zoned.map(r=>Number((r.recurrence.end_date||dateOf(r)).slice(0,4))));out.push(...timezoneComponent(Math.max(1,first-1),last));}for(const r of rows.filter(r=>!r.deleted_at&&(r.start_at||r.due_at))){out.push('BEGIN:VEVENT','UID:'+r.id+'@dali.local','DTSTAMP:'+utc(at),'SUMMARY:'+esc(r.title),'DESCRIPTION:'+esc(r.notes));const start=r.start_at||r.due_at;if(r.all_day){const date=Domain.today(new Date(start));out.push('DTSTART;VALUE=DATE:'+date.replaceAll('-',''),'DTEND;VALUE=DATE:'+V2Domain.addDays(Domain.today(new Date(r.due_at||start)),1).replaceAll('-',''));}else if(r.recurrence){const local=localValue(start).slice(0,10)+'T'+(r.recurrence.time_local||localValue(start).slice(11));out.push('DTSTART;TZID='+DALI_CONFIG.timezone+':'+local.replace(/[-:]/g,'')+'00');const seconds=r.due_at&&Date.parse(r.due_at)>Date.parse(start)?Math.round((Date.parse(r.due_at)-Date.parse(start))/1000):r.duration_minutes*60;if(seconds)out.push('DURATION:PT'+seconds+'S');}else{out.push('DTSTART:'+utc(start));if(r.due_at&&Date.parse(r.due_at)>Date.parse(start))out.push('DTEND:'+utc(r.due_at));else if(r.duration_minutes)out.push('DURATION:PT'+r.duration_minutes+'M');}if(r.recurrence){const rec=r.recurrence;let rule='FREQ='+rec.frequency.toUpperCase()+';INTERVAL='+rec.interval;if(rec.end_date)rule+=';UNTIL='+(r.all_day?rec.end_date.replaceAll('-',''):utc(occurrenceTimestamp({...r,all_day:true},rec.end_date)));if(rec.days_of_week?.length)rule+=';BYDAY='+rec.days_of_week.map(n=>['SU','MO','TU','WE','TH','FR','SA'][n]).join(',');if(['monthly','yearly'].includes(rec.frequency)){const day=rec.day_of_month||Number(dateOf(r).slice(8));if(rec.frequency==='yearly')rule+=';BYMONTH='+Number(dateOf(r).slice(5,7));rule+=';BYMONTHDAY='+day+(day>=28?',-1;BYSETPOS=1':'');}if(rec.frequency==='weekly')rule+=';WKST=MO';out.push('RRULE:'+rule);}out.push('END:VEVENT');}out.push('END:VCALENDAR');return out.map(line=>{let result='',n=0;for(const char of line){const bytes=new TextEncoder().encode(char).length;if(n+bytes>73){result+='\r\n ';n=1;}result+=char;n+=bytes;}return result;}).join('\r\n')+'\r\n';}
 return {render,edit,card,complete,suggestions,dateOf,occurrence,isDone,ics,localValue,toTimestamp,occurrenceTimestamp,timezoneComponent,timeline,clock,areas,priorities};
})();
