import fs from 'node:fs/promises';
import path from 'node:path';
import {createHash} from 'node:crypto';
const root=path.resolve(import.meta.dirname,'..','public');
const html=await fs.readFile(path.join(root,'index.html'),'utf8');
const files=new Set(['/','/manifest.webmanifest','/icon.svg','/icons/ivy-192.png','/icons/ivy-512.png','/pcm-recorder.js','/vendor/three.module.min.js','/vendor/three.core.min.js']);
for(const [,file] of html.matchAll(/(?:src|href)="([^"#]+)"/g))if(!file.includes(':')&&!file.startsWith('/')&&/\.(js|css|png|svg|webmanifest)$/.test(file))files.add('/'+file);
const list=[...files].sort(),hash=createHash('sha256');
// Pages redirects /index.html to /. Cache the canonical URL, not a redirect.
for(const file of list){hash.update(file);hash.update(await fs.readFile(path.join(root,file==='/'?'index.html':file.slice(1))));}
hash.update(await fs.readFile(path.join(root,'sw.js')));
const output='// Generated by scripts/build-shell.mjs; public static files only.\nconst SHELL_VERSION='+JSON.stringify(hash.digest('hex').slice(0,20))+';\nconst SHELL_FILES='+JSON.stringify(list,null,2)+';\n';
await fs.writeFile(path.join(root,'sw-manifest.js'),output);
console.log(`EVIE PWA: ${list.length} static assets; no API or private responses cached.`);
