'use strict';
window.EntityLinks=(()=>{
 const names={agendaItems:'Agenda',goals:'Objetivos',clients:'SOMA',farmAnimals:'Cerdos',farmTasks:'Pendientes de Granja',contentItems:'Contenido',skills:'Aprendizaje',studySessions:'Sesiones de estudio',alventoMilestones:'Hitos ALVENTO',alventoDrops:'Drops',books:'Libros',visionItems:'Vision',gymSessions:'Entrenamientos',journal:'Bitácora',transactions:'Finanzas',nutritionDays:'Alimentación',pantryItems:'Despensa',groceryRuns:'Compras de despensa'};
 const routes={agendaItems:'agenda',goals:'objetivos',clients:'soma',farmAnimals:'granja',farmTasks:'granja',contentItems:'contenido',skills:'aprendizaje',studySessions:'aprendizaje',alventoMilestones:'alvento',alventoDrops:'alvento',books:'libros',visionItems:'vision',gymSessions:'gimnasio',journal:'bitacora',transactions:'finanzas',nutritionDays:'gimnasio',pantryItems:'gimnasio',groceryRuns:'gimnasio'};
 function create(s,source,target,relation='related'){V2Domain.assert(names[source.collection]&&names[target.collection],'Tipo de registro no vinculable.');const same=(a,b)=>RCData.endpointKey(a)===RCData.endpointKey(b),old=s.entityLinks.find(r=>!r.deleted_at&&r.relation===relation&&((same(r.source,source)&&same(r.target,target))||(same(r.source,target)&&same(r.target,source))));if(old)return old;const now=new Date().toISOString(),r={id:crypto.randomUUID(),source:{...source},target:{...target},relation,creation_source:'manual',created_at:now,updated_at:now};s.entityLinks.push(r);return r;}
 function endpointLink(ep){const base=routes[ep.collection];return '#'+base+(['agendaItems','clients','farmAnimals','contentItems','skills','alventoDrops','books','visionItems','gymSessions','journal'].includes(ep.collection)?'/'+ep.id:'')+(ep.child?'/'+ep.child.collection+'/'+ep.child.id:'');}
 function focusTarget(child=UI.linkedChild){if(!child)return false;const control=document.querySelector('#main-content [data-child-collection="'+CSS.escape(child.collection)+'"][data-child-id="'+CSS.escape(child.id)+'"]');if(!control){App.toast('El registro vinculado ya no está disponible en esta ficha.');return false;}for(let p=control.parentElement;p;p=p.parentElement)if(p.tagName==='DETAILS')p.open=true;control.focus({preventScroll:true});control.scrollIntoView({block:'center',behavior:'instant'});return true;}
 function assertChildRemovable(s,collection,id,child){const key=RCData.endpointKey({collection,id,child});V2Domain.assert(!s.entityLinks.some(link=>!link.deleted_at&&[link.source,link.target].some(ep=>RCData.endpointKey(ep)===key)),'Esta actividad tiene vínculos activos. Retíralos desde «Vincular» antes de eliminarla; los otros registros se conservarán.');}
 function open(collection,id,child=null){const e=Domain.escape,source={collection,id,...(child?{child}: {})},r=RCData.resolveEndpoint(Store.get(),source);V2Domain.assert(r&&names[collection],'Registro no disponible para vincular.');App.openDialog('Relacionado con…',`<p class="dialog-subtitle">${e(r.title||r.ear_tag||r.name)} · Vincular no duplica dinero, inventario ni progreso. Quitar un vínculo conserva ambos registros.</p><label>Buscar un registro<input id="link-search" class="input full-width" placeholder="Título o identificador" autocomplete="off"></label><div id="link-results"></div><h3>Vínculos actuales</h3><div id="current-links"></div>`);const input=document.getElementById('link-search'),results=document.getElementById('link-results'),current=document.getElementById('current-links');
  function render(){const links=Store.list('entityLinks').filter(x=>[x.source,x.target].some(p=>RCData.endpointKey(p)===RCData.endpointKey(source)));current.innerHTML=links.map(x=>{const ep=RCData.endpointKey(x.source)===RCData.endpointKey(source)?x.target:x.source,record=RCData.resolveEndpoint(Store.get(),ep);return `<div class="key-value"><a href="${e(endpointLink(ep))}" data-action="search-link">${e(names[ep.collection])} · ${e(record.title||record.name||record.ear_tag||record.date)}${record.deleted_at?' · archivado':''}</a><button class="button" data-unlink="${x.id}">Quitar vínculo</button></div>`;}).join('')||'<p class="muted">Sin vínculos confirmados.</p>';current.querySelectorAll('[data-unlink]').forEach(button=>button.onclick=()=>{const row=button.parentElement;row.innerHTML='<p>¿Quitar solo este vínculo?</p><button class="button" data-cancel>Cancelar</button><button class="button" data-confirm>Quitar vínculo</button>';row.querySelector('[data-cancel]').onclick=render;row.querySelector('[data-confirm]').onclick=()=>{try{Store.remove('entityLinks',button.dataset.unlink);render();App.toast('Vínculo retirado. Ambos registros se conservan.');}catch(err){App.toast(err.message,'error');}};});}
  function search(){const q=input.value.toLocaleLowerCase().trim();if(!q){results.innerHTML='<p class="muted">Escribe para buscar. No se muestran tus registros antes de buscar.</p>';return;}const rows=Object.keys(names).flatMap(c=>Store.list(c).flatMap(r=>{const parent={collection:c,r,endpoint:{collection:c,id:r.id},title:r.title||r.name||r.ear_tag||r.date||names[c]},nested=({skills:'tasks',clients:'deliverables',contentItems:'shots'})[c];return [parent,...(nested?(r[nested]||[]).filter(item=>item.id).map(item=>({collection:c,r:item,endpoint:{collection:c,id:r.id,child:{collection:nested,id:item.id}},title:(item.title||'Actividad')+' · '+parent.title})):[])];})).filter(x=>RCData.endpointKey(x.endpoint)!==RCData.endpointKey(source)&&(x.title+' '+x.r.id).toLocaleLowerCase().includes(q)).slice(0,20);results.innerHTML=rows.map((x,n)=>`<button class="search-result full-width" data-result="${n}"><span><strong>${e(x.title)}</strong><small>${names[x.collection]}</small></span><span>Vincular</span></button>`).join('')||'<p>Sin coincidencias.</p>';results.querySelectorAll('[data-result]').forEach(button=>button.onclick=()=>{const x=rows[Number(button.dataset.result)];try{Store.save(s=>create(s,source,x.endpoint));render();App.toast('Vínculo confirmado. Sin efectos automáticos.');}catch(err){App.toast(err.message,'error');}});}
  input.oninput=search;render();search();input.focus();
 }
 function pickerMarkup(){return '<section class="full" data-link-picker><h3>Vincular con… · opcional</h3><label>Buscar registro<input type="search" class="input" data-link-query placeholder="Título o identificador"></label><input type="hidden" name="linked_endpoint" value=""><p data-link-selected>Sin vínculo. Se crea solo al guardar.</p><div data-link-options></div><button class="button" type="button" data-link-clear>Quitar selección</button></section>';}
 function mountPicker(root,source){const q=root.querySelector('[data-link-query]'),out=root.querySelector('[data-link-options]'),input=root.querySelector('[name="linked_endpoint"]'),label=root.querySelector('[data-link-selected]');const choose=(ep,title)=>{input.value=ep?JSON.stringify(ep):'';label.textContent=ep?'Al guardar: '+title:'Sin vínculo. Se crea solo al guardar.';out.replaceChildren();input.dispatchEvent(new Event('input',{bubbles:true}));};root.querySelector('[data-link-clear]').onclick=()=>choose(null);q.oninput=()=>{out.replaceChildren();const query=q.value.trim().toLowerCase();if(!query)return;let count=0;for(const c of Object.keys(names))for(const r of Store.list(c)){const nested=({skills:'tasks',clients:'deliverables',contentItems:'shots'})[c],rows=[{r,ep:{collection:c,id:r.id}},...(nested?(r[nested]||[]).filter(x=>x.id&&!x.deleted_at).map(x=>({r:x,ep:{collection:c,id:r.id,child:{collection:nested,id:x.id}}})):[])];for(const x of rows){const title=x.r.title||x.r.name||x.r.ear_tag||x.r.date||names[c];if(count>=20||source&&RCData.endpointKey(source)===RCData.endpointKey(x.ep)||!(title+' '+x.r.id).toLowerCase().includes(query))continue;const button=document.createElement('button');button.type='button';button.className='button search-result full-width';button.textContent=names[c]+' · '+title;button.onclick=()=>choose(x.ep,title);out.append(button);count++;}}if(!count)out.textContent='Sin coincidencias.';};}
 return {create,open,names,routes,endpointLink,focusTarget,assertChildRemovable,pickerMarkup,mountPicker};
})();
