'use strict';
window.Farm=(()=>{
 const {assert,integer,date,addDays,days}=V2Domain;
 const settings=s=>s.farmSettings.at(-1);
 const stamp=()=>new Date().toISOString();
 function event(s,animalId,type,payload,eventId=crypto.randomUUID()){
  if(s.farmEvents.some(e=>e.id===eventId))return;
  const a=s.farmAnimals.find(x=>x.id===animalId&&!x.deleted_at);assert(a,'Animal no encontrado.');assert(date(payload.date),'Fecha inválida.');const previous=s.farmEvents.filter(e=>e.animal_id===a.id&&!e.reverted_at).at(-1);assert(!previous||payload.date>=previous.date,'No registres un evento anterior al último. Usa una corrección auditada.');
  const before=structuredClone(a),now=stamp(),e={id:eventId,animal_id:a.id,type,...payload,created_at:now,updated_at:now,before};
  if(['mating','farrowing','weaning','sale'].includes(type))assert(a.status==='active','El animal debe estar activo.');
  if(type==='mating'){assert(a.role==='sow'&&a.reproductive_state==='empty','La monta requiere una puerca vacía.');assert(payload.sire_name&&payload.sire_name.trim(),'Indica el semental activo.');a.reproductive_state='gestation';a.sire_name=payload.sire_name;}
  if(type==='farrowing'){assert(a.role==='sow'&&a.reproductive_state==='gestation','Registra la gestación o una corrección antes del parto.');assert(integer(payload.born_total)&&integer(payload.born_alive)&&payload.born_alive<=payload.born_total,'Conteos de nacimientos inválidos.');assert(!s.farmLitters.some(l=>l.event_id===eventId),'El parto ya tiene una camada.');const litter={id:crypto.randomUUID(),event_id:eventId,dam_id:a.id,sire_name:a.sire_name||null,birth_date:payload.date,born_total:payload.born_total,born_alive:payload.born_alive,stillborn:payload.born_total-payload.born_alive,weaned:null,notes:payload.notes||'',created_at:now,updated_at:now};s.farmLitters.push(litter);e.litter_id=litter.id;a.reproductive_state='lactation';}
  if(type==='weaning'){assert(a.reproductive_state==='lactation','El destete requiere lactancia.');const l=s.farmLitters.filter(l=>l.dam_id===a.id&&l.weaned==null&&!l.deleted_at).at(-1);assert(l,'No existe una camada activa.');assert(integer(payload.weaned)&&payload.weaned<=l.born_alive,'Conteo de destetados inválido.');e.litter_before=structuredClone(l);e.litter_id=l.id;l.weaned=payload.weaned;l.weaned_at=payload.date;l.losses=l.born_alive-payload.weaned;l.destination=payload.destination||'';l.updated_at=now;a.reproductive_state='empty';}
  if(type==='sale'){assert(a.reproductive_state!=='lactation','Cierra o corrige primero la camada en lactancia.');a.status='sold';if(payload.amount){assert(integer(payload.amount,1),'Importe de venta inválido.');s.transactions.push({id:crypto.randomUUID(),title:'Venta · Arete '+a.ear_tag,type:'income',amount:payload.amount,date:payload.date,category:'Ventas',business_unit:'granja',origin:eventId,source:'farm-sale',related_entity_type:'animal',related_entity_id:a.id,created_at:now,updated_at:now});}}
  if(type==='death')a.status='deceased';if(type==='transfer')a.status='transferred';
  if(type==='state_correction'){assert(textReason(payload.notes),'Explica el motivo de la corrección.');assert(['empty','gestation','lactation','not_applicable'].includes(payload.reproductive_state),'Estado inválido.');a.reproductive_state=payload.reproductive_state;}
  if(['mating','farrowing','weaning','state_correction'].includes(type))a.current_state_since=payload.date;
  a.updated_at=now;e.after=structuredClone(a);s.farmEvents.push(e);
 }
 const textReason=v=>typeof v==='string'&&v.trim().length>=5;
 function revert(s,id){const e=s.farmEvents.find(x=>x.id===id);assert(e&&!e.reverted_at,'Evento no disponible.');const later=s.farmEvents.filter(x=>x.animal_id===e.animal_id&&!x.reverted_at).at(-1);assert(later.id===id,'Hay eventos posteriores. Revierte primero el último.');const index=s.farmAnimals.findIndex(a=>a.id===e.animal_id);assert(JSON.stringify(s.farmAnimals[index])===JSON.stringify(e.after),'El animal cambió después. No se sobrescribirán cambios posteriores.');s.farmAnimals[index]=structuredClone(e.before);e.reverted_at=stamp();if(e.litter_before){s.farmLitters[s.farmLitters.findIndex(l=>l.id===e.litter_id)]=e.litter_before;}else if(e.litter_id)s.farmLitters.find(l=>l.id===e.litter_id).deleted_at=stamp();for(const t of s.transactions.filter(t=>t.origin===id))t.deleted_at=stamp();}
 function alerts(s){const f=settings(s),out=[];for(const a of s.farmAnimals.filter(a=>a.status==='active'&&!a.deleted_at)){if(a.current_state_since&&['gestation','lactation'].includes(a.reproductive_state)){out.push({id:a.id,title:'Arete '+a.ear_tag,detail:a.reproductive_state==='gestation'?'Parto esperado':'Destete objetivo',date:addDays(a.current_state_since,a.reproductive_state==='gestation'?f.gestation_days:f.lactation_days),route:'granja/'+a.id});}}
  for(const l of s.farmLitters.filter(l=>!l.deleted_at&&l.weaned==null))for(const m of f.milestones.filter(m=>m.enabled))out.push({id:l.id+'-'+m.day,title:'Camada · '+(s.farmAnimals.find(a=>a.id===l.dam_id)?.ear_tag||'—'),detail:m.title+' · Confirma protocolo veterinario',date:addDays(l.birth_date,m.day),route:'granja/'+l.dam_id});
  for(const h of s.farmHealthRecords.filter(h=>!h.deleted_at&&h.next_date))out.push({id:h.id,title:'Salud · '+(s.farmAnimals.find(a=>a.id===h.animal_id)?.ear_tag||''),detail:h.observation,date:h.next_date,route:'granja/'+h.animal_id});return out.sort((a,b)=>a.date.localeCompare(b.date));
 }
 function metrics(s,animalId){const ls=s.farmLitters.filter(l=>!l.deleted_at&&(!animalId||l.dam_id===animalId)),closed=ls.filter(l=>l.weaned!=null),live=closed.reduce((n,l)=>n+l.born_alive,0),weaned=closed.reduce((n,l)=>n+l.weaned,0);return {sample:ls.length,closed:closed.length,bornAverage:ls.length?ls.reduce((n,l)=>n+l.born_alive,0)/ls.length:null,weanedAverage:closed.length?weaned/closed.length:null,mortality:live?Math.max(0,live-weaned)/live*100:null};}
 return {settings,event,revert,alerts,metrics};
})();
