'use strict';
window.Importer=(()=>{
 const A=V2Domain.assert,uuid=()=>crypto.randomUUID(),UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
 const allow={finance:{transaction:'transactions',bill:'bills',loan:'loans',payment:'@payment'},objectives:{goal:'goals'},soma:{client:'clients',deliverable:'@deliverable',installment:'@installment',note:'@note'},journal:{entry:'journal'},agenda:{task:'agendaItems',event:'agendaItems',time_block:'agendaItems',reminder:'agendaItems'},system:{entity_link:'entityLinks'},gym:{nutrition_day:'nutritionDays',pantry_item:'pantryItems',grocery_run:'groceryRuns',session:'gymSessions',body_metric:'metrics',imported_rank:'gymRanks'},learning:{skill:'skills',route:'@route',activity:'@activity',study_session:'studySessions'},farm:{animal:'farmAnimals',event:'@farmEvent',litter:'farmLitters',health_record:'farmHealthRecords',setting:'farmSettings',task:'farmTasks',feed_product:'farmFeedProducts',feed_price:'farmFeedPriceHistory',feed_rule:'farmFeedRules',feed_opening:'@feedOpening',feed_purchase:'@feedPurchase',feed_consumption:'@feedConsumption'},books:{book:'books'},alvento:{drop:'alventoDrops',product:'alventoProducts',milestone:'alventoMilestones'},content:{content_item:'contentItems',shot:'@shot',metric_snapshot:'@snapshot'},vision:{vision_item:'visionItems'},profile:{profile_patch:'@profile'}};
 function parse(raw){A(new Blob([raw]).size<=DALI_CONFIG.limits.jsonBytes,'El JSON supera 1 MB.');let d;try{d=JSON.parse(raw);}catch{throw new Error('JSON mal formado. Revisa comas, comillas y llaves.');}V2Domain.safeTree(d);A(d&&typeof d==='object'&&!Array.isArray(d),'Se esperaba un documento JSON.');A(UUID.test(d.import_id||''),'import_id debe ser un UUID válido.');const versions={'dali.crm.import':'2.0','dali.gym.session':'1.0','dali.learning.route':'1.0','dali.journal.entry':'1.0'};A(Object.hasOwn(versions,d.format)&&d.schema_version===versions[d.format],'Formato o schema_version no compatible.');A(d.timezone===DALI_CONFIG.timezone,'Usa timezone America/Mexico_City.');return d;}
 function operations(d){if(d.format==='dali.journal.entry')return [JournalData.operation(d)];if(d.format==='dali.crm.import'){A(Array.isArray(d.operations)&&d.operations.length>0&&d.operations.length<=500,'Se requieren entre 1 y 500 operaciones.');return d.operations;}if(d.format==='dali.gym.session')return [{operation_id:'session',module:'gym',entity:'session',action:'upsert',dedupe_key:'gym:'+(d.session?.source_workout_id||d.session?.date+':'+d.session?.title),payload:d.session}];return [{operation_id:'route',module:'learning',entity:'route',action:'upsert',dedupe_key:'route:'+(d.target?.skill_id||d.target?.skill_title),payload:{target:d.target,route:d.route}}];}
 function reference(value,ids){if(Array.isArray(value))return value.map(v=>reference(v,ids));if(value&&typeof value==='object'){if(Object.keys(value).length===1&&Object.hasOwn(value,'$ref')){A(ids.has(value.$ref),'Referencia a operación inexistente: '+value.$ref);return ids.get(value.$ref);}return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,reference(v,ids)]));}return value;}
 function routeInto(s,p,id,strategy,warnings){const target=p.target||{},route=p.route;A(route&&Array.isArray(route.levels)&&target.skill_title,'La ruta requiere target.skill_title y route.levels.');const existing=target.skill_id?s.skills.find(x=>x.id===target.skill_id):s.skills.find(x=>x.title===target.skill_title&&!x.deleted_at);A(!target.skill_id||existing,'La habilidad seleccionada no existe.');const keys=new Set(),tasks=[];
  for(const level of route.levels){A(Number.isInteger(level.level)&&level.level>=0&&level.level<=6&&Array.isArray(level.activities),'Nivel inválido.');for(const t of level.activities)tasks.push({...t,level:level.level});}if(route.final_project&&!tasks.some(t=>t.activity_key===route.final_project.activity_key))tasks.push({...route.final_project,level:6,final:true});A(tasks.length>0&&tasks.length<=500,'Ruta vacía o demasiado grande.');
  for(const t of tasks){A(typeof t.activity_key==='string'&&t.activity_key&&!keys.has(t.activity_key),'activity_key inválida o duplicada.');keys.add(t.activity_key);A(V2Domain.integer(t.points,1,1000)&&V2Domain.text(t.title),'Puntos/título de actividad inválidos.');for(const resource of t.resources||[]){const url=typeof resource==='string'?resource:resource.url;A(V2Domain.safeUrl(url),'Recurso sin URL http/https válida.');}}
  for(const t of tasks)for(const k of t.prerequisites||[])A(keys.has(k)||(existing?.tasks||[]).some(x=>x.activity_key===k),'Prerequisito inexistente: '+k);
  const nextTasks=tasks.map(t=>{const prev=existing?.tasks.find(x=>x.activity_key===t.activity_key);return {...t,id:prev?.id||uuid(),done:prev?.done||false,evidence:prev?.evidence||'',final:t.final||t.level===6};});
  const skill={...Records.defaults('skills'),...existing,id:existing?.id||id,title:target.skill_title,category:route.category||existing?.category||'Aprendizaje',reason:route.reason||'',minutes:route.weekly_minutes||120,disclaimer:route.disclaimer||'',tasks:strategy==='replace'?nextTasks:[...(existing?.tasks||[]).filter(t=>!keys.has(t.activity_key)),...nextTasks]};if(existing){skill.routeHistory=[...(existing.routeHistory||[]),{at:new Date().toISOString(),tasks:existing.tasks}];s.skills[s.skills.indexOf(existing)]=skill;warnings.push(strategy==='replace'?'Se reemplaza la ruta; la anterior se conserva en historial y deshacer.':'Fusión: se conserva el progreso y la evidencia existente.');}else s.skills.push(skill);return skill;
 }
 function preview(raw,{strategy='merge',skillId=null,omitNarrative=true,journalActions=[]}={}){
  const document=typeof raw==='string'?parse(raw):parse(JSON.stringify(raw));const base=Store.get();const known=base.importBatches.find(b=>b.import_id===document.import_id&&!b.undone_at);if(known)return {already:true,document,plans:[],warnings:['Este lote ya fue importado. No se crearon duplicados.']};
  A(['merge','replace','cancel'].includes(strategy),'Estrategia inválida.');A(strategy!=='cancel','Importación cancelada sin cambios.');
  const ops=operations(document);if(document.format==='dali.journal.entry'){A(Array.isArray(journalActions)&&journalActions.every(n=>Number.isInteger(n)&&n>=0&&n<document.entry.next_actions.length),'Selección de acciones inválida.');for(const n of new Set(journalActions)){const x=document.entry.next_actions[n];ops.push({operation_id:'journal-action-'+n,module:'agenda',entity:'task',action:'upsert',dedupe_key:ops[0].dedupe_key+':action:'+n,payload:{title:x.title,priority:x.priority,duration_minutes:x.duration_minutes??null,notes:'Sugerencia revisada. Fecha orientativa: '+(x.due_hint||'sin fecha')}});}}
  const s=structuredClone(base),plans=[],warnings=[],ids=new Map(),opNames=new Set(),dedupes=new Set(),now=new Date().toISOString();
  for(const op of ops){A(typeof op.operation_id==='string'&&op.operation_id&&!opNames.has(op.operation_id),'operation_id vacía o duplicada.');opNames.add(op.operation_id);A(Object.hasOwn(allow,op.module)&&Object.hasOwn(allow[op.module],op.entity),'Módulo/entidad no permitido.');A(['upsert','create','update'].includes(op.action),'Solo se permiten create, update o upsert.');A(typeof op.dedupe_key==='string'&&op.dedupe_key&&!dedupes.has(op.dedupe_key),'dedupe_key vacía o duplicada en el lote.');dedupes.add(op.dedupe_key);A(op.payload&&typeof op.payload==='object'&&!Array.isArray(op.payload),'Payload inválido.');const c=allow[op.module][op.entity],old=!c.startsWith('@')?s[c].find(r=>(op.payload.id&&r.id===op.payload.id)||r.dedupe_key===op.dedupe_key):null;if(op.payload.id)A(UUID.test(op.payload.id),'payload.id debe ser UUID.');if(op.action==='update'&&!c.startsWith('@'))A(old,'No existe el registro a actualizar.');ids.set(op.operation_id,old?.id||op.payload.id||uuid());}
  // Resolve existing nested IDs before links, including forward $ref references.
  const nestedAdapters={'@deliverable':['clients','client_id','deliverables'],'@installment':['clients','client_id','installments'],'@note':['clients','client_id','notes'],'@activity':['skills','skill_id','tasks'],'@shot':['contentItems','content_id','shots'],'@snapshot':['contentItems','content_id','snapshots']};
  for(const op of ops){const adapter=nestedAdapters[allow[op.module][op.entity]];if(!adapter)continue;const [col,key,arr]=adapter,p=reference(op.payload,ids),parent=s[col].find(r=>r.id===p[key]),old=parent?.[arr]?.find(r=>r.dedupe_key===op.dedupe_key||(p.id&&r.id===p.id));if(old)ids.set(op.operation_id,old.id);}
  // Parent records are materialized before dependent actions; references are resolved in this pass.
  const ordered=[...ops.filter(o=>!allow[o.module][o.entity].startsWith('@')),...ops.filter(o=>allow[o.module][o.entity].startsWith('@'))];
  for(const op of ordered){const c=allow[op.module][op.entity],id=ids.get(op.operation_id),p=reference(op.payload,ids);if(op.needs_confirmation)warnings.push(op.operation_id+': requiere tu confirmación sobre datos ambiguos.');let touched;
   if(!c.startsWith('@')){const old=s[c].find(r=>r.id===id);A(!(old&&op.action==='create'),'El registro ya existe. Cambia a upsert o update.');let record;if(c==='farmFeedPriceHistory'&&old)A(JSON.stringify({...old,...p})===JSON.stringify(old),'El historial de precios es inmutable: importa un precio nuevo.');if(c==='farmAnimals'&&old&&p.role&&p.role!==old.role)A(!s.farmEvents.some(e=>e.animal_id===old.id),'No cambies la función de un animal con historial mediante importación.');if(c==='gymSessions'){warnings.push(...V2Domain.gym(p).warnings);record={...p,id};}else if(c==='gymRanks'){V2Domain.rank(p);record={...p,id};}else if(c==='journal'&&p.journal_version===4){record=JournalData.normalize(p,old||{},strategy,omitNarrative);warnings.push('Reflexión personal: revisa las intensidades independientes e inferencias. No es diagnóstico.');if(old)warnings.push(strategy==='replace'?'Se reemplazan campos de reflexión tras confirmar; la versión anterior queda en Deshacer.':'Fusión de reflexión: conserva listas y campos no suministrados.');}else record=Records.normalize(c,c==='agendaItems'?{...p,kind:op.entity}:p,old||{},true);if(c==='nutritionDays'&&old)record=RCData.nutritionRevision(old,record,now);record={...record,id,created_at:old?.created_at||now,updated_at:now,source:c==='entityLinks'?record.source:document.source||{kind:'json'},import_batch_id:document.import_id,dedupe_key:op.dedupe_key};if(old)s[c][s[c].indexOf(old)]=record;else s[c].push(record);touched=record;plans.push({module:op.module,entity:op.entity,title:record.title||record.ear_tag||op.operation_id,mode:old?'Actualizar':'Crear'});
   }else{
    if(c==='@profile'){A(Object.keys(p).every(k=>['name','preferred','bio','location','school','languages','interests','projects'].includes(k)),'Campo de perfil no permitido.');s.profile={...s.profile,...p};warnings.push('PERFIL: se modificará información personal. Confirma expresamente el cambio.');}
    else if(c==='@payment'){A(['bills','loans','clients'].includes(p.collection),'El pago requiere collection bills, loans o clients.');A(UUID.test(p.record_id),'Pago sin record_id UUID válido.');const parent=s[p.collection].find(x=>x.id===p.record_id);A(parent,'Registro de pago inexistente.');const existing=parent.payments.find(x=>x.dedupe_key===op.dedupe_key);if(existing){warnings.push('Abono ya registrado: se omite.');}else{Domain.linkedPayment(s,p.collection,p.record_id,{id,amount:Domain.cents(p.amount),date:p.date,link:p.link!==false,dedupe_key:op.dedupe_key,created_at:now});}}
    else if(c==='@feedOpening'){const old=s.farmFeedMovements.find(m=>m.dedupe_key===op.dedupe_key);if(!old){const m=Feed.opening(s,p,id);m.dedupe_key=op.dedupe_key;}else warnings.push('Existencia inicial ya registrada: se omite.');}
    else if(c==='@feedPurchase'){const old=s.farmFeedMovements.find(m=>m.dedupe_key===op.dedupe_key);if(!old){const m=Feed.purchase(s,p,id);m.dedupe_key=op.dedupe_key;}else warnings.push('Compra ya registrada: se omite.');}
    else if(c==='@feedConsumption'){const old=s.farmFeedMovements.find(m=>m.dedupe_key===op.dedupe_key);if(!old){Feed.consume(s,p,id);for(const m of s.farmFeedMovements.filter(m=>m.idempotency_key===id))m.dedupe_key=op.dedupe_key;}else warnings.push('Consumo ya registrado: se omite.');}
    else if(c==='@farmEvent'){const existing=s.farmEvents.find(e=>e.dedupe_key===op.dedupe_key);if(!existing){const ep={...p};if(p.amount!=null)ep.amount=Domain.cents(p.amount);Farm.event(s,p.animal_id,p.type,ep,id);s.farmEvents.find(e=>e.id===id).dedupe_key=op.dedupe_key;}else warnings.push('Evento ya registrado: se omite.');}
    else if(c==='@route'){if(skillId)p.target={...p.target,skill_id:skillId};touched=routeInto(s,p,id,strategy,warnings);touched.updated_at=now;touched.created_at=touched.created_at||now;touched.import_batch_id=document.import_id;}
    else {const nested={ '@deliverable':['clients','client_id','deliverables'],'@installment':['clients','client_id','installments'],'@note':['clients','client_id','notes'],'@activity':['skills','skill_id','tasks'],'@shot':['contentItems','content_id','shots'],'@snapshot':['contentItems','content_id','snapshots']}[c];A(nested,'Adaptador no disponible.');const [col,key,arr]=nested,parent=s[col].find(x=>x.id===p[key]);A(parent,'Referencia inexistente: '+key);parent[arr]=parent[arr]||[];const old=parent[arr].find(x=>x.dedupe_key===op.dedupe_key||x.id===id);A(!(old&&op.action==='create'),'El registro anidado ya existe. Usa update o upsert.');A(op.action!=='update'||old,'No existe el registro anidado a actualizar.');const item={...old,...p,id:old?.id||id,dedupe_key:op.dedupe_key,updated_at:now,created_at:old?.created_at||now};if(c==='@activity'){item.evidence=item.evidence||'';item.done=item.done||false;item.final=item.final||false;}if(c==='@installment')item.amount=Domain.cents(p.amount);if(old)parent[arr][parent[arr].indexOf(old)]=item;else parent[arr].push(item);parent.updated_at=now;}
    plans.push({module:op.module,entity:op.entity,title:p.title||p.target?.skill_title||op.operation_id,mode:'Aplicar'});
   }
  }
  Store.validate(s);const changes=[];for(const c of Store.collections.filter(c=>c!=='importBatches')){for(const record of s[c]){const before=base[c].find(x=>x.id===record.id);if(JSON.stringify(record)!==JSON.stringify(before))changes.push({collection:c,id:record.id,before:before||null,after:structuredClone(record)});}}if(JSON.stringify(s.profile)!==JSON.stringify(base.profile))changes.push({collection:'profile',id:'profile',before:structuredClone(base.profile),after:structuredClone(s.profile)});
  const batch={id:uuid(),import_id:document.import_id,title:document.format,format:document.format,created_at:now,updated_at:now,changes,warnings,status:'applied'};s.importBatches.push(batch);return {document,next:s,baseRevision:base.revision,plans,warnings,changes,batch,already:false};
 }
 function commit(p){A(p&&!p.already,'No hay cambios nuevos para importar.');A(Store.get().revision===p.baseRevision,'Los datos cambiaron. Vuelve a validar antes de confirmar.');if(p.document.format==='dali.journal.entry'){for(const ch of p.changes.filter(c=>c.collection==='journal')){ch.after.confirmed_by_user=true;ch.after.review_required=false;Object.assign(p.next.journal.find(r=>r.id===ch.id),{confirmed_by_user:true,review_required:false});}}
  Store.save(s=>{for(const key of Object.keys(p.next))if(key!=='revision')s[key]=structuredClone(p.next[key]);});return p.batch;}
 function undo(id,force=false){const batch=Store.get().importBatches.find(b=>b.id===id);A(batch&&!batch.undone_at,'Lote no disponible.');Store.save(s=>{for(const ch of batch.changes){const current=ch.collection==='profile'?s.profile:s[ch.collection].find(r=>r.id===ch.id);A(force||JSON.stringify(current)===JSON.stringify(ch.after),'Hay cambios posteriores en '+(ch.after.title||ch.collection)+'. No se modificó nada.');}for(const ch of [...batch.changes].reverse()){if(ch.collection==='profile')s.profile=structuredClone(ch.before);else if(ch.before)s[ch.collection][s[ch.collection].findIndex(r=>r.id===ch.id)]=structuredClone(ch.before);else s[ch.collection]=s[ch.collection].filter(r=>r.id!==ch.id);}const target=s.importBatches.find(b=>b.id===id);target.undone_at=new Date().toISOString();target.status='undone';});}
 function example(kind='general'){const base={format:'dali.crm.import',schema_version:'2.0',import_id:uuid(),created_at:new Date().toISOString(),timezone:DALI_CONFIG.timezone,source:{kind:'manual_example'},atomic:true};if(kind==='gym')return {...base,format:'dali.gym.session',schema_version:'1.0',session:{date:Domain.today(),title:'Mi entrenamiento',duration_seconds:null,reported_volume_kg:null,reported_total_sets:null,completeness:'partial',muscle_distribution:[],exercises:[],imported_ranks:[],uncertainties:['Completa este ejemplo con tus datos reales antes de importar.']}};return {...base,operations:[{operation_id:'mi-objetivo',module:'objectives',entity:'goal',action:'upsert',dedupe_key:'goal:ejemplo-revisar',needs_confirmation:true,payload:{title:'Ejemplo: definir mi siguiente paso',period:'daily',start_date:Domain.today(),category:'Personal',target:1,progress:0}}]};}
 const prompt='Convierte mi dictado en JSON para mi CRM personal DALI. Devuelve exclusivamente format dali.crm.import, schema_version 2.0, import_id UUID, created_at ISO, timezone America/Mexico_City, atomic true y operations. Cada operación requiere operation_id único, module/entity permitidos, action upsert, dedupe_key estable, needs_confirmation y payload. Nunca inventes fechas, personas, recurrencias o montos: usa null y needs_confirmation true. Dinero externo en pesos MXN positivos (amount: 500, type: expense); internamente DALI convierte a centavos. Usa fechas YYYY-MM-DD. Conserva el relato original. Referencias internas: {"$ref":"operation_id"}. Descarga los esquemas y consulta los módulos soportados antes de preparar el JSON. Mi dictado: [PEGAR AQUÍ].';
 return {parse,preview,commit,undo,example,prompt,allow};
})();
