'use strict';
window.JournalData=(()=>{
 const A=V2Domain.assert,T=V2Domain.text,I=V2Domain.integer;
 const emotions={alegria:'Alegría',tristeza:'Tristeza',enojo:'Enojo',calma:'Calma',miedo:'Miedo',ansiedad:'Ansiedad',gratitud:'Gratitud',entusiasmo:'Entusiasmo',frustracion:'Frustración',cansancio:'Cansancio',orgullo:'Orgullo',soledad:'Soledad',esperanza:'Esperanza'};
 const indicators={energy:'Energía',stress:'Estrés',productivity:'Productividad',social_connection:'Conexión social'};
 function measure(x,field){A(x&&typeof x==='object','Valor inválido: '+field);A(['reported','inferred','mixed'].includes(x.basis),'Origen inválido: '+field);A(V2Domain.finite(x.confidence,0,1),'Confianza entre 0 y 1: '+field);A(x.value===null||I(x.value,0,100),'Intensidad entera entre 0 y 100: '+field);}
 function validate(r){A(r&&V2Domain.date(r.date)&&T(r.title)&&r.title.trim()&&T(r.summary),'Bitácora: fecha, título y resumen requeridos.');A(T(r.source_entry_id)&&r.source_entry_id.trim(),'source_entry_id requerido.');if(r.raw_narrative!=null)A(T(r.raw_narrative),'Relato inválido.');for(const k of ['highlights','difficulties','learnings','tags'])A(Array.isArray(r[k])&&r[k].length<=100&&r[k].every(T),'Lista inválida: '+k);A(Array.isArray(r.emotions)&&r.emotions.length<=Object.keys(emotions).length,'Emociones inválidas.');const keys=new Set();for(const x of r.emotions){A(Object.hasOwn(emotions,x.key)&&!keys.has(x.key),'Emoción inválida o repetida.');keys.add(x.key);A(T(x.label)&&T(x.evidence),'Etiqueta/evidencia inválida.');measure({...x,value:x.intensity},x.key);A(I(x.intensity,0,100),'Intensidad entera entre 0 y 100.');}
  A(r.indicators&&typeof r.indicators==='object'&&!Array.isArray(r.indicators),'Indicadores inválidos.');for(const [k,x] of Object.entries(r.indicators)){A(Object.hasOwn(indicators,k),'Indicador desconocido: '+k);if(x!==null)measure(x,k);}
  A(Array.isArray(r.events)&&r.events.length<=100,'Eventos inválidos.');for(const x of r.events)A(RCData.areas.includes(x.area)&&T(x.title)&&['positive','negative','neutral','mixed'].includes(x.sentiment)&&(x.linked_entity_hint==null||T(x.linked_entity_hint)),'Evento de reflexión inválido.');
  A(Array.isArray(r.next_actions)&&r.next_actions.length<=100,'Próximos pasos inválidos.');for(const x of r.next_actions){A(T(x.title)&&x.title.trim()&&['low','medium','high'].includes(x.priority)&&x.needs_confirmation===true,'Acción sugerida inválida.');A(x.duration_minutes==null||I(x.duration_minutes,1,10080),'Duración sugerida inválida.');A(['agenda','objetivos','soma','granja','finanzas','gimnasio','aprendizaje','alvento','contenido','personal'].includes(x.suggested_module),'Módulo sugerido inválido.');A(x.due_hint==null||T(x.due_hint),'Fecha sugerida inválida.');}
  A(typeof r.review_required==='boolean'&&typeof r.confirmed_by_user==='boolean'&&T(r.assistant_note),'Confirmación o nota de reflexión inválida.');return true;
 }
 function operation(doc){A(doc.source&&doc.source.type==='chatgpt_daily_reflection'&&T(doc.source.label),'Origen de reflexión inválido.');validate(doc.entry);return {operation_id:'journal-day',module:'journal',entity:'entry',action:'upsert',dedupe_key:'reflection:'+doc.entry.date+':'+doc.source.type+':'+doc.entry.source_entry_id,payload:{...doc.entry,journal_version:4,text:doc.entry.raw_narrative||'',productivity:doc.entry.indicators.productivity?.value??null,reason:'',confirmed_by_user:false}};}
 function normalize(p,old,strategy,omitNarrative){let r={...old,...p};if(old.id&&strategy==='merge'){for(const k of ['highlights','difficulties','learnings','tags'])r[k]=[...new Set([...(old[k]||[]),...p[k]])];const map=new Map((old.emotions||[]).map(x=>[x.key,x]));for(const x of p.emotions)map.set(x.key,x);r.emotions=[...map.values()];r.indicators={...old.indicators,...p.indicators};}if(omitNarrative){r.raw_narrative=null;r.text='';}r.confirmed_by_user=false;validate(r);return r;}
 function statistics(rows,key,from,to){const confirmed=rows.filter(r=>!r.deleted_at&&r.journal_version===4&&r.confirmed_by_user&&r.date>=from&&r.date<=to),byDay=new Map();for(const r of confirmed){if(!byDay.has(r.date))byDay.set(r.date,[]);const value=Object.hasOwn(indicators,key)?r.indicators[key]?.value??null:r.emotions.find(x=>x.key===key)?.intensity??null;if(Number.isFinite(value))byDay.get(r.date).push(value);}const points=[...byDay].sort(([a],[b])=>a.localeCompare(b)).map(([date,values])=>({date,value:values.length?values.reduce((a,b)=>a+b,0)/values.length:null}));const values=points.filter(x=>x.value!==null);return {points,n:values.length,entries:confirmed.length,days:byDay.size,mean:values.length?values.reduce((n,x)=>n+x.value,0)/values.length:null,trendAllowed:values.length>=3,associationAllowed:values.length>=14};}
 function association(rows,keyA,keyB,from,to){const a=statistics(rows,keyA,from,to),b=new Map(statistics(rows,keyB,from,to).points.map(p=>[p.date,p.value])),pairs=a.points.filter(p=>Number.isFinite(p.value)&&Number.isFinite(b.get(p.date))).map(p=>({date:p.date,a:p.value,b:b.get(p.date)}));return describePairs(pairs);}
 function describePairs(pairs){const n=pairs.length;if(n<14)return {n,pairs,r:null,reason:'Se requieren al menos 14 días con ambos valores confirmados.'};const ma=pairs.reduce((n,p)=>n+p.a,0)/n,mb=pairs.reduce((n,p)=>n+p.b,0)/n,va=pairs.reduce((n,p)=>n+(p.a-ma)**2,0),vb=pairs.reduce((n,p)=>n+(p.b-mb)**2,0);if(!va||!vb)return {n,pairs,r:null,reason:'No hay variación suficiente para calcular una asociación.'};return {n,pairs,r:pairs.reduce((n,p)=>n+(p.a-ma)*(p.b-mb),0)/Math.sqrt(va*vb),reason:'Asociación descriptiva de Pearson, no causalidad ni evaluación clínica.'};}
 const crossMeasures={gym_volume:'Gym · volumen reportado (kg por día)',study_minutes:'Aprendizaje · minutos registrados por día'};
 function crossAssociation(s,key,measure,from,to){
  if(s.preferences.journalPrivacy?.crossModule!==true)return {enabled:false,n:0,pairs:[],r:null,reason:'Comparaciones entre módulos desactivadas.'};
  A(Object.hasOwn(crossMeasures,measure),'Selecciona una medida compatible.');
  const source=measure==='gym_volume'?s.gymSessions:s.studySessions,byDay=new Map();
  for(const row of source){if(row.deleted_at||row.date<from||row.date>to)continue;const value=measure==='gym_volume'?row.reported_volume_kg:row.minutes;if(!Number.isFinite(value))continue;byDay.set(row.date,(byDay.get(row.date)||0)+value);}
  const points=statistics(s.journal,key,from,to).points,pairs=points.filter(p=>Number.isFinite(p.value)&&byDay.has(p.date)).map(p=>({date:p.date,a:p.value,b:byDay.get(p.date)}));
  return {...describePairs(pairs),enabled:true,measure};
 }
 const prompt='Quiero cerrar mi día y convertir esta conversación en una entrada para mi CRM DALI. Primero escúchame y hazme preguntas breves solo si falta algo importante. Cuando yo diga “genera mi JSON”, devuelve únicamente un JSON válido con formato dali.journal.entry y schema_version 1.0; no uses Markdown ni texto fuera del JSON.\n\nResume con fidelidad lo que yo sí dije. Separa hechos, logros, dificultades, aprendizajes y próximos pasos. Puedes proponer intensidades de emociones e indicadores de 0 a 100, pero marca cada valor como reported, inferred o mixed y agrega una confianza de 0 a 1. Las emociones son intensidades independientes: no tienen que sumar 100. Si algo no se sabe, usa null o no lo incluyas. No inventes citas, recuerdos, diagnósticos, traumas, intenciones ni causas.\n\nIncluye alegría, tristeza y enojo cuando exista evidencia, y agrega otras emociones solo si realmente aportan. Cualquier inferencia debe sonar tentativa y quedar marcada para revisión. Esto es una reflexión personal, no terapia, diagnóstico ni evaluación clínica.\n\nLos próximos pasos deben incluir suggested_module, due_hint, duration_minutes, priority y needs_confirmation:true. No des por hecho que se crearán automáticamente. Usa la zona horaria America/Mexico_City y la fecha local correcta. El resultado debe pasar el esquema descargable de DALI.';
 return {emotions,indicators,validate,operation,normalize,statistics,association,crossAssociation,crossMeasures,prompt};
})();
