'use strict';
// Visual projections only: Pig and Feed remain the single source of domain rules.
window.NeuralFarm = (() => {
  const e = Domain.escape;
  const icon = Views.icon;
  const labels = {heat_observed:'Registrar celo',service:'Registrar servicio',pregnancy_check:'Registrar revisión',farrowing:'Registrar parto',weaning:'Registrar destete'};
  const lifeLabels = {active:'Activo',sold:'Vendido',deceased:'Fallecido',transferred:'Trasladado',archived:'Archivado'};
  function silhouette() {
    return `<svg class="rancho-silhouette" viewBox="0 0 480 280" fill="none" aria-hidden="true"><g stroke="currentColor" stroke-width="1"><path d="M20 235H460M60 255H420M45 35V250M435 35V250M20 70H460M20 190H460" opacity=".16"/><ellipse cx="245" cy="169" rx="186" ry="77" opacity=".17"/><ellipse cx="245" cy="169" rx="155" ry="57" opacity=".12"/></g><path d="M110 127C121 80 200 69 273 84C304 89 328 98 345 117L384 125L390 159L356 168L332 195L322 230H300L296 198L180 199L168 230H145L148 191C119 178 107 159 110 127Z" fill="currentColor" fill-opacity=".12" stroke="currentColor" stroke-width="2"/><path d="M326 106L328 67L351 103M110 128C74 133 74 110 89 108C104 106 103 126 84 124M182 198L190 176M296 198L291 177M382 132L378 151" stroke="currentColor" stroke-width="3" stroke-linecap="round"/><circle cx="348" cy="129" r="3.5" fill="currentColor"/><g fill="currentColor"><circle cx="156" cy="119" r="4"/><circle cx="252" cy="97" r="4"/><circle cx="294" cy="164" r="4"/></g><path d="M156 119L117 52H63M252 97L285 37H391M294 164L369 216H427" stroke="currentColor" stroke-opacity=".45"/></svg>`;
  }
  function hero(s, tab) {
    const active = s.farmAnimals.filter(a=>!a.deleted_at && Pig.derive(s,a).life==='active');
    const alerts = Pig.alerts(s);
    const confirmed = active.filter(a=>['gestation_confirmed','prefarrowing'].includes(Pig.derive(s,a).labelState)).length;
    const next=alerts.slice().sort((a,b)=>a.date.localeCompare(b.date))[0];
    const capacity=Pig.capacity(s,Domain.today(),V2Domain.addDays(Domain.today(),60));
    const forecast=active.length?Feed.forecast(s,Feed.period(Domain.today(),'7'),0):null;
    const coverage=forecast&&!forecast.incomplete&&forecast.products.length?Math.min(...forecast.products.map(p=>p.coverageDays??Infinity)):null;
    const stageCounts=['open','heat','served_pending_confirmation','gestation_confirmed','prefarrowing','lactation'].map(key=>({key,count:active.filter(a=>Pig.derive(s,a).labelState===key).length}));
    return `<section class="rancho-hero ${tab!=='summary'?'rancho-hero-compact':''}" aria-labelledby="rancho-title"><div class="rancho-hero-copy"><span class="rancho-eyebrow">RANCHO FAMILIAR / CIUDAD GUZMÁN</span><h1 id="rancho-title">Cuidar hoy.<br><em>Crecer con certeza.</em></h1><p>Tu rancho, conectado a sus registros. Cada animal tiene una historia; cada decisión, un punto de partida.</p><div class="rancho-hero-actions">${PigViews.btn(icon('plus')+(s.farmAnimals.some(a=>!a.deleted_at)?'Agregar cerdo':'Agregar primer cerdo'),'animal','','primary')}<a class="button" href="#subir">${icon('upload')}Importar registros</a></div>${active.length?`<div class="rancho-data"><span><strong>${active.length}</strong> animales activos</span><span><strong>${confirmed}</strong> gestaciones confirmadas</span><span><strong>${alerts.length}</strong> pendientes y ventanas</span></div>`:'<p class="rancho-start">Empieza con un arete real. Sin animales ni operaciones de muestra.</p>'}</div><div class="rancho-visual">${silhouette()}${active.length?`<div class="rancho-stage-counts">${stageCounts.map(x=>`<span class="${x.count?'has-records':''}"><strong>${x.count}</strong> ${e(Pig.states[x.key])}</span>`).join('')}</div>`:''}<span class="rancho-visual-label">REGISTROS LOCALES · SIN TELEMETRÍA</span><p>Una monta no confirma gestación.<br>La evidencia registrada, sí.</p></div>${active.length?`<div class="rancho-brief"><article><span>SIGUIENTE PENDIENTE</span>${next?`<a href="#${e(next.route)}"><strong>${e(next.title)}</strong>${e(next.detail)} · ${Views.date(next.date)}</a>`:'<strong>Sin ventana pendiente registrada</strong>'}</article><article><span>ALIMENTO · COBERTURA INICIAL</span><strong>${coverage!==null&&Number.isFinite(coverage)?coverage.toFixed(1)+' días estimados':'Faltan datos confirmados'}</strong><p>${coverage!==null?'Mínima por producto, con la demanda inicial. Recalcular con movimientos reales.':'Revisa animales, productos, precios y raciones en Comida.'}</p></article><article><span>MATERNIDAD · PRÓXIMOS 60 DÍAS</span><strong>${capacity.max} / ${capacity.capacity} espacios proyectados</strong><p>${capacity.max>capacity.capacity?'Hay traslapes previstos: revisa Agenda. No se reprograma ningún evento.':'Sin exceso de capacidad proyectado.'}</p></article></div>`:''}</section>`;
  }
  function actionButton(a, type, primary=false) {
    return PigViews.btn(labels[type]||Pig.events[type], 'event', `data-id="${e(a.id)}" data-type="${type}"`, primary?'primary':'');
  }
  function card(a, alerts) {
    const s=Store.get(), r=Pig.derive(s,a), allowed=Pig.allowed(r,a), primary=allowed.find(t=>Object.hasOwn(labels,t)), alert=alerts.find(x=>x.animal_id===a.id);
    const elapsed=r.since?Math.max(0,V2Domain.days(r.since,Domain.today())):null;
    const secondary=allowed.filter(t=>t!==primary);
    const lastObservation=Pig.timeline(s,a.id).slice().reverse().find(ev=>ev.notes?.trim());
    const health=s.farmHealthRecords.filter(h=>!h.deleted_at&&h.animal_id===a.id).sort((a,b)=>b.date.localeCompare(a.date))[0];
    const stageDays=r.state==='lactation'?Pig.settings(s).lactation_days: r.due?Pig.settings(s).gestation_days:null;
    const stageStart=r.state==='lactation'?r.farrowingDate:r.serviceDate;
    const stageProgress=stageDays&&stageStart?Math.max(0,Math.min(100,V2Domain.days(stageStart,Domain.today())/stageDays*100)):null;
    return `<article class="panel rancho-animal"><a href="#granja/${e(a.id)}" class="rancho-animal-image" aria-label="Abrir ficha de arete ${e(a.ear_tag)}">${a.media_id?V2Views.image(a.media_id,'Arete '+a.ear_tag):silhouette()}<span class="ear-tag">${e(a.ear_tag)}</span></a><div class="rancho-animal-body"><div class="card-top"><span class="tag ${r.state==='served_pending_confirmation'?'amber':r.life==='active'?'green':''}">${e(Pig.states[r.labelState])}</span><span class="muted">${e(lifeLabels[r.life]||'Estado no clasificado')}</span></div><h2><a href="#granja/${e(a.id)}">${e(a.name||'Arete '+a.ear_tag)}</a></h2><p>${e(Pig.roles[a.role])} · ${e(a.location||'Corral sin indicar')}</p><div class="rancho-animal-status">${icon('clock-3')}<span>${elapsed!==null?'Día '+elapsed+' desde el cambio registrado':'Sin fecha de cambio registrada'}</span></div>${r.due&&['served_pending_confirmation','gestation_confirmed'].includes(r.state)?`<p class="rancho-estimate">${r.state==='served_pending_confirmation'?'Ventana provisional, sin confirmación':'Parto estimado'} · ${Views.date(r.due)}</p>`:''}${stageProgress!==null?`<div class="rancho-stage-progress" aria-label="Avance de ventana estimada"><p class="muted">Ventana estimada · no confirma estado</p>${Views.progress(stageProgress)}</div>`:''}<p class="rancho-alert">${icon(alert?'calendar-clock':'clipboard-check')}${alert?e(alert.detail)+' · '+Views.date(alert.date):'Sin ventana pendiente registrada'}</p>${health?`<p class="rancho-alert">${icon('heart-pulse')}Observación de salud · ${Views.date(health.date)}: ${e(health.observation||'Consultar ficha')}</p>`:''}${lastObservation||a.notes?`<p class="rancho-notes">${lastObservation?'Última observación: ':''}${e(lastObservation?.notes||a.notes)}</p>`:''}<div class="rancho-card-actions">${primary?actionButton(a,primary,true):`<a href="#granja/${e(a.id)}" class="button primary">Ver historial</a>`}<details class="rancho-more"><summary class="button">Más acciones ${icon('chevron-down')}</summary><div>${secondary.map(t=>actionButton(a,t)).join('')}<a class="button" href="#granja/${e(a.id)}">Ficha e historial</a>${PigViews.btn('Editar datos','animal',`data-id="${e(a.id)}"`)}</div></details></div></div></article>`;
  }
  function cards(list) {
    const alerts=Pig.alerts(Store.get());
    return `<div class="cards-grid pig-cards">${list.map(a=>card(a,alerts)).join('')}</div>`;
  }
  function feedChart(f) {
    if(!f.products.length) return `<section class="panel feed-empty"><div class="feed-empty-art">${icon('wheat')}${icon('package')}${icon('scale')}</div><h2>Antes de calcular, conoce tu alimento.</h2><p>Registra tus animales, revisa un producto y confirma su ración. Aquí verás la demanda teórica; nunca se registrará como consumo real automáticamente.</p><div class="toolbar">${PigViews.btn('Revisar productos','feed-tab','data-tab="products"','primary')}${PigViews.btn('Configurar raciones','rule')}</div></section>`;
    const max=Math.max(1,...f.daily.map(d=>d.totalG)), points=f.daily.map((d,n)=>`${42+n/Math.max(1,f.daily.length-1)*680},${168-d.totalG/max*126}`).join(' ');
    return `<section class="panel chart-section" id="feed-demand-chart"><div class="card-top"><h2>El ritmo de tu alimento</h2><span class="tag ${f.incomplete?'amber':'green'}">${f.incomplete?'Proyección parcial':'Raciones confirmadas'}</span></div><p>Demanda teórica diaria · kg. No es alimento ofrecido ni consumido.</p><svg viewBox="0 0 760 218" role="img" aria-label="Demanda teórica diaria. Consulta los valores exactos en la tabla inferior." class="feed-line-chart"><g stroke="currentColor" opacity=".15"><path d="M42 42H722M42 105H722M42 168H722"/></g><polygon points="42,168 ${points} 722,168" fill="currentColor" opacity=".10"/><polyline points="${points}" fill="none" stroke="currentColor" stroke-width="3" stroke-linejoin="round"/><g fill="currentColor" font-size="12"><text x="42" y="26">${e((max/1000).toLocaleString('es-MX'))} kg</text><text x="42" y="196">${e(Views.date(f.range.start))}</text><text x="722" y="196" text-anchor="end">${e(Views.date(f.range.end))}</text></g></svg><details class="feed-values"><summary>Ver datos diarios · ${f.daily.length} días</summary><div class="feed-values-scroll"><table class="chart-table"><caption>Demanda calculada a partir de raciones confirmadas${f.incomplete?' — faltan datos, total parcial':''}</caption><thead><tr><th scope="col">Fecha</th><th scope="col">Gramos</th><th scope="col">Kilogramos</th></tr></thead><tbody>${f.daily.map(d=>`<tr><th scope="row">${Views.date(d.date)}</th><td>${d.totalG}</td><td>${d.totalG/1000}</td></tr>`).join('')}</tbody></table></div></details></section>`;
  }
  return {silhouette,hero,cards,feedChart};
})();
