'use strict';
(()=>{
 const e=Domain.escape,i=Views.icon,b=Views.button,legacy=V2Views.home;
 V2Views.home=function(){const s=Store.get(),core=DaliCore.select(s),rows=NeuralSignals.pending(s),today=Domain.today(),hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:'America/Mexico_City',hour:'2-digit',hour12:false}).format(new Date())),greeting=hour<12?'Buenos días':hour<19?'Buenas tardes':'Buenas noches',quote=['Haz espacio para lo que importa.','Pequeñas acciones. Una dirección clara.','Tu siguiente paso empieza aquí.','Construye con intención. Avanza a tu ritmo.'][Number(today.slice(-2))%4],t=document.createElement('template');t.innerHTML=legacy();const widgets=t.content.querySelector('.dashboard-grid')?.innerHTML||'';
 return `<section class="neural-hero" id="neural-home-hero"><div class="neural-hero-copy"><div class="neural-kicker"><span class="status-dot"></span> IVY · MODO LOCAL</div><h1>${e(Personalization.greeting(s.profile))}</h1><p>Tu mundo, en perspectiva.</p><div class="hero-caption">Datos locales listos.<br>¿Qué necesitas, jefe?</div><p class="core-talk-hint">${window.evieDesktop?'Pulsa el núcleo para escuchar · Ctrl + Espacio':'Pulsa el núcleo para abrir Ivy'}</p></div>${DaliCore.markup()}<div class="hero-bottom"><span><span class="ivy-live-dot"></span> <span data-ivy-state-label>En espera</span></span><span>CONTROL LOCAL / SIN SERVICIOS EXTERNOS</span></div></section>
 <div class="briefing-title"><div><span class="eyebrow">TU PANORAMA</span><h2>Lo importante, primero.</h2></div><span class="muted">${Views.date(today,{weekday:'long',day:'numeric',month:'long'})}</span></div><div class="briefing-grid"><section class="panel briefing-attention"><header class="panel-header"><h2>${i('radar')}Requiere tu atención</h2><span class="tag">${rows.filter(r=>r.date<=today).length} para hoy o vencidos</span></header>${rows.slice(0,5).map(r=>`<a class="briefing-row" href="#${e(r.route)}"><span class="briefing-dot ${r.date<today?'overdue':''}"></span><div><small>${e(r.kind)} · ${Views.date(r.date)}</small><h3>${e(r.title)}</h3><p>${e(r.detail)}</p></div>${i('arrow-up-right')}</a>`).join('')||`<div class="briefing-clear">${i('circle-check')}<h3>Espacio para enfocarte.</h3><p>No hay pendientes registrados que reclamen tu atención.</p>${b('Crear objetivo','add-goal')}</div>`}</section><section class="panel next-actions"><span class="eyebrow">AVANZA CON INTENCIÓN</span><h2>Tus próximas<br>tres acciones.</h2>${rows.slice(0,3).map((r,n)=>`<a href="#${e(r.route)}"><span class="action-number">0${n+1}</span><div><strong>${e(r.title)}</strong><small>${e(r.kind)} · ${Views.date(r.date)}</small></div>${i('arrow-up-right')}</a>`).join('')||`<p>Empieza por una prioridad real. No necesitas hacerlo todo hoy.</p>${b(i('target')+'Elegir una prioridad','add-goal','primary')}`}</section></div>
 <div class="briefing-title"><div><span class="eyebrow">EN PERSPECTIVA</span><h2>El pulso de tu espacio.</h2></div>${b('Editar widgets','customize','ghost')}</div><div class="dashboard-grid neural-pulse">${widgets}</div><section class="panel activity-panel"><header class="panel-header"><h2>${i('git-branch')}Actividad conectada</h2><span class="muted">Derivada de tus registros</span></header>${NeuralSignals.activity(s).map(r=>`<a class="record-row" href="#${e(r.route)}"><span class="stat-icon">${i('arrow-up-right')}</span><div class="record-main"><h3>${e(r.title)}</h3><p>${e(r.kind)} · Última actualización ${Views.date(r.date)}</p></div></a>`).join('')||'<p class="empty-compact">Tu actividad aparecerá aquí al guardar registros.</p>'}</section>`;
 };
})();
