'use strict';
// Compatibility facade: every existing farm caller uses the event-derived model.
Object.assign(Farm,{settings:Pig.settings,event:Pig.record,revert:Pig.revert,alerts:Pig.alerts,metrics:(s,id)=>Pig.metrics(s,'1900-01-01',Domain.today(),id)});
V2Views.farm=PigViews.render;
window.PigApp={
 async action(el){const action=el.dataset.action.slice(4),id=el.dataset.id,A=V2Domain.assert;
  if(['animal','opening','purchase','consume','product','rule','lot','task','health','litter','settings'].includes(action)){PigForms[action](id);return;}
  if(action==='health-status'){const closed=el.dataset.closed==='true';App.confirmAction(closed?'Cerrar seguimiento':'Reabrir seguimiento',closed?'Se conserva la observación y su historial. Cerrar retira las alertas operativas; no confirma recuperación ni sustituye una revisión veterinaria.':'El seguimiento vuelve a estar abierto y puede volver a aparecer en las alertas según la prioridad que registraste.',()=>Store.save(s=>NeuralCare.setFollowup(s,id,closed)));return;}
  if(action==='event'){PigForms.event(id,el.dataset.type);return;}
  if(action==='purchase-revert'){App.confirmAction('Anular compra y gasto','Solo se permite si su lote no tiene otros movimientos. La evidencia original se conserva.',()=>Store.save(s=>Feed.revertPurchase(s,id)));return;}
  if(action==='correct'){App.confirmAction('Anular último evento','Se añade una corrección auditada. La evidencia se conserva y se revierten los efectos vinculados.',()=>Store.save(s=>Pig.revert(s,id)));return;}
  if(action==='archive'){App.confirmAction('Archivar cerdo','Se conserva el historial. Dejará de contar como animal activo.',()=>Store.save(s=>{const a=s.farmAnimals.find(a=>a.id===id);a.archived_at=new Date().toISOString();a.status='archived';}));return;}
  if(action==='feed-tab'){UI.feedTab=el.dataset.tab;App.render();return;}
  if(action==='calculate'){const start=document.getElementById('feed-start').value,kind=document.getElementById('feed-period').value,end=document.getElementById('feed-end').value,buffer=Number(document.getElementById('feed-buffer').value);Feed.period(start,kind,end);A(Number.isFinite(buffer)&&buffer>=0&&buffer<=100,'Colchón entre 0 y 100%.');Object.assign(UI,{feedStart:start,feedPeriod:kind,feedEnd:end,feedBuffer:buffer});App.render();return;}
  if(action==='copy-shopping'){const f=UI.feedForecast;A(f,'Calcula primero la previsión.');const text=`Compra estimada ${f.range.start} – ${f.range.end}${f.incomplete?' · CONFIGURACIÓN INCOMPLETA':''}\n`+f.products.map(p=>`${p.product.name}: ${p.bags} costales (${p.purchaseG/1000} kg), ${p.price?Domain.money(p.costCents):'precio pendiente'}. Sobrante: ${p.endingG/1000} kg.`).join('\n');try{await navigator.clipboard.writeText(text);App.toast('Lista copiada.');}catch{App.openDialog('Lista de compra',Forms.area('shopping','Copia esta lista',text));}return;}
  if(action==='metrics-range'){const start=document.getElementById('pig-metric-start').value,end=document.getElementById('pig-metric-end').value;A(V2Domain.date(start)&&V2Domain.date(end)&&start<=end,'Rango de rendimiento inválido.');UI.pigMetricStart=start;UI.pigMetricEnd=end;App.render();return;}
  if(action==='catalog-backup'){const raw=localStorage.getItem(DALI_CONFIG.storageKey+'-pre-catalog-v4');A(raw,'No existe respaldo previo: este navegador puede haber comenzado con el catálogo actual.');App.download('dali-pre-catalogo-v4.json',raw,'application/json');return;}
  if(action==='migration-report'){App.download('dali-granja-migracion.json',JSON.stringify(Store.get().farmMigrationReport||[],null,2),'application/json');return;}
  if(action==='task-done'||action==='alert-goal'){const alert=Pig.alerts(Store.get()).find(x=>x.id===el.dataset.key);A(alert,'Pendiente ya completado o inexistente.');if(action==='task-done'){if(alert.task_id)Store.put('farmTasks',{status:'done',completed_at:new Date().toISOString()},alert.task_id);else Store.put('farmTasks',{title:alert.title,date:alert.date,notes:alert.detail,status:'done',origin_key:alert.id});}else{if(Store.list('goals').some(g=>g.farm_origin_key===alert.id)){App.toast('Ya existe un objetivo para este pendiente.');return;}Store.put('goals',{...Records.defaults('goals'),title:alert.title+' · '+alert.detail,date:alert.date,category:'Rancho',farm_origin_key:alert.id,periodKey:alert.date});}App.render();return;}
  throw new Error('Acción de Granja no reconocida.');
 },
 afterRender(){const rail=document.querySelector('.rancho-rail'),selected=rail?.querySelector('[aria-current="page"]');if(rail&&selected){const r=rail.getBoundingClientRect(),t=selected.getBoundingClientRect();rail.scrollLeft+=t.left-r.left-(rail.clientWidth-t.width)/2;}const bind=(id,fn)=>{const el=document.getElementById(id);if(el)el.onchange=()=>{try{fn(el);}catch(error){App.toast(error.message,'error');}};};bind('pig-state-filter',el=>{UI.pigFilter=el.value;App.render();});bind('feed-period',el=>{document.getElementById('feed-end').disabled=el.value!=='custom';});bind('pig-calendar-month',el=>{if(!/^\d{4}-\d{2}$/.test(el.value))return;UI.pigMonth=el.value;App.render();});bind('pig-metric-period',el=>{UI.pigMetricDays=Number(el.value);UI.pigMetricStart=null;UI.pigMetricEnd=null;App.render();});}
};
