'use strict';
Pig.record=function(s,id,eventType,p,eventId=crypto.randomUUID()){
 const A=V2Domain.assert,existing=s.farmEvents.find(e=>e.id===eventId||e.idempotency_key===eventId);if(existing)return existing;
 const a=s.farmAnimals.find(a=>a.id===id&&!a.deleted_at);A(a,'Cerdo no encontrado.');A(V2Domain.date(p.date)&&p.date<=Domain.today(),'La fecha registrada debe ser válida y no futura.');const t=Pig.type({type:eventType});A(Object.hasOwn(Pig.events,t),'Evento no permitido.');const last=Pig.timeline(s,id).at(-1);A(!last||p.date>=last.date,'No se admiten eventos anteriores al último. Usa una corrección auditada.');if(p.occurred_at)A(!Number.isNaN(Date.parse(p.occurred_at))&&Domain.today(new Date(p.occurred_at))===p.date&&(!last?.occurred_at||p.occurred_at>=last.occurred_at),'Hora inválida o anterior al último evento.');const r=Pig.derive(s,a,p.date);A(Pig.allowed(r,a).includes(t),'Acción no permitida desde '+Pig.states[r.state]+'.');const now=new Date().toISOString(),ev={...p,id:eventId,animal_id:id,type:t,idempotency_key:eventId,created_at:now,updated_at:now,recorded_at:now,sequence:s.farmEvents.length+1,schema_version:3,source:p.source||'manual',before:structuredClone(a)};
 if(t==='service'){if(p.service_number!=null)A(V2Domain.integer(p.service_number,1,10),'Número de servicio inválido.');A(p.method==='artificial'||p.sire_id||p.sire_name,'Selecciona semental conocido o inseminación.');if(p.sire_id){const sire=s.farmAnimals.find(x=>x.id===p.sire_id);A(sire&&sire.role==='boar'&&Pig.derive(s,sire,p.date).life==='active','Semental no activo.');}if(p.sire_name)A(s.farmAnimals.some(x=>x.role==='boar'&&x.name===p.sire_name)||s.farmEvents.some(e=>e.sire_name===p.sire_name),'Ese semental no consta en los datos. Regístralo primero.');ev.cycle_id=r.state==='heat'?r.last?.id:r.serviceId||eventId;}
 if(t==='pregnancy_check'){A(['positive','negative','inconclusive'].includes(p.result),'Selecciona un resultado.');A(r.serviceDate,'No existe servicio previo.');ev.service_id=r.serviceId;}
 if(t==='farrowing'){const total=p.born_total??null,alive=p.born_alive??null,still=p.stillborn??null,mum=p.mummified??null;for(const n of [total,alive,still,mum])A(n===null||V2Domain.integer(n,0,100),'Conteo inválido.');A(total===null||[alive,still,mum].reduce((n,x)=>n+(x||0),0)<=total,'Los conteos superan nacidos totales.');ev.litter_id=crypto.randomUUID();s.farmLitters.push({id:ev.litter_id,event_id:ev.id,dam_id:id,sire_name:r.sire_name,birth_date:p.date,born_total:total,born_alive:alive,stillborn:still,mummified:mum,weaned:null,adoptions:0,transfers:0,losses:0,notes:p.notes||'',created_at:now,updated_at:now});}
 if(t==='weaning'){const l=s.farmLitters.filter(l=>l.dam_id===id&&!l.deleted_at&&l.weaned_at==null).at(-1);A(l,'No hay camada abierta.');const available=l.born_alive==null?null:l.born_alive+(l.adoptions||0)-(l.transfers||0)-(l.losses||0);A(p.weaned==null||V2Domain.integer(p.weaned,0,100),'Destetados inválidos.');A(p.weaned==null||available===null||p.weaned<=available,'Destetados superiores a disponibles.');ev.litter_id=l.id;ev.litter_before=structuredClone(l);l.weaned=p.weaned??null;l.weaned_at=p.date;l.updated_at=now;}
 if(t==='health_observation'){ev.health_record_id=crypto.randomUUID();s.farmHealthRecords.push({id:ev.health_record_id,animal_id:id,event_id:ev.id,date:p.date,observation:p.observation||p.notes||'Observación registrada',professional:p.professional||'',treatment:p.treatment||'',next_date:p.next_date||null,notes:p.notes||'',created_at:now,updated_at:now});}
 if(t==='state_correction'){A(typeof p.notes==='string'&&p.notes.trim().length>=5,'Explica la corrección.');if(p.reproductive_state)A(['open','heat','postweaning','not_applicable'].includes(p.reproductive_state),'La gestación solo se confirma con revisión positiva.');if(p.void_event_id){const target=s.farmEvents.find(x=>x.id===p.void_event_id&&x.animal_id===id);A(target&&target.type!=='state_correction'&&Pig.timeline(s,id).at(-1)?.id===target.id,'Solo puede anularse el último evento vigente.');if(target.health_record_id)s.farmHealthRecords.find(h=>h.id===target.health_record_id).deleted_at=now;if(target.litter_before)s.farmLitters[s.farmLitters.findIndex(x=>x.id===target.litter_id)]=structuredClone(target.litter_before);else if(target.litter_id)s.farmLitters.find(x=>x.id===target.litter_id).deleted_at=now;for(const tx of s.transactions.filter(x=>x.origin===target.id))tx.deleted_at=now;}}
 s.farmEvents.push(ev);const updated=Pig.derive(s,a);a.reproductive_state=updated.state;a.current_state_since=updated.since;a.status=updated.life;a.updated_at=now;ev.after=structuredClone(a);
 if(t==='sale'&&p.amount){A(V2Domain.integer(p.amount,1),'Importe de venta inválido.');s.transactions.push({id:crypto.randomUUID(),date:p.date,title:'Venta de cerdo · '+a.ear_tag,type:'income',amount:p.amount,category:'Ventas',business_unit:'granja',source:'farm-sale',origin:ev.id,related_entity_id:a.id,related_entity_type:'animal',created_at:now,updated_at:now});}return ev;
};
Pig.revert=function(s,id){const ev=s.farmEvents.find(e=>e.id===id);V2Domain.assert(ev,'Evento no encontrado.');return Pig.record(s,ev.animal_id,'state_correction',{date:Domain.today(),void_event_id:id,notes:'Anulación explícita del último evento. Evidencia original conservada.'});};
