'use strict';
window.PigForms={animal:id=>NeuralCare.animal(id)};
PigForms.event=function(id,type){const F=Forms,day=Domain.today(),a=Store.list('farmAnimals').find(a=>a.id===id),eventId=crypto.randomUUID();let fields=F.field('date','Fecha registrada',day,'date',`required max="${day}"`)+F.field('time','Hora local México','12:00','time','required');
 if(type==='heat_observed')fields+=F.area('signals','Señales observadas (opcional)','')+F.select('boar_exposure','Exposición a semental',['unknown','yes','no'],'unknown')+F.select('confidence','Confianza',['low','medium','high'],'medium')+F.field('observer','Observador','');
 if(type==='service'){const sires=Store.list('farmAnimals').filter(a=>a.role==='boar'&&Pig.derive(Store.get(),a).life==='active');fields+=F.select('method','Método',[['natural','Monta natural'],['artificial','Inseminación artificial']],'natural')+F.select('sire_id','Semental (natural)',[['','Selecciona'],...sires.map(a=>[a.id,a.name||a.ear_tag])],'')+F.field('service_number','Servicio dentro del celo',1,'number','min="1" max="10" step="1"')+F.field('semen_lot','Lote / proveedor semen','')+F.field('responsible','Responsable','');}
 if(type==='pregnancy_check')fields+=F.select('result','Resultado',[['inconclusive','Inconcluso'],['positive','Positivo'],['negative','Negativo']],'inconclusive')+F.field('method','Método','')+F.field('professional','Profesional','')+F.field('next_date','Seguimiento','','date');
 if(type==='farrowing')for(const [key,label]of [['born_total','Nacidos totales'],['born_alive','Vivos'],['stillborn','Muertos'],['mummified','Momificados']])fields+=F.field(key,label,'','number','min="0" max="100" step="1"');
 if(type==='weaning')fields+=F.field('weaned','Destetados (opcional)','','number','min="0" max="100" step="1"')+F.field('destination','Destino','');
 if(type==='sale')fields+=F.field('amount','Ingreso MXN (0 = sin movimiento)',0,'text','inputmode="decimal" required',true);
 if(type==='state_correction')fields+=F.select('reproductive_state','Estado observado',[['open','Vacía'],['heat','Celo'],['postweaning','Posdestete'],['not_applicable','No aplica']],'open',true);
 if(type==='transfer')fields+=F.field('destination','Destino','','text','required');fields+=F.area('notes','Notas / motivo','','required');
 F.form(Pig.events[type],a.ear_tag+' · Una monta no confirma gestación. Ventanas estimadas, no diagnóstico.',fields,data=>{for(const k of ['born_total','born_alive','stillborn','mummified','weaned'])if(k in data)data[k]=data[k]===''?null:Number(data[k]);if('amount'in data)data.amount=Domain.cents(data.amount);if(data.service_number)data.service_number=Number(data.service_number);data.occurred_at=new Date(data.date+'T'+data.time+':00-06:00').toISOString();if(!data.sire_id)delete data.sire_id;Store.save(s=>Pig.record(s,id,type,data,eventId));},'Confirmar evento');};
