'use strict';
window.Records=(()=>{
 const labels={books:'Libro',farmAnimals:'Animal',farmHealthRecords:'Registro de salud',alventoDrops:'Drop',alventoProducts:'Producto / SKU',alventoMilestones:'Hito',contentItems:'Contenido',visionItems:'Meta visual'};
 // [key, label, type, options]. Money is displayed in MXN and stored in cents.
 const fields={
 books:[['title','Título','text!'],['author','Autor','text'],['status','Estado','select',['wishlist','owned','reading','paused','finished','abandoned']],['format','Formato','select',['físico','ebook','audiolibro']],['total_pages','Páginas totales','number'],['current_page','Página actual','number'],['rating','Calificación 1–5 (opcional)','nullableNumber'],['estimated_price','Precio estimado MXN','money'],['purchase_priority','Prioridad de compra','select',['Normal','Alta','Baja']],['isbn','ISBN','text'],['store_or_link','Enlace de compra','url'],['short_review','Opinión breve','area'],['lessons','Aprendizajes','area'],['brief_quotes','Cita breve (máx. 500 caracteres)','area'],['tags','Etiquetas','tags']],
 farmAnimals:[['ear_tag','Arete único','text!'],['name','Nombre opcional','text'],['role','Rol','select',Object.keys(Pig.roles)],['sex','Sexo','select',['female','male']],['birth_date','Nacimiento','date'],['acquisition_date','Adquisición','date'],['acquisition_cost','Costo de adquisición de referencia MXN','money'],['notes','Notas','area']],
 farmHealthRecords:[['animal_id','Animal','relation','farmAnimals'],['date','Fecha','date!'],['observation','Síntomas observados','area!'],['professional','Profesional responsable','text'],['treatment','Indicación del profesional (sin consejo automático)','area'],['medicine','Medicina indicada','text'],['next_date','Siguiente revisión','date'],['notes','Notas','area']],
 alventoDrops:[['title','Nombre del drop','text!'],['sequence','Número de drop','number'],['status','Estado','select',['idea','planning','production','content','scheduled','live','closed','archived']],['launch_at','Fecha de lanzamiento','date'],['goal_units','Meta de unidades','number'],['goal_revenue','Meta de ingresos MXN','money'],['budget','Presupuesto MXN','money'],['notes','Notas','area']],
 alventoProducts:[['drop_id','Drop','relation','alventoDrops'],['title','Producto','text!'],['sku','SKU','text!'],['category','Categoría','text'],['color','Color','text'],['size','Talla','text'],['unit_price','Precio unitario MXN','money'],['unit_cost','Costo unitario MXN','money'],['initial_stock','Stock inicial','number'],['notes','Notas','area']],
 alventoMilestones:[['drop_id','Drop','relation','alventoDrops'],['title','Hito','text!'],['date','Fecha límite','date!'],['owner','Responsable','text'],['status','Estado','select',['pending','done']],['notes','Notas','area']],
 contentItems:[['title','Título','text!'],['platform','Plataforma','select',['youtube','youtube_shorts','instagram_reels','tiktok','multiple',['other','Otra (Other)']]],['format','Formato','select',['long','short']],['series','Serie','text'],['episode_number','Episodio','number'],['status','Estado','select',['idea','research','script','ready','recording','editing','scheduled','published','analyzed']],['priority','Prioridad','select',['Normal','Alta','Baja']],['target_publish_at','Publicación objetivo','date'],['record_at','Fecha de grabación','date'],['objective','Objetivo','area'],['audience','Audiencia','text'],['hook','Hook: primeros segundos','area'],['premise','Idea central','area'],['script','Guion / estructura','area'],['broll','B-roll','area'],['location','Ubicación','text'],['people','Personas','text'],['props','Props','text'],['cta','Llamada a la acción','text'],['caption','Caption / título de YouTube','area'],['published_url','URL publicada','url'],['notes','Notas','area']],
 visionItems:[['title','Aspiración','text!'],['category','Categoría','select',['patrimonio','viaje','estilo de vida','negocio','experiencia','aprendizaje','otra']],['why','¿Por qué es importante para ti?','area'],['target_date','Fecha objetivo','date'],['target_cost','Costo objetivo MXN','money'],['saved_amount','Ahorro registrado MXN','money'],['status','Estado','select',['someday','active','achieved','archived']],['related_goal_id','Objetivo vinculado (opcional)','relation?','goals']]
 };
 const moneyFields=['amount','acquisition_cost','estimated_price','goal_revenue','budget','unit_price','unit_cost','target_cost','saved_amount'];
 function defaults(c){const date=Domain.today();const table={
 transactions:{title:'',type:'expense',amount:0,date,category:'Personal',business_unit:'personal',note:''},bills:{title:'',amount:0,date,category:'Personal',payments:[]},loans:{title:'',amount:0,date,category:'Personal',payments:[]},goals:{title:'',date,horizon:'diario',category:'Personal',target:1,progress:0,history:[],periodKey:date,recurring:false,archived:false,unit:'',description:''},clients:{title:'',date,stage:'Prospecto',amount:0,contact:'',phone:'',email:'',project:'',payments:[],deliverables:[],notes:[],installments:[]},journal:{title:'',date,text:'',summary:'',productivity:50,reason:'',tags:[]},metrics:{date,weight:0,note:''},skills:{title:'',date,category:'Aprendizaje',status:'Activa',minutes:120,reason:'',tasks:[]},studySessions:{date,minutes:25,note:''},
 books:{title:'',author:'',status:'wishlist',format:'físico',total_pages:0,current_page:0,rating:null,estimated_price:0,purchase_priority:'Normal',short_review:'',lessons:'',brief_quotes:'',tags:[],readingLog:[]},
 farmAnimals:{species:'pig',role:'sow',ear_tag:'',name:'',sex:'female',birth_date:null,acquisition_date:null,acquisition_cost:0,status:'active',reproductive_state:'open',current_state_since:date,notes:''},farmHealthRecords:{animal_id:'',date,observation:'',professional:'',treatment:'',next_date:null,notes:''},
 alventoDrops:{title:'',sequence:1,status:'idea',launch_at:null,goal_units:0,goal_revenue:0,budget:0,notes:''},alventoProducts:{title:'',drop_id:'',sku:'',size:'',color:'',unit_price:0,unit_cost:0,initial_stock:0,status:'active'},alventoMilestones:{title:'',drop_id:'',date,owner:'',status:'pending',notes:''},
 contentItems:{title:'',platform:'youtube',format:'long',series:'De cero hasta viajar por el mundo',episode_number:1,status:'idea',target_publish_at:null,hook:'',premise:'',script:'',shots:[],snapshots:[],checklist:[],cadence_days:null},visionItems:{title:'',category:'viaje',why:'',target_date:null,target_cost:0,saved_amount:0,status:'someday',position:0,related_goal_id:null}};return structuredClone(table[c]||{});}
 function normalize(c,p,old={},importing=false){if(RCData.collections.includes(c))return {...RCData.defaults(c),...old,...p};const r={...defaults(c),...old,...p};if(importing){for(const k of moneyFields)if(Object.hasOwn(p,k)&&p[k]!=null){V2Domain.assert(typeof p[k]==='number'&&p[k]>=0,'Importe positivo numérico requerido: '+k);r[k]=Domain.cents(p[k]);}if(['transactions','bills','loans','goals','clients','journal','metrics','studySessions'].includes(c)&&!old.id)r.date=p.date??p.start_date??null;
  if(c==='goals'){const horizons={daily:'diario',weekly:'semanal',monthly:'mensual',yearly:'anual'};r.horizon=horizons[p.period]||p.horizon||r.horizon;r.recurring=!!p.recurrence;r.periodKey=Domain.periodKey(r.horizon,r.date||Domain.today());r.timezone=DALI_CONFIG.timezone;if(r.recurrence){Recurrence.validate(r.recurrence);r.start_date=p.start_date||old.start_date||r.date;}}
  if(['transactions','bills','loans'].includes(c))V2Domain.assert(r.amount>0,'El importe debe ser mayor a cero.');
  if(c==='journal'&&!old.id)r.productivity=p.productivity??null;
  if(c==='studySessions')r.skillId=p.skill_id||p.skillId||old.skillId;
  if(p.currency)V2Domain.assert(p.currency==='MXN','Solo se admite MXN; no se convierten monedas automáticamente.');
  if(c==='farmAnimals'){for(const k of ['reproductive_baseline','reproductive_state','status','current_state_since','migration_original'])if(Object.hasOwn(p,k))V2Domain.assert(old.id&&JSON.stringify(p[k])===JSON.stringify(old[k]),'El estado reproductivo se modifica mediante eventos, no mediante el alta/importación del animal.');if(!old.id)r.reproductive_state=Pig.breeding(r)?'open':'not_applicable';}
 }
 if(c==='books'){V2Domain.assert(r.brief_quotes?.length<=500||!r.brief_quotes,'Las citas deben ser breves: hasta 500 caracteres.');if(old.id&&r.current_page!==old.current_page)r.readingLog=[...(old.readingLog||[]),{date:Domain.today(),from:old.current_page,to:r.current_page}];}
 for(const k of ['store_or_link','published_url'])if(r[k])V2Domain.assert(V2Domain.safeUrl(r[k]),'Usa un enlace http o https válido.');return r;}
 return {labels,fields,defaults,normalize,moneyFields};
})();
