'use strict';
window.Recurrence=(()=>{
 const validDate=d=>typeof d==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&!Number.isNaN(Date.parse(d+'T12:00:00Z'));
 const days=(a,b)=>Math.round((Date.parse(b+'T12:00:00Z')-Date.parse(a+'T12:00:00Z'))/86400000);
 function validate(r){if(!r)return;const fail=m=>{throw new Error('Recurrencia: '+m);};if(!['daily','weekly','monthly','yearly'].includes(r.frequency))fail('frecuencia inválida.');if(!Number.isInteger(r.interval)||r.interval<1||r.interval>365)fail('intervalo entre 1 y 365.');if(r.timezone!=='America/Mexico_City')fail('usa America/Mexico_City.');if(r.time_local!=null&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(r.time_local))fail('hora inválida.');if(!Array.isArray(r.days_of_week||[])||(r.days_of_week||[]).some(n=>!Number.isInteger(n)||n<0||n>6))fail('days_of_week usa 0–6.');if(r.day_of_month!=null&&(!Number.isInteger(r.day_of_month)||r.day_of_month<1||r.day_of_month>31))fail('día del mes inválido.');if(r.end_date!=null&&!validDate(r.end_date))fail('fecha final inválida.');}
 function latest(g,today){const r=g.recurrence;validate(r);const start=g.start_date||g.date;if(!validDate(start))return null;const until=r.end_date&&r.end_date<today?r.end_date:today;if(until<start)return null;const interval=r.interval,from=new Date(start+'T12:00:00Z'),end=new Date(until+'T12:00:00Z');
  if(r.frequency==='daily')return new Date(+from+Math.floor(days(start,until)/interval)*interval*86400000).toISOString().slice(0,10);
  if(r.frequency==='weekly'){const weekdays=r.days_of_week?.length?r.days_of_week:[from.getUTCDay()];for(let offset=0;offset<=interval*7+7;offset++){const dt=new Date(+end-offset*86400000),key=dt.toISOString().slice(0,10);if(key<start)return null;const weeks=Math.round(days(Domain.periodKey('semanal',start),Domain.periodKey('semanal',key))/7);if(weeks%interval===0&&weekdays.includes(dt.getUTCDay()))return key;}return null;}
  const step=r.frequency==='yearly'?interval*12:interval,total=(end.getUTCFullYear()-from.getUTCFullYear())*12+end.getUTCMonth()-from.getUTCMonth();let offset=Math.floor(total/step)*step;for(let n=0;n<2;n++,offset-=step){if(offset<0)return null;const dt=new Date(Date.UTC(from.getUTCFullYear(),from.getUTCMonth()+offset,1,12)),lastDay=new Date(Date.UTC(dt.getUTCFullYear(),dt.getUTCMonth()+1,0)).getUTCDate();dt.setUTCDate(Math.min(r.day_of_month||from.getUTCDate(),lastDay));const key=dt.toISOString().slice(0,10);if(key<=until&&key>=start)return key;}return null;
 }
 const legacy=Domain.renewGoals;
 function renew(goals,date=Domain.today()){let changed=false;for(const g of goals.filter(g=>g.recurring&&!g.deleted_at&&!g.archived)){if(!g.recurrence){changed=legacy([g],date)||changed;continue;}const key=latest(g,date);if(!key)continue;if(!g.start_date){g.start_date=g.date;changed=true;}if(!g.last_occurrence&&g.periodKey===Domain.periodKey(g.horizon,key)){g.last_occurrence=key;g.date=key;changed=true;continue;}const previous=g.last_occurrence||g.start_date;if(key<=previous){if(!g.last_occurrence){g.last_occurrence=previous;changed=true;}continue;}g.history=g.history||[];if(!g.history.some(h=>h.occurrence===previous))g.history.push({periodKey:g.periodKey,occurrence:previous,progress:g.progress,target:g.target});g.progress=0;g.last_occurrence=key;g.periodKey=Domain.periodKey(g.horizon,key);g.date=key;g.updated_at=new Date().toISOString();changed=true;}return changed;}
 Domain.renewGoals=renew;return {validate,latest,renew};
})();
