'use strict';
const {test}=require('node:test'),a=require('node:assert/strict');
const R=require('../electron/ai/router.cjs'),{createConversation}=require('../electron/ai/ollama.cjs'),{createRegistry}=require('../electron/tools/registry.cjs');
const sale='Agrega en Finanzas mil pesos de una venta de Intensity',reminder='Agenda mañana cobrarle a Intensity mil pesos';
test('explicit module wins; scheduling never becomes a payment',()=>{
 for(const [input,domain] of [[sale,'finance'],[reminder,'agenda'],['Agrega en Finanzas un gasto de agenda impresa','finance'],['Registra una venta en Granja','granja'],['Agrega algo','ambiguous'],['Agrega en Finanzas y en Agenda','ambiguous'],['¿Cuánto gasté en el módulo de Finanzas?','finance']])a.equal(R.classify(input),domain,input);
 a.throws(()=>R.assertScope('finance','crm.create_task',{}));a.throws(()=>R.assertScope('agenda','finance.create_transaction',{}));a.throws(()=>R.assertScope('finance','crm.verify_record',{collection:'agendaItems'}));
});
test('money parser stores integer cents, not pesos or binary decimal fractions',()=>{a.equal(R.cents('mil'),100000);a.equal(R.cents('10,29'),1029);a.equal(R.cents('1.01'),101);for(const x of ['0','-2','1.001','NaN','999999999999999999'])a.equal(R.cents(x),null);});
test('narrow deterministic commands preserve exact domain and meaning',()=>{const p=R.directFinance(sale);a.equal(p.name,'finance.create_transaction');a.equal(p.args.amount,100000);a.equal(p.args.entity_name,'Intensity');a.equal(p.args.category,'Ventas');a.equal(R.directFinance(sale+' y luego otra venta'),null);const t=R.directAgenda(reminder,'2026-12-31');a.equal(t.name,'crm.create_task');a.equal(t.args.date,'2027-01-01');a.equal(R.directFinance(reminder),null);});
function conversation({chat,result,models=['local:qwen'],execute}={}){const calls=[];const c=createConversation({provider:{models:async()=>models,cancel(){},chat:chat||(async()=>{throw Error('No model call expected');})},settings:()=>({model:'local:qwen'}),status(){},context:async()=>({currentScreen:'finanzas'}),registry:{catalog:()=>[],execute:async(name,args)=>{calls.push({name,args});return execute?execute(name,args):result||{ok:true,data:{verified:true,record:{id:'verified-id',title:args.title,amount:args.amount,date:'2026-09-19'}}};}}});return {c,calls};}
test('required Finance sentence executes one financial write and announces only verified result',async()=>{const {c,calls}=conversation();const r=await c.ask(sale);a.equal(calls.length,1);a.equal(calls[0].name,'finance.create_transaction');a.equal(calls[0].args.amount,100000);a.match(r.text,/verificado en Finanzas/);a.match(r.text,/1,000\.00/);});
test('required reminder creates only Agenda task, no Finance write',async()=>{const {c,calls}=conversation();await c.ask(reminder);a.equal(calls.length,1);a.equal(calls[0].name,'crm.create_task');a.match(calls[0].args.title,/Intensity mil pesos/);});
test('cross-domain model batch is rejected before ANY tool runs',async()=>{const {c,calls}=conversation({chat:async()=>({role:'assistant',content:'',tool_calls:[{function:{name:'finance.get_summary',arguments:{}}},{function:{name:'crm.create_task',arguments:{title:'wrong'}}}]})});await a.rejects(c.ask('Registra un ingreso de 25 pesos'),/fuera del dominio/);a.equal(calls.length,0);});
test('failure, duplicate client and unverified output cannot become model success',async()=>{for(const result of [{ok:false,error:'Hay varios clientes Intensity. ¿Cuál es el ID correcto?'},{ok:true,data:{record:{id:'x'}}}]){const {c}=conversation({result});const r=await c.ask(sale);a.doesNotMatch(r.text,/Registrado y verificado/);a.match(r.text,/varios clientes|no tiene una lectura/);}});
test('duplicate-client clarification preserves the financial proposal but still executes through registry',async()=>{let n=0;const {c,calls}=conversation({execute:async(name,args)=>++n===1?{ok:false,error:'Elige cliente',clarification:{kind:'client',choices:[{id:'client-a'},{id:'client-b'}]}}:{ok:true,data:{verified:true,record:{id:'sale',title:args.title,amount:args.amount,date:'2026-09-19'}}}});a.equal((await c.ask(sale)).ok,false);const r=await c.ask('client-b');a.match(r.text,/verificado en Finanzas/);a.equal(calls.length,2);a.equal(calls[1].name,'finance.create_transaction');a.equal(calls[1].args.client_id,'client-b');a.equal(calls[1].args.amount,100000);});
test('never switches automatically to an available fallback model',async()=>{const {c,calls}=conversation({models:['qwen3:4b']});await a.rejects(c.ask('Hola'),/no se cambió ni descargó/);a.equal(calls.length,0);});
test('ambiguous mutation clarifies without requesting a model or executing tools',async()=>{const {c,calls}=conversation({models:[]});a.match((await c.ask('Agrega uno')).text,/qué módulo/);a.equal(calls.length,0);});
test('cancel while model is pending prevents tools',async()=>{let resolve;const {c,calls}=conversation({chat:()=>new Promise(r=>resolve=r)});const waiting=c.ask('Registra un gasto de cinco pesos');await new Promise(r=>setImmediate(r));c.cancel();resolve({role:'assistant',content:'',tool_calls:[{function:{name:'finance.get_summary',arguments:{}}}]});await a.rejects(waiting,/cancelada/);a.equal(calls.length,0);});
test('preparation rejection never opens confirmation or commits',async()=>{let confirms=0,commits=0;const r=createRegistry({crm:async action=>{if(action==='commit')commits++;return {ok:false,error:'Hay varios clientes'};},windows:{},confirm:async()=>{confirms++;return true;},audit(){},settings:()=>({})});a.equal((await r.execute('finance.create_transaction',{title:'x',type:'income',amount:100})).ok,false);a.equal(confirms,0);a.equal(commits,0);});
