'use strict';
const {test}=require('node:test'),a=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const settings=require('../electron/main/settings.cjs');
function fixture(fn){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'evie-settings-test-'));try{fn(dir,path.join(dir,'desktop-settings.json'));}finally{fs.rmSync(dir,{recursive:true,force:true});}}
test('versioned migration preserves original bytes, apps, grants, AI paths and unknown preferences',()=>fixture((dir,file)=>{const old={opacity:.85,setupDone:false,apps:{spotify:{path:'C:\\Spotify\\Spotify.exe'}},grants:{'open:spotify':true},whisperModel:'D:\\ai\\custom.bin',custom:{kept:true}};const raw=JSON.stringify(old,null,3);fs.writeFileSync(file,raw);const s=settings(dir).get();a.equal(s.opacity,100);a.equal(s.settingsVersion,2);a.equal(s.setupDone,true);a.deepEqual(s.apps,old.apps);a.deepEqual(s.grants,old.grants);a.equal(s.whisperModel,old.whisperModel);a.deepEqual(s.custom,old.custom);const backups=fs.readdirSync(dir).filter(n=>n.startsWith('desktop-settings.pre-2.1.0.'));a.equal(backups.length,1);a.equal(fs.readFileSync(path.join(dir,backups[0]),'utf8'),raw);settings(dir);a.equal(fs.readdirSync(dir).filter(n=>n.startsWith('desktop-settings.pre-')).length,1);}));
test('malformed and newer settings are not silently reset or overwritten',()=>fixture((dir,file)=>{for(const raw of ['{broken','[]','null','{"settingsVersion":99}']){fs.writeFileSync(file,raw);a.throws(()=>settings(dir));a.equal(fs.readFileSync(file,'utf8'),raw);}}));
test('microphone consent survives host restart and explicit revocation',()=>fixture(dir=>{let s=settings(dir);a.equal(s.get().microphoneConsent,false);s.microphone(true);s=settings(dir);a.equal(s.get().microphoneConsent,true);a.equal(s.get().microphoneAsked,true);s.microphone(false);s=settings(dir);a.equal(s.get().microphoneConsent,false);a.equal(s.get().microphoneAsked,true);a.throws(()=>s.patch({microphoneConsent:true}));}));
test('replacing an authorized identity revokes its old action grants',()=>fixture(dir=>{const s=settings(dir);s.mapping('apps','player',{path:'C:\\one.exe'});s.grant('windows.open_app:player',true);s.grant('windows.window_action:player:minimize',true);s.grant('windows.open_app:other',true);s.mapping('apps','player',{path:'C:\\two.exe'});a.equal(s.get().grants['windows.open_app:player'],undefined);a.equal(s.get().grants['windows.window_action:player:minimize'],undefined);a.equal(s.get().grants['windows.open_app:other'],true);}));
test('opacity full range and explicit model preference persist',()=>fixture(dir=>{const s=settings(dir);for(const opacity of [0,50,100]){s.patch({opacity});a.equal(settings(dir).get().opacity,opacity);}for(const opacity of [-1,101,NaN])a.throws(()=>s.patch({opacity}));s.patch({model:'custom-qwen:8b',modelMode:'selected'});a.equal(settings(dir).get().model,'custom-qwen:8b');}));
