'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const owner='11111111-1111-4111-8111-111111111111';
function fixture(){
 const s={structuredClone,AbortController,setTimeout,clearTimeout};s.window=s;vm.createContext(s);vm.runInContext(fs.readFileSync(path.join(__dirname,'../public/sync-engine.js'),'utf8'),s);
 let state={version:4,profile:{name:''},preferences:{},transactions:[]},listener=()=>{};const cached=new Map(),records=new Map();
 const storage={getItem:k=>cached.get(k)||null,setItem:(k,v)=>cached.set(k,v)};
 const store={collections:['transactions'],get:()=>state,validate:()=>{},save:fn=>{const next=structuredClone(state);fn(next);store.validate(next);state=next;listener();},subscribe:fn=>{listener=fn;return()=>listener=()=>{};}};
 const server={hook:null,pushes:0,pulls:0,async api(route,args){if(server.hook){const result=await server.hook(route,args);if(result)return result;}if(route==='data/pull'){server.pulls++;return {owner,rows:structuredClone([...records.values()]),next:''};}server.pushes++;const rows=args.body.changes.map(c=>{const previous=records.get(c.collection+'/'+c.record_id);if((previous?.revision||0)!==c.expected_revision)throw Object.assign(Error('CAS conflict'),{status:409});return {...c,owner_id:owner,revision:c.expected_revision+1};});for(const r of rows)records.set(r.collection+'/'+r.record_id,structuredClone(r));return {owner,rows};}};
 const engine=s.EvieSync.create({owner,storage,key:'test',store,api:(...args)=>server.api(...args)});
 const edit=(id,amount)=>store.save(v=>{let r=v.transactions.find(r=>r.id===id);if(r)r.amount=amount;else v.transactions.push({id,amount});});
 const remote=(id,amount)=>{const key='transactions/'+id,previous=records.get(key);records.set(key,{owner_id:owner,collection:'transactions',record_id:id,payload:{id,amount},revision:(previous?.revision||0)+1});};
 return {engine,store,storage,records,server,edit,remote,get:()=>state};
}
async function seeded(t){const f=fixture();t.after(()=>f.engine.stop());f.edit('Exact-ID',100);assert.equal((await f.engine.sync()).ok,true);return f;}
function resolve(f,key,choice){const c=f.engine.conflicts().find(c=>c.key===key);return f.engine.resolve(key,choice,c.reviewVersion);}
test('CAS conflict after pull fetches reviewable versions without retrying a write',async t=>{const f=await seeded(t);f.edit('Exact-ID',200);let injected=false;f.server.hook=route=>{if(route==='data/push'&&!injected){injected=true;f.remote('Exact-ID',300);}return null;};const before=f.server.pushes,result=await f.engine.sync();assert.equal(result.conflict,true);assert.equal(result.status,409);assert.equal(f.server.pushes,before+1);const c=f.engine.conflicts()[0];assert.equal(c.local.payload.amount,200);assert.equal(c.remote.payload.amount,300);assert.equal(f.get().transactions[0].amount,200);});
test('CAS race with identical remote data resolves through readback without a write loop',async t=>{const f=await seeded(t);f.edit('Exact-ID',200);let injected=false;f.server.hook=route=>{if(route==='data/push'&&!injected){injected=true;f.remote('Exact-ID',200);}return null;};const result=await f.engine.sync();assert.equal(result.conflict,false);assert.equal(f.engine.pending(),0);assert.equal((await f.engine.sync()).ok,true);});
test('remote conflict resolution applies nonconflicting linked companions atomically',async t=>{const f=await seeded(t);f.edit('Companion-ID',100);await f.engine.sync();f.edit('Exact-ID',200);f.remote('Exact-ID',300);f.remote('Companion-ID',300);const before=structuredClone(f.get());f.store.validate=value=>{assert.equal(value.transactions[0].amount,value.transactions[1].amount,'linked amounts must match');};assert.equal((await f.engine.sync()).conflict,true);assert.deepEqual(f.get(),before);resolve(f,'transactions/Exact-ID','remote');assert.equal(f.get().transactions[0].amount,300);assert.equal(f.get().transactions[1].amount,300);assert.ok(f.storage.getItem('test-rollback'));assert.equal(f.engine.pending(),0);});
test('editing while conflict is displayed prevents stale confirmation from discarding that edit',async t=>{const f=await seeded(t);f.edit('Exact-ID',200);f.remote('Exact-ID',300);await f.engine.sync();const c=f.engine.conflicts()[0];f.edit('Exact-ID',400);assert.throws(()=>f.engine.resolve(c.key,'remote',c.reviewVersion),/locales cambiaron/);assert.equal(f.get().transactions[0].amount,400);assert.equal(f.storage.getItem('test-rollback'),null);});
test('old conflict dialog cannot confirm a newer server version',async t=>{const f=await seeded(t);f.edit('Exact-ID',200);f.remote('Exact-ID',300);await f.engine.sync();const c=f.engine.conflicts()[0];f.remote('Exact-ID',500);await f.engine.sync();assert.throws(()=>f.engine.resolve(c.key,'remote',c.reviewVersion),/vista previa cambió/);assert.equal(f.get().transactions[0].amount,200);resolve(f,c.key,'remote');assert.equal(f.get().transactions[0].amount,500);});
test('conflict choices wait until all linked conflicts are selected',async t=>{const f=await seeded(t);f.edit('Second-ID',100);await f.engine.sync();f.edit('Exact-ID',200);f.edit('Second-ID',200);f.remote('Exact-ID',300);f.remote('Second-ID',300);await f.engine.sync();resolve(f,'transactions/Exact-ID','remote');assert.equal(f.get().transactions[0].amount,200);resolve(f,'transactions/Second-ID','remote');assert.deepEqual(Array.from(f.get().transactions,r=>r.amount),[300,300]);});
test('rollback quota failure never applies the selected remote versions',async t=>{const f=await seeded(t);f.edit('Exact-ID',200);f.remote('Exact-ID',300);await f.engine.sync();const set=f.storage.setItem;f.storage.setItem=(key,value)=>{if(key.endsWith('-rollback'))throw Error('quota');set(key,value);};assert.throws(()=>resolve(f,'transactions/Exact-ID','remote'),/quota/);assert.equal(f.get().transactions[0].amount,200);assert.equal(f.engine.conflicts().length,1);});
test('remote revision rollback or changed payload at same revision is rejected',async t=>{const f=await seeded(t),key='transactions/Exact-ID',row=structuredClone(f.records.get(key));f.records.set(key,{...row,payload:{id:'Exact-ID',amount:900}});assert.equal((await f.engine.sync()).ok,false);assert.equal(f.get().transactions[0].amount,100);f.records.set(key,row);f.edit('Exact-ID',200);await f.engine.sync();f.records.set(key,row);const result=await f.engine.sync();assert.equal(result.ok,false);assert.match(result.error,/revisión remota/);assert.equal(f.get().transactions[0].amount,200);});
test('cannot resolve during an active fetch or after cancelling the account engine',async t=>{const f=await seeded(t);f.edit('Exact-ID',200);f.remote('Exact-ID',300);await f.engine.sync();const c=f.engine.conflicts()[0];let release;f.server.hook=route=>route==='data/pull'?new Promise(r=>release=()=>r({owner,rows:structuredClone([...f.records.values()]),next:''})):null;const inFlight=f.engine.sync();while(!release)await new Promise(r=>setTimeout(r,1));assert.throws(()=>f.engine.resolve(c.key,'remote',c.reviewVersion),/termine/);f.engine.stop();release();assert.equal((await inFlight).cancelled,true);assert.throws(()=>f.engine.resolve(c.key,'remote',c.reviewVersion),/cerrada/);assert.equal(f.get().transactions[0].amount,200);});
