'use strict';
window.runCatalogTests=async({w,test,assert,equal,rejects})=>{
 const S=w.Store,U=w.FarmUpgrade;
 const previous=()=>{const s=structuredClone(S.get());s.farmFeedProducts=s.farmFeedProducts.filter(p=>!p.id.startsWith('fe400000'));s.farmFeedPriceHistory=s.farmFeedPriceHistory.filter(p=>!p.id.startsWith('fe410000'));delete s.farm_catalog_version;delete s.catalog_updates;return s;};
 await test('Catálogo: 16 referencias exactas e inactivas, anteriores intactas',()=>{const before=previous(),next=U.upgradeReferences(before);S.validate(next);equal(U.referencesV4.length,16);equal(next.farmFeedProducts.length,before.farmFeedProducts.length+16);for(const [name,,grams,cents] of U.referencesV4){const p=next.farmFeedProducts.find(p=>p.name===name),price=next.farmFeedPriceHistory.find(x=>x.product_id===p.id&&x.effective_date==='2026-09-16');equal(p.bag_weight_g,grams);equal(p.active,false);equal(price.price_cents,cents);equal(price.status,'reference_needs_confirmation');equal(price.source,'photo_price_board');}for(const p of before.farmFeedProducts)equal(next.farmFeedProducts.find(x=>x.id===p.id),p);for(const p of before.farmFeedPriceHistory)equal(next.farmFeedPriceHistory.find(x=>x.id===p.id),p);equal(next.farmFeedPriceHistory.find(p=>p.id==='fe310000-0000-4000-8000-000000000007').price_cents,34900);for(const c of S.collections.filter(c=>!['farmFeedProducts','farmFeedPriceHistory'].includes(c)))equal(next[c],before[c]);equal(U.upgradeReferences(next),next);});
 await test('Catálogo: dedupe normalizado conserva producto y precio confirmado',()=>{const s=previous(),p={id:crypto.randomUUID(),name:'PIGGO  F1 “K”',bag_weight_g:25000,active:false};s.farmFeedProducts.push(p);const price={id:crypto.randomUUID(),product_id:p.id,price_cents:70000,currency:'MXN',effective_date:'2026-09-16',status:'confirmed',source:'user-confirmation'};s.farmFeedPriceHistory.push(price);const next=U.upgradeReferences(s);S.validate(next);equal(next.farmFeedProducts.length,s.farmFeedProducts.length+15);equal(next.farmFeedProducts.find(x=>x.id===p.id),p);equal(next.farmFeedPriceHistory.find(x=>x.id===price.id),price);assert(next.farmFeedPriceHistory.some(x=>x.product_id===p.id&&x.status==='reference_needs_confirmation'&&x.price_cents===66200));});
 await test('Catálogo: Monensina y Racto exigen revisión expresa',()=>{const s=U.upgradeReferences(previous());for(const p of s.farmFeedProducts.filter(p=>/racto|monensina/i.test(p.name))){assert(p.requires_compliance_review);equal(p.active,false);const copy=structuredClone(s),item=copy.farmFeedProducts.find(x=>x.id===p.id);item.active=true;rejects(()=>S.validate(copy));const before=JSON.stringify(copy.farmFeedMovements);rejects(()=>w.Feed.purchase(copy,{product_id:p.id,date:w.Domain.today(),bags:1,price_cents:24000,link:true}));equal(JSON.stringify(copy.farmFeedMovements),before);}});
 await test('Catálogo: actualización real respalda y no se repite',()=>{const key=w.DALI_CONFIG.storageKey,raw=localStorage.getItem(key),backupKey=key+'-pre-catalog-v4',backup=localStorage.getItem(backupKey);try{const old=previous();localStorage.setItem(key,JSON.stringify(old));localStorage.removeItem(backupKey);S.init();equal(JSON.parse(localStorage.getItem(backupKey)),old);equal(S.get().farm_catalog_version,4);equal(S.get().revision,old.revision+1);const first=localStorage.getItem(key);S.init();equal(localStorage.getItem(key),first);}finally{localStorage.setItem(key,raw);if(backup===null)localStorage.removeItem(backupKey);else localStorage.setItem(backupKey,backup);S.init();}});
 await test('Catálogo: fallo al respaldar conserva el original',()=>{const key=w.DALI_CONFIG.storageKey,raw=localStorage.getItem(key),backupKey=key+'-pre-catalog-v4',backup=localStorage.getItem(backupKey),set=w.Storage.prototype.setItem;try{const old=JSON.stringify(previous());localStorage.setItem(key,old);localStorage.removeItem(backupKey);w.Storage.prototype.setItem=function(k,v){if(k===backupKey)throw new Error('Fallo de cuota QA');return set.call(this,k,v);};rejects(()=>S.init());equal(localStorage.getItem(key),old);}finally{w.Storage.prototype.setItem=set;localStorage.setItem(key,raw);if(backup===null)localStorage.removeItem(backupKey);else localStorage.setItem(backupKey,backup);S.init();}});
};
