'use strict';
window.runModuleTests=async({w,test,assert,equal,rejects})=>{
 const S=w.Store,d=w.document,M=w.NeuralModules;
 const render=(section,id=null)=>{w.UI.section=section;w.UI.id=id;w.App.render();};
 await test('Módulos: selector diario no inventa fechas y separa suma de promedio',()=>{const today=w.Domain.today(),rows=[{date:today,value:20},{date:today,value:40},{date:today,value:null}];equal(M.daily(rows,r=>r.value,30),[{date:today,value:60}]);equal(M.daily(rows,r=>r.value,30,'mean'),[{date:today,value:30}]);});
 await test('Módulos: renders repetidos no duplican gráficas ni modifican datos',()=>{const before=JSON.stringify(S.get());render('finanzas');equal(d.querySelectorAll('.module-chart').length,1);w.App.render();equal(d.querySelectorAll('.module-chart').length,1);render('objetivos');equal(d.querySelectorAll('.completion-ring').length,1);render('soma');assert(d.querySelector('.module-pipeline'));equal(JSON.stringify(S.get()),before);});
 await test('Gimnasio: seis destinos, cuerpo y progreso mantienen controles existentes',async()=>{render('gimnasio');for(const tab of ['summary','history','body','metrics','nutrition','pantry']){await w.RCApp.action({dataset:{action:'rc-gym-section',tab}});equal(d.querySelectorAll('nav[aria-label="Secciones de Gimnasio"] button').length,6);if(tab==='body')equal(d.querySelectorAll('.body-silhouette').length,2);if(tab==='metrics')assert(d.querySelector('[data-action="add-metric"]'));}await w.RCApp.action({dataset:{action:'rc-gym-section',tab:'training'}});});
 await test('Libros: estantería, cuadrícula y lista sin alterar biblioteca',()=>{const before=JSON.stringify(S.get().books);render('libros');for(const mode of ['shelf','grid','list']){M.action({dataset:{action:'rc-module-mode',mode}});equal(d.querySelector('.cards-grid').dataset.libraryMode,mode);}equal(JSON.stringify(S.get().books),before);});
 await test('Contenido: filtro de producción no cambia estados ni escenas',()=>{const before=JSON.stringify(S.get().contentItems);render('contenido');M.action({dataset:{action:'rc-module-content-stage',stage:'edit'}});assert(d.querySelector('.module-pipeline'));equal(JSON.stringify(S.get().contentItems),before);w.UI.contentStage='all';});
 await test('Vínculos anidados: actividades diferentes, idempotencia y cero progreso implícito',()=>{const s=structuredClone(S.get()),parent={...w.Records.defaults('skills'),id:'nested-skill',title:'QA habilidad',tasks:[{id:'nested-a',title:'A',points:1,done:false,level:0,evidence:''},{id:'nested-b',title:'B',points:1,done:false,level:0,evidence:''}]};s.skills.push(parent);const a={collection:'skills',id:parent.id,child:{collection:'tasks',id:'nested-a'}},b={collection:'skills',id:parent.id,child:{collection:'tasks',id:'nested-b'}};const link=w.EntityLinks.create(s,a,b);equal(w.EntityLinks.create(s,b,a).id,link.id);w.RCData.validate(s);equal(parent.tasks[0].done,false);parent.tasks.pop();rejects(()=>w.RCData.validate(s));link.deleted_at=new Date().toISOString();w.RCData.validate(s);equal(s.skills.length,S.get().skills.length+1);});
 await test('Vínculos anidados: búsqueda explícita encuentra actividad y no crea nada sola',()=>{const skill=S.put('skills',{...w.Records.defaults('skills'),title:'QA conexiones',tasks:[{id:'qa-nested-task',title:'Actividad única vinculable',points:1,done:false,level:0,evidence:''}]}),goal=S.list('goals')[0],before=S.list('entityLinks').length;w.EntityLinks.open('goals',goal.id);assert(!d.getElementById('link-results').querySelector('button'));const search=d.getElementById('link-search');search.value='Actividad única vinculable';search.dispatchEvent(new w.Event('input'));assert(d.querySelector('[data-result]'));equal(S.list('entityLinks').length,before);d.querySelector('[data-result]').click();equal(S.list('entityLinks').length,before+1);const ep=S.list('entityLinks').at(-1).target;equal(ep.id,skill.id);equal(ep.child.id,'qa-nested-task');w.App.closeDialog();});
 await test('Vínculos anidados: $ref adelantado, reimportación idempotente, campos desconocidos y undo',()=>{const op=(operation_id,module,entity,payload)=>({operation_id,module,entity,payload,dedupe_key:'qa-nested-import:'+operation_id,action:'upsert'}),doc={format:'dali.crm.import',schema_version:'2.0',import_id:crypto.randomUUID(),timezone:'America/Mexico_City',operations:[op('link','system','entity_link',{source:{collection:'skills',id:{$ref:'skill'},child:{collection:'tasks',id:{$ref:'task'}}},target:{collection:'goals',id:{$ref:'goal'}}}),op('task','learning','activity',{skill_id:{$ref:'skill'},title:'Actividad importada',level:0,points:1,evidence:'',custom_nested:{keep:true}}),op('skill','learning','skill',{title:'Ruta vinculada por JSON'}),op('goal','objectives','goal',{title:'Meta vinculada por JSON',date:w.Domain.today()})]},before=JSON.stringify(S.get().skills),p=w.Importer.preview(doc);equal(JSON.stringify(S.get().skills),before);w.Importer.commit(p);const skill=S.list('skills').find(r=>r.dedupe_key==='qa-nested-import:skill'),task=skill.tasks[0],link=S.list('entityLinks').find(r=>r.dedupe_key==='qa-nested-import:link');equal(link.source.child.id,task.id);doc.import_id=crypto.randomUUID();delete doc.operations[1].payload.custom_nested;const again=w.Importer.preview(doc);equal(again.next.entityLinks.find(r=>r.id===link.id).source.child.id,task.id);equal(again.next.skills.find(r=>r.id===skill.id).tasks[0].custom_nested,{keep:true});w.Importer.commit(again);w.Importer.undo(again.batch.id);w.Importer.undo(p.batch.id);equal(JSON.stringify(S.get().skills),before);});
 await test('ALVENTO: un solo hero y acciones de negocio conservadas tras renders',()=>{const before=JSON.stringify(S.get().alventoDrops);render('alvento');equal(d.querySelectorAll('.alvento-editorial').length,1);equal(d.querySelectorAll('.alvento-banner').length,0);assert(d.querySelector('[data-collection="alventoDrops"]'));w.App.render();equal(d.querySelectorAll('.alvento-editorial').length,1);equal(JSON.stringify(S.get().alventoDrops),before);});
 await test('Agenda: vínculo desde captura se guarda atómicamente y buscar no escribe',()=>{const goal=S.list('goals')[0],before=JSON.stringify(S.get());w.Agenda.edit();const form=d.getElementById('record-form'),search=form.querySelector('[data-link-query]');assert(!form.querySelector('[data-link-options] button'));search.value=goal.id;search.dispatchEvent(new w.Event('input'));form.querySelector('[data-link-options] button').click();equal(JSON.stringify(S.get()),before);form.querySelector('[name="title"]').value='QA captura vinculada';const revision=S.get().revision;form.requestSubmit();assert(!d.getElementById('app-dialog').open,d.getElementById('form-error')?.textContent);equal(S.get().revision,revision+1);const row=S.list('agendaItems').find(r=>r.title==='QA captura vinculada');assert(S.list('entityLinks').some(l=>l.source.id===row.id&&l.target.id===goal.id));equal(row.duration_minutes,null);});
 await test('Agenda: sugerencias deterministas no cambian fechas ni completan pendientes',()=>{const rows=['low','high','medium','high'].map((priority,n)=>({...w.RCData.defaults('agendaItems'),id:'suggest-'+n,title:'QA',priority})),before=JSON.stringify(rows),p=w.Agenda.suggestions(rows);equal(p.length,3);equal(p[0].priority,'high');equal(JSON.stringify(rows),before);});
 await test('Vínculos: URI child y foco contextual exacto sin progreso implícito',()=>{const skill=S.list('skills').find(r=>r.tasks.some(t=>t.id==='qa-nested-task')),child={collection:'tasks',id:'qa-nested-task'};equal(w.EntityLinks.endpointLink({collection:'skills',id:skill.id,child}),'#aprendizaje/'+skill.id+'/tasks/qa-nested-task');render('aprendizaje',skill.id);assert(w.EntityLinks.focusTarget(child));rejects(()=>w.EntityLinks.assertChildRemovable(S.get(),'skills',skill.id,child));equal(S.list('skills').find(r=>r.id===skill.id).tasks[0].done,false);});
 await test('Contenido: plataforma Other conserva campos anteriores',()=>{const r=S.put('contentItems',{...w.Records.defaults('contentItems'),title:'QA otra plataforma',platform:'other',custom:{keep:true}});equal(r.platform,'other');equal(r.custom,{keep:true});S.validate(S.get());});
 render('inicio');
};
