'use strict';
window.V2App=(()=>{
 const e=Domain.escape,i=Views.icon,b=Views.button,F=Forms;let fileUrl=null;
 function recordForm(c,id,parent){const old=id?Store.list(c).find(r=>r.id===id):null;V2Domain.assert(Records.fields[c],'Este registro se edita desde su módulo de origen.');const r={...Records.defaults(c),...old};if(parent){if(c==='farmHealthRecords')r.animal_id=parent;else r.drop_id=parent;}
  const fields=Records.fields[c].map(([key,label,type,opts])=>{const required=type.includes('!'),base=type.replace('!',''),value=r[key]??'';if(base==='select')return F.select(key,label,opts,value);if(base.startsWith('relation'))return F.select(key,label,[...(base.endsWith('?')?[['','Sin vínculo']]:[]),...Store.list(opts).map(x=>[x.id,x.title||x.ear_tag])],value,true);if(base==='area')return F.area(key,label,value,`${required?'required':''} ${key==='brief_quotes'?'maxlength="500"':''}`);if(base==='tags')return F.field(key,label,(value||[]).join(', '),'text','',true);return F.field(key,label,base==='money'?(value||0)/100:value,base==='money'?'text':base==='nullableNumber'?'number':base==='date'?'date':base==='number'?'number':base==='url'?'url':'text',`${required?'required':''} ${['number','nullableNumber'].includes(base)?'min="0" max="1000000" step="1"':''} ${base==='money'?'inputmode="decimal" required':''}`,base==='text'||base==='url');}).join('');
  F.form((id?'Editar ':'Agregar ')+(Records.labels[c]||'registro'),'Se guardará en este navegador. Los importes se expresan en MXN.',fields,data=>{for(const [key,,type]of Records.fields[c]){if(type==='money')data[key]=Domain.cents(data[key]||0);else if(type==='number')data[key]=Number(data[key]||0);else if(type==='nullableNumber')data[key]=data[key]===''?null:Number(data[key]);else if(type.startsWith('date'))data[key]=data[key]||null;else if(type==='tags')data[key]=data[key].split(',').map(x=>x.trim()).filter(Boolean);else if(typeof data[key]==='string')data[key]=data[key].trim();}const next=Records.normalize(c,data,old||{});if(c==='farmAnimals'){next.title='Arete '+next.ear_tag;if(!id){next.reproductive_state=next.role==='sow'?'empty':'not_applicable';next.current_state_since=Domain.today();}}if(c==='visionItems'&&!id)next.position=Store.list(c).length;if(c==='books'){if(next.status==='reading'&&!next.started_at)next.started_at=Domain.today();if(next.status==='finished')next.finished_at=Domain.today();}Store.put(c,next,id);});
 }
 function photo(c,id){const rec=c==='profile'?Store.get().profile:Store.list(c).find(r=>r.id===id);V2Domain.assert(rec,'Registro no encontrado.');App.openDialog('Una imagen para tu espacio',`<p class="dialog-subtitle">JPEG, PNG o WebP · hasta 10 MB. Se comprime en este navegador y se guarda en IndexedDB.</p><input id="photo-file" class="input full-width" type="file" accept="image/jpeg,image/png,image/webp"><div id="photo-preview" class="crop-preview"></div><label class="form-check"><input id="photo-square" type="checkbox" checked>Recorte cuadrado</label><label class="form-field">Zoom<input id="crop-zoom" type="range" min="1" max="3" step=".1" value="1"></label><label class="form-field">Posición horizontal<input id="crop-x" type="range" min="0" max="1" step=".05" value=".5"></label><label class="form-field">Posición vertical<input id="crop-y" type="range" min="0" max="1" step=".05" value=".5"></label><p class="form-error" id="photo-error" role="alert"></p><div class="form-footer">${b('Cancelar','close-dialog')}<button id="save-photo" class="button primary" disabled>Confirmar imagen</button></div>`);let file;const opts=()=>({square:document.getElementById('photo-square').checked,zoom:Number(document.getElementById('crop-zoom').value),x:Number(document.getElementById('crop-x').value),y:Number(document.getElementById('crop-y').value)});let renderId=0;
  const preview=async()=>{if(!file)return;const n=++renderId;try{const data=await MediaStore.prepare(file,opts());if(n!==renderId)return;if(fileUrl)URL.revokeObjectURL(fileUrl);fileUrl=URL.createObjectURL(data.thumbnail);const img=document.createElement('img');img.src=fileUrl;img.alt='Vista previa del recorte';document.getElementById('photo-preview').replaceChildren(img);document.getElementById('save-photo').disabled=false;document.getElementById('photo-error').textContent='';}catch(error){document.getElementById('photo-error').textContent=error.message;document.getElementById('save-photo').disabled=true;}};
  document.getElementById('photo-file').onchange=ev=>{file=ev.target.files[0];preview();};for(const key of ['photo-square','crop-zoom','crop-x','crop-y'])document.getElementById(key).onchange=preview;
  document.getElementById('save-photo').onclick=async ev=>{ev.target.disabled=true;try{const mediaId=await MediaStore.save(file,opts());Store.save(s=>{if(c==='profile')s.profile.media_id=mediaId;else{s[c].find(r=>r.id===id).media_id=mediaId;s[c].find(r=>r.id===id).updated_at=new Date().toISOString();}});App.closeDialog();App.render();App.toast('Imagen guardada en este navegador.');}catch(error){document.getElementById('photo-error').textContent=error.message;ev.target.disabled=false;}};
 }
 function farmEvent(id,type){const labels={mating:'Registrar monta',farrowing:'Registrar parto',weaning:'Registrar destete',sale:'Registrar venta',state_correction:'Corrección auditada'};let fields=F.field('date','Fecha',Domain.today(),'date','required',true);if(type==='mating')fields+=F.field('sire_name','Semental activo confirmado',Farm.settings(Store.get()).active_sire_name,'text','required',true);if(type==='farrowing')fields+=F.field('born_total','Nacidos totales',0,'number','min="0" step="1" required')+F.field('born_alive','Nacidos vivos',0,'number','min="0" step="1" required');if(type==='weaning')fields+=F.field('weaned','Destetados',0,'number','min="0" step="1" required')+F.field('destination','Destino','','text');if(type==='sale')fields+=F.field('amount','Importe MXN (0 = no crear movimiento)',0,'text','inputmode="decimal" required',true);if(type==='state_correction')fields+=F.select('reproductive_state','Estado correcto',['empty','gestation','lactation','not_applicable'],'empty',true);fields+=F.area('notes','Notas / motivo', '',type==='state_correction'?'required':'');const eventId=crypto.randomUUID();F.form(labels[type],'El evento se conservará en el historial. No se prescribe ningún tratamiento.',fields,data=>{for(const k of ['born_total','born_alive','weaned'])if(k in data)data[k]=Number(data[k]);if('amount'in data)data.amount=Domain.cents(data.amount);Store.save(s=>Farm.event(s,id,type,data,eventId));},'Confirmar evento');}
 function farmSettings(){const old=Farm.settings(Store.get()),money=['feed_fortnight_min','feed_fortnight_max','piglet_price','kilo_price_min','kilo_price_max','sow_purchase_min','sow_purchase_max','cycle_cost','supplies_cost','reference_litter_revenue'],fields=[F.field('effective_date','Vigente desde',Domain.today(),'date','required'),F.field('active_sire_name','Semental de referencia',old.active_sire_name,'text','required')];for(const [key,label]of [['gestation_days','Gestación (días)'],['lactation_days','Lactancia (días)'],['heat_days','Revisión de celo (días)'],['reference_sows','Puercas de referencia'],['target_sows','Meta de reproductoras'],['target_piglets','Meta de lechones']])fields.push(F.field(key,label,old[key],'number','min="1" max="400" step="1" required'));for(const key of money)fields.push(F.field(key,key.replaceAll('_',' ')+' · MXN',old[key]/100,'text','inputmode="decimal" required'));fields.push(F.area('milestones','Hitos JSON: day, title, enabled',JSON.stringify(old.milestones,null,2),'required'));F.form('Protocolos y referencias','Cambiar referencias no registra animales, ventas ni rentabilidad. Confirma los protocolos con tu veterinario.',fields.join(''),data=>{const next={...old,...data};delete next.id;for(const k of ['gestation_days','lactation_days','heat_days','reference_sows','target_sows','target_piglets'])next[k]=Number(data[k]);for(const k of money)next[k]=Domain.cents(data[k]);next.milestones=V2Domain.safeTree(JSON.parse(data.milestones));V2Domain.assert(Array.isArray(next.milestones)&&next.milestones.every(m=>V2Domain.integer(m.day,0,400)&&V2Domain.text(m.title)&&typeof m.enabled==='boolean'),'Hitos inválidos.');Store.put('farmSettings',next);});}
 function importHistory(){App.openDialog('Historial de importaciones',`<p class="dialog-subtitle">Cada lote conserva sus versiones anteriores y posteriores. Deshacer no sobrescribe cambios posteriores sin avisar.</p>${Store.list('importBatches').slice().reverse().map(batch=>`<div class="record-row"><div class="record-main"><h3>${e(batch.format)}</h3><p>${Views.date(batch.created_at)} · ${batch.changes.length} registros · ${batch.undone_at?'Deshecho':'Aplicado'}</p></div>${!batch.undone_at?b('Deshacer','v2-undo-batch','',`data-id="${e(batch.id)}"`):''}</div>`).join('')||'<p class="muted">Aún no se han importado lotes.</p>'}`);}
 async function zipBackup(){V2Domain.assert(window.JSZip,'No se pudo cargar JSZip del CDN. Usa el respaldo JSON o restablece la conexión.');Store.validate(Store.get());const zip=new JSZip(),state=structuredClone(Store.get()),media=await MediaStore.all(),manifest=[];for(const r of media){zip.file('media/'+r.id+'.webp',r.blob);zip.file('media/'+r.id+'-thumb.webp',r.thumbnail);manifest.push({id:r.id,width:r.width,height:r.height});}zip.file('data.json',JSON.stringify(state));zip.file('manifest.json',JSON.stringify({format:'dali.backup',schema_version:state.version,media:manifest,created_at:new Date().toISOString()}));const blob=await zip.generateAsync({type:'blob'});App.download('dali-respaldo-'+Domain.today()+'.zip',blob,'application/zip');}
 function zipRestore(){V2Domain.assert(window.JSZip,'JSZip no disponible. Revisa tu conexión.');App.openDialog('Restaurar un respaldo completo',`<p class="dialog-subtitle">Reemplaza el estado completo y recupera sus imágenes. Se descargará primero un respaldo de seguridad. No es el importador operativo.</p><input id="zip-restore-file" class="input full-width" type="file" accept=".zip,application/zip"><p id="zip-restore-error" class="form-error"></p><div id="zip-restore-preview"></div>`);document.getElementById('zip-restore-file').onchange=async ev=>{try{const file=ev.target.files[0];V2Domain.assert(file&&file.size<50*1024*1024,'ZIP de hasta 50 MB requerido.');const zip=await JSZip.loadAsync(file);V2Domain.assert(zip.file('data.json')&&zip.file('manifest.json'),'Faltan data.json o manifest.json.');const data=JSON.parse(await zip.file('data.json').async('string')),manifest=JSON.parse(await zip.file('manifest.json').async('string'));V2Domain.safeTree(manifest);V2Domain.assert(manifest.format==='dali.backup'&&Array.isArray(manifest.media)&&manifest.media.length<=500,'Manifiesto incompatible.');Store.validate(data);const next=Migrations.migrate(data);Store.validate(next);const files=[];let total=0;for(const meta of manifest.media){V2Domain.assert(/^[a-zA-Z0-9-]{1,80}$/.test(meta.id),'ID de imagen inválido.');const f=zip.file('media/'+meta.id+'.webp'),t=zip.file('media/'+meta.id+'-thumb.webp');V2Domain.assert(f&&t,'Imagen ausente del ZIP.');const blob=await f.async('blob'),thumbnail=await t.async('blob');total+=blob.size+thumbnail.size;V2Domain.assert(total<100*1024*1024,'El contenido descomprimido supera el límite.');files.push({...meta,blob:new Blob([blob],{type:'image/webp'}),thumbnail:new Blob([thumbnail],{type:'image/webp'})});}const rev=Store.get().revision;document.getElementById('zip-restore-preview').innerHTML=`<p class="notice">Respaldo válido · ${files.length} imágenes. Reemplazará los registros actuales.</p><button class="button primary" id="zip-restore-confirm">Respaldar y confirmar restauración</button>`;document.getElementById('zip-restore-confirm').onclick=async event=>{event.target.disabled=true;const before=[];try{V2Domain.assert(Store.get().revision===rev,'Los datos cambiaron. Vuelve a abrir el respaldo.');await zipBackup();for(const r of files){before.push({id:r.id,record:await MediaStore.get(r.id)});await MediaStore.put(r);}Store.save(s=>{for(const key of Object.keys(next))if(key!=='revision')s[key]=next[key];});App.closeDialog();App.render();App.toast('Respaldo restaurado.');}catch(error){for(const r of before){if(r.record)await MediaStore.put(r.record);else await MediaStore.remove(r.id);}document.getElementById('zip-restore-error').textContent=error.message;event.target.disabled=false;}};}catch(error){document.getElementById('zip-restore-error').textContent=error.message;}};}
 function sale(id){const p=Store.list('alventoProducts').find(p=>p.id===id),saleId=crypto.randomUUID();F.form('Registrar venta',`${p.title} · ${V2Domain.stock(Store.get(),p)} unidades disponibles. Se creará un único ingreso en Finanzas.`,F.field('quantity','Unidades',1,'number',`min="1" max="${V2Domain.stock(Store.get(),p)}" step="1" required`)+F.field('date','Fecha',Domain.today(),'date','required'),data=>Store.save(s=>{if(s.alventoSales.some(x=>x.id===saleId))return;const q=Number(data.quantity),amount=p.unit_price*q,tid=crypto.randomUUID(),now=new Date().toISOString();V2Domain.assert(q<=V2Domain.stock(s,p),'No hay stock suficiente.');s.alventoSales.push({id:saleId,product_id:id,quantity:q,amount,cost:p.unit_cost*q,date:data.date,transaction_id:tid,created_at:now,updated_at:now});s.transactions.push({id:tid,title:'Venta ALVENTO · '+p.title,amount,type:'income',date:data.date,category:'Ventas',business_unit:'alvento',source:'alvento-sale',origin:saleId,related_entity_type:'drop',related_entity_id:p.drop_id,created_at:now,updated_at:now});}), 'Confirmar venta');}
 async function action(el){const a=el.dataset.action.slice(3),id=el.dataset.id,c=el.dataset.collection;
  if(a==='edit'){recordForm(c,id,el.dataset.parent);return;}if(a==='photo'){photo(c,id);return;}
  if(a==='remove-photo'){App.confirmAction('¿Eliminar la imagen del registro?','El archivo podrá limpiarse después desde Configuración. El resto del registro se conserva.',()=>Store.save(s=>{delete (c==='profile'?s.profile:s[c].find(r=>r.id===id)).media_id;}));return;}
  if(a==='gym-upload'||a==='route-upload'){UI.importKind=a==='gym-upload'?'gym':'learning';UI.importSkill=a==='route-upload'?id:null;App.closeDialog();location.hash='subir';return;}
  if(a==='validate-json'){UI.importText=document.getElementById('import-json').value;UI.importStrategy=document.getElementById('import-strategy').value;try{UI.importPreview=Importer.preview(UI.importText,{strategy:UI.importStrategy,skillId:UI.importSkill});UI.importError='';}catch(error){UI.importPreview=null;UI.importError=error.message;}App.render();return;}
  if(a==='commit-json'){V2Domain.assert(document.getElementById('import-confirm')?.checked,'Confirma que revisaste los cambios y avisos.');el.disabled=true;try{Importer.commit(UI.importPreview);UI.importPreview=null;UI.importText='';App.render();App.toast('Lote importado de forma atómica. Puedes deshacerlo desde el historial.');}catch(error){el.disabled=false;throw error;}return;}
  if(a==='example-json'){UI.importText=JSON.stringify(Importer.example(UI.importKind),null,2);UI.importPreview=null;UI.importError='';App.render();return;}
  if(a==='clear-json'){UI.importText='';UI.importPreview=null;UI.importError='';App.render();return;}
  if(a==='copy-prompt'){await navigator.clipboard.writeText(Importer.prompt);App.toast('Instrucciones copiadas. Añade los esquemas a tu conversación con ChatGPT.');return;}
  if(a==='schemas'){App.openDialog('Contratos JSON compatibles',`<p class="dialog-subtitle">El validador local aplica además reglas de negocio y relaciones. No se aceptan versiones desconocidas.</p><div class="settings-list">${['dali.crm.import','dali.gym.session','dali.learning.route','dali.journal.entry'].map(name=>`<a class="button" href="schemas/${name}.schema.json" download>${i('download')}${name}</a>`).join('')}</div>`);return;}
  if(a==='import-history'){importHistory();return;}
  if(a==='undo-batch'){App.confirmAction('¿Deshacer este lote?','Se restaurarán sus versiones anteriores. Los registros creados quedarán conservados en el historial del lote, fuera de las colecciones activas. Si hubo cambios posteriores, se cancelará.',()=>{Importer.undo(id);UI.importPreview=null;App.toast('Lote deshecho.');});return;}
  if(a==='farm-event'){farmEvent(id,el.dataset.type);return;}if(a==='farm-revert'){App.confirmAction('Revertir evento','Solo se permite revertir el último evento sin cambios posteriores. La camada y el movimiento vinculados se ajustarán en la misma operación.',()=>Farm.revert(Store.get(),id));
   document.getElementById('confirm-action').onclick=()=>{try{Store.save(s=>Farm.revert(s,id));App.closeDialog();App.render();App.toast('Evento revertido y conservado en historial.');}catch(error){document.getElementById('confirm-error').textContent=error.message;}};return;}
  if(a==='farm-settings'){PigForms.settings();return;}
  if(a==='business-expense'){F.form('Registrar gasto de '+el.dataset.business,'Se crea una sola transacción en el libro mayor central.',F.field('title','Concepto','','text','required',true)+F.field('amount','Monto MXN','','text','inputmode="decimal" required')+F.field('date','Fecha',Domain.today(),'date','required'),data=>{const amount=Domain.cents(data.amount);V2Domain.assert(amount>0,'El monto debe ser positivo.');Store.put('transactions',{...data,amount,type:'expense',category:'Otro',business_unit:el.dataset.business,related_entity_id:id||null,related_entity_type:id?'drop':null});});return;}
  if(a==='sale'){sale(id);return;}if(a==='sale-revert'){App.confirmAction('¿Revertir la venta?','Se restaurará el stock y se enviará a la papelera el ingreso vinculado, sin duplicados.',()=>Store.save(s=>{const sale=s.alventoSales.find(x=>x.id===id);sale.deleted_at=new Date().toISOString();s.transactions.find(t=>t.id===sale.transaction_id).deleted_at=sale.deleted_at;}));return;}
  if(a==='shot-add'){F.form('Agregar escena','El orden se puede ajustar después.',F.field('title','Descripción de la escena','','text','required',true),data=>Store.save(s=>{const r=s.contentItems.find(r=>r.id===id);r.shots.push({id:crypto.randomUUID(),title:data.title,done:false});r.updated_at=new Date().toISOString();}));return;}
  if(a==='shot-toggle'||a==='shot-up'||a==='shot-delete'){const run=()=>Store.save(s=>{const r=s.contentItems.find(r=>r.id===id),n=Number(el.dataset.index);if(a==='shot-toggle')r.shots[n].done=!r.shots[n].done;if(a==='shot-up'&&n>0)[r.shots[n-1],r.shots[n]]=[r.shots[n],r.shots[n-1]];if(a==='shot-delete'){if(r.shots[n]?.id)EntityLinks.assertChildRemovable(s,'contentItems',id,{collection:'shots',id:r.shots[n].id});r.shots.splice(n,1);}r.updated_at=new Date().toISOString();});if(a==='shot-delete')App.confirmAction('Eliminar escena','Se quitará esta escena de la lista. Las otras se conservarán.',run);else{run();App.render();}return;}
  if(a==='snapshot'){let fields=F.field('date','Fecha de observación',Domain.today(),'date','required',true);for(const key of ['views','likes','comments','shares','saves','followers_gained','retention_percent'])fields+=F.field(key,({views:'Vistas',likes:'Likes',comments:'Comentarios',shares:'Compartidos',saves:'Guardados',followers_gained:'Seguidores ganados',retention_percent:'Retención %'})[key],0,'number',`min="0" max="${key==='retention_percent'?100:1e9}" step="1" required`);fields+=F.area('lesson','Aprendizaje');F.form('Registrar métricas','Registro manual. No sustituye ni borra snapshots anteriores.',fields,data=>Store.save(s=>{const r=s.contentItems.find(r=>r.id===id);for(const key of ['views','likes','comments','shares','saves','followers_gained','retention_percent'])data[key]=Number(data[key]);r.snapshots.push({...data,id:crypto.randomUUID()});r.updated_at=new Date().toISOString();}));return;}
  if(a==='vision-up'){Store.save(s=>{const rows=s.visionItems.filter(r=>!r.deleted_at).sort((a,b)=>a.position-b.position),n=rows.findIndex(r=>r.id===id);if(n>0){[rows[n-1],rows[n]]=[rows[n],rows[n-1]];rows.forEach((r,pos)=>{r.position=pos;r.updated_at=new Date().toISOString();});}});App.render();return;}
  if(a==='vision-achieve'){App.confirmAction('¿Marcar esta aspiración como lograda?','No se borrará: seguirá formando parte de tu historia.',()=>Store.put('visionItems',{status:'achieved'},id));return;}
  if(a==='focus'){const r=Store.list('visionItems').find(x=>x.id===id);App.openDialog(r.title,`${V2Views.image(r.media_id,r.title)}<h3 style="margin:20px 0">${e(r.why)}</h3><p class="muted">A tu ritmo, en tu dirección.</p>`);MediaStore.hydrate();return;}
  if(a==='muscle'){const key=el.dataset.muscle,rows=Store.list('gymSessions').filter(s=>V2Domain.days(s.date,Domain.today())>=0&&V2Domain.days(s.date,Domain.today())<(UI.gymDays||28)).flatMap(s=>s.exercises.filter(ex=>ex.primary_muscles?.includes(key)).map(ex=>({date:s.date,...ex})));App.openDialog(V2Domain.muscles[key],`<p class="dialog-subtitle">Series registradas en el periodo; sin diagnóstico ni estimación de recuperación.</p>${rows.map(ex=>`<div class="key-value"><span>${e(ex.name)}<small style="display:block">${Views.date(ex.date)}</small></span><strong>${ex.sets.length} series</strong></div>`).join('')||'<p>No hay series atribuidas a este músculo.</p>'}`);return;}
  if(a==='preferences'){F.form('Reloj y saludo','Se usa siempre la zona America/Mexico_City.',F.select('greeting','Cómo te saludo',[['jefe','Jefe'],['name','Mi nombre preferido']],Store.get().preferences.greeting,true)+F.check('hour12','Mostrar reloj de 12 horas',Store.get().preferences.hour12),data=>Store.save(s=>{s.preferences.greeting=data.greeting;s.preferences.hour12=!!data.hour12;}));return;}
  if(a==='legacy-export'){App.download('dali-legado-v1.json',JSON.stringify({routines:Store.get().routines,sessions:Store.get().sessions},null,2),'application/json');return;}
  if(a==='pre-migration'){const raw=localStorage.getItem(DALI_CONFIG.storageKey+'-pre-v4')||localStorage.getItem(DALI_CONFIG.storageKey+'-pre-v3')||localStorage.getItem(DALI_CONFIG.storageKey+'-pre-v2');V2Domain.assert(raw,'No hay copia previa: este navegador empezó directamente con la versión actual.');App.download('dali-pre-migracion.json',raw,'application/json');return;}
  if(a==='backup-zip'){el.disabled=true;try{await zipBackup();App.toast('Respaldo ZIP generado.');}finally{el.disabled=false;}return;}
  if(a==='restore-zip'){zipRestore();return;}
  if(a==='clean-media'){App.confirmAction('Limpiar imágenes sin referencias','No se tocarán imágenes usadas por registros, papelera o historial de importación.',()=>{});document.getElementById('confirm-action').onclick=async()=>{try{const count=await MediaStore.clean();App.closeDialog();App.toast(count+' imágenes no referenciadas eliminadas.');}catch(error){document.getElementById('confirm-error').textContent=error.message;}};return;}
  if(a==='source-zip'){V2Domain.assert(window.JSZip,'JSZip no disponible. Revisa la conexión.');el.disabled=true;try{const manifestResponse=await fetch('project-files.json');V2Domain.assert(manifestResponse.ok,'No se pudo leer el listado del proyecto.');const files=await manifestResponse.json(),zip=new JSZip();V2Domain.assert(Array.isArray(files)&&files.every(file=>typeof file==='string'&&!file.includes('..')&&!file.startsWith('/')&&!file.includes(':')),'Listado de archivos inválido.');const controller=new AbortController();let cursor=0;const timeout=setTimeout(()=>controller.abort(),90000);try{await Promise.all(Array.from({length:Math.min(6,files.length)},async()=>{while(cursor<files.length){const file=files[cursor++],response=await fetch(file,{signal:controller.signal});V2Domain.assert(response.ok,'No se pudo leer '+file);zip.file(file,await response.blob());}}));}catch(error){controller.abort();throw new Error(error.name==='AbortError'?'La descarga del proyecto tardó demasiado. Revisa la conexión e inténtalo de nuevo.':error.message);}finally{clearTimeout(timeout);}const blob=await zip.generateAsync({type:'blob'});App.download('dali-neural-v4-en-desarrollo.zip',blob,'application/zip');App.toast('Proyecto estático generado. No incluye tus registros locales.');}finally{el.disabled=false;}return;}
 }
 function clock(){const p=Store.get()?.preferences;if(!p)return;const hour=Number(new Intl.DateTimeFormat('en-GB',{timeZone:DALI_CONFIG.timezone,hour:'2-digit',hourCycle:'h23'}).format(new Date())),greeting=hour>=5&&hour<12?'Buenos días':hour>=12&&hour<19?'Buenas tardes':'Buenas noches';const title=document.getElementById('live-greeting');if(title)title.textContent=greeting+', '+(p.greeting==='name'?Store.get().profile.preferred:'jefe')+'.';const c=document.getElementById('local-clock');if(c)c.textContent=new Intl.DateTimeFormat('es-MX',{timeZone:DALI_CONFIG.timezone,hour:'2-digit',minute:'2-digit',hour12:!!p.hour12}).format(new Date())+' · '+Views.date(Domain.today(),{weekday:'long',day:'numeric',month:'long'});}
 function afterRender(){clock();MediaStore.hydrate();const file=document.getElementById('json-file'),drop=document.getElementById('json-drop');const load=async f=>{try{V2Domain.assert(f&&f.size<=DALI_CONFIG.limits.jsonBytes,'Archivo de hasta 1 MB requerido.');UI.importText=await f.text();UI.importPreview=null;UI.importError='';App.render();}catch(error){App.toast(error.message,'error');}};if(file)file.onchange=ev=>load(ev.target.files[0]);if(drop){drop.ondragover=ev=>{ev.preventDefault();drop.classList.add('dragging');};drop.ondragleave=()=>drop.classList.remove('dragging');drop.ondrop=ev=>{ev.preventDefault();load(ev.dataTransfer.files[0]);};}const json=document.getElementById('import-json');if(json)json.oninput=()=>{UI.importText=json.value;UI.importPreview=null;document.querySelector('[data-action="v2-commit-json"]')?.setAttribute('disabled','');};const gym=document.getElementById('v2-gym-days');if(gym)gym.onchange=()=>{UI.gymDays=Number(gym.value);App.render();};}
 function init(){document.addEventListener('keydown',ev=>{if((ev.key==='Enter'||ev.key===' ')&&ev.target.matches('.body-silhouette [data-action]')){ev.preventDefault();action(ev.target).catch(error=>App.toast(error.message,'error'));}});document.getElementById('app-dialog').addEventListener('close',()=>{if(fileUrl){URL.revokeObjectURL(fileUrl);fileUrl=null;}});}
 return {action,afterRender,init,recordForm,zipBackup,clock};
})();
