import {chromium} from 'playwright';
import fs from 'node:fs';
const browser=await chromium.launch({args:['--no-sandbox']}),page=await browser.newPage({viewport:{width:1440,height:900}}),errors=[],matrix=[],shots=[],start=Date.now();
page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
await page.goto('http://localhost:3000/index.html?qa=evie-visual');await page.waitForFunction(()=>window.DALI_READY);await page.evaluate(()=>document.fonts.ready);await page.evaluate(()=>{Neural.dismiss();Store.save(s=>{for(const c of ['clients','routines','skills'])s[c]=[];});App.render();});
const sizes=[[360,800],[390,844],[412,915],[430,932],[768,1024],[1024,768],[1280,800],[1440,900],[1920,1080]];
const routes=await page.evaluate(()=>DALI_CONFIG.sections.map(x=>x.route));
for(const [width,height] of sizes){await page.setViewportSize({width,height});for(const theme of ['dark','light']){for(const motion of ['full','subtle','reduced','paused']){await page.evaluate(({theme,motion})=>{Store.save(s=>{s.preferences.theme=theme;s.preferences.motion=motion==='paused'?'full':motion;s.preferences.motionPaused=motion==='paused';});},{theme,motion});for(const route of routes){await page.evaluate(route=>{UI.section=route;UI.id=null;App.render();},route);const check=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth+1,scrollWidth:document.documentElement.scrollWidth,invalid:/\b(undefined|NaN|Invalid Date)\b/.test(document.querySelector('main').innerText),heading:!!document.querySelector('main h1'),renderer:IvyRenderer.stats().renderer,raf:IvyRenderer.stats().raf}));matrix.push({width,height,theme,motion,route,...check});
 if(motion==='reduced'&&((route==='inicio')||([390,1440].includes(width)&&theme==='dark'))){await page.waitForTimeout(30);const file=`evidence/${route}-${width}-${theme}.png`;await page.screenshot({path:file});shots.push(file);}
}}}}
await page.setViewportSize({width:1440,height:900});await page.evaluate(()=>{Store.save(s=>{s.preferences.theme='dark';s.preferences.motion='full';s.preferences.motionPaused=false;});UI.section='inicio';App.render();});await page.waitForTimeout(2200);const perf=await page.evaluate(()=>IvyRenderer.stats());
await page.evaluate(()=>IvyChat.open());await page.locator('#ivy-command-input').fill('Crea pendiente: Preparar revisión hoy');await page.locator('#ivy-command-form button').click();await page.locator('#ivy-proposal-form button[type=submit]').click();await page.screenshot({path:'evidence/ivy-confirmation-desktop.png'});shots.push('evidence/ivy-confirmation-desktop.png');await page.setViewportSize({width:390,height:844});await page.screenshot({path:'evidence/ivy-confirmation-mobile.png'});shots.push('evidence/ivy-confirmation-mobile.png');await page.locator('[data-ivy=cancel]').click();await page.keyboard.press('Escape');
// Real keyboard activation and focus restoration.
await page.evaluate(()=>document.getElementById('dali-core-control').focus());await page.keyboard.press('Enter');const keyboardOpen=await page.locator('#dali-core-menu').evaluate(el=>el.open);await page.keyboard.press('Escape');const focusRestored=await page.evaluate(()=>document.activeElement.id==='dali-core-control');
await page.evaluate(()=>{document.body.style.zoom='2';App.render();});const zoomOverflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);await page.screenshot({path:'evidence/home-390-zoom200.png'});shots.push('evidence/home-390-zoom200.png');await page.evaluate(()=>document.body.style.zoom='');
const summary={date:new Date().toISOString(),browser:await browser.version(),durationMs:Date.now()-start,checks:matrix.length,errors,issues:matrix.filter(x=>x.overflow||x.invalid||!x.heading),keyboardOpen,focusRestored,zoomOverflow,performance:perf,shots,matrix};fs.writeFileSync('evidence/visual-matrix.json',JSON.stringify(summary,null,2));console.log(JSON.stringify({...summary,matrix:undefined,shots:summary.shots.length},null,2));await browser.close();
if(summary.errors.length||summary.issues.length||!keyboardOpen||!focusRestored||zoomOverflow)process.exitCode=1;
