'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const {validateWav}=require('../electron/voice/local-voice.cjs');
function harness(){
 const calls={transcribe:0,speak:0,ask:0,stopped:0,closed:0},timers=new Map(),worklets=[],contexts=[],players=[];let timerId=0;
 const track={onended:null,stop(){calls.stopped++;}};const stream={getTracks:()=>[track]};
 class AudioNode{connect(next){return next;}disconnect(){}start(){}stop(){}getFloatTimeDomainData(a){a.fill(.05);}}
 class Context{constructor(){this.sampleRate=48000;this.state='running';this.destination={};this.audioWorklet={addModule:async()=>{}};contexts.push(this);}async resume(){}async close(){this.state='closed';calls.closed++;}async decodeAudioData(){return {};}createMediaStreamSource(){return new AudioNode();}createAnalyser(){return new AudioNode();}createGain(){const n=new AudioNode();n.gain={value:1};return n;}createBufferSource(){const n=new AudioNode();players.push(n);return n;}}
 class Worklet extends AudioNode{constructor(){super();this.port={postMessage(){},onmessage:null};worklets.push(this);}}
 const c={console,Float32Array,Uint8Array,ArrayBuffer,DataView,AudioContext:Context,AudioWorkletNode:Worklet,
  navigator:{mediaDevices:{getUserMedia:async()=>stream}},document:{querySelectorAll:()=>[],addEventListener(){}},addEventListener(){},
  requestAnimationFrame:()=>1,cancelAnimationFrame(){},setTimeout(fn){const id=++timerId;timers.set(id,fn);return id;},clearTimeout(id){timers.delete(id);},
  evieDesktop:{async transcribe(wav){calls.transcribe++;validateWav(wav);return {ok:true,data:{text:'Prueba sintética'}};},async speak(){calls.speak++;return {ok:true,data:{audio:new Uint8Array(44)}};}},
  DesktopUI:{transcript(){},async ask(){calls.ask++;},notice(){}}};c.window=c;vm.createContext(c);
 for(const file of ['ivy-state-machine.js','desktop-voice.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'../public',file),'utf8'),c);
 c.IvyState.transition('idle');return {c,calls,timers,worklets,contexts,players,track};
}
const tick=()=>new Promise(r=>setImmediate(r));
test('diagnostic mic timeout discards without transcription or model dispatch',async()=>{const h=harness();await h.c.DesktopVoice.start({diagnostic:true});assert.equal(h.c.DesktopVoice.stats().diagnostic,true);h.worklets[0].port.onmessage({data:new Float32Array(4800)});await [...h.timers.values()][0]();assert.equal(h.calls.transcribe,0);assert.equal(h.calls.ask,0);assert.equal(h.c.DesktopVoice.stats().tracks,0);assert.equal(h.c.DesktopVoice.stats().frames,false);assert.equal(h.calls.stopped,1);});
test('synthetic PCM recording encodes valid mono WAV and releases before dispatch',async()=>{const h=harness();await h.c.DesktopVoice.start();h.worklets[0].port.onmessage({data:new Float32Array(4800).fill(.2)});await h.c.DesktopVoice.finish();assert.equal(h.calls.transcribe,1);assert.equal(h.calls.ask,1);assert.equal(h.calls.closed,1);assert.equal(h.c.DesktopVoice.stats().tracks,0);assert.equal(h.track.onended,null);});
test('cancel during microphone permission stops late stream without starting recorder',async()=>{const h=harness();let resolve;h.c.navigator.mediaDevices.getUserMedia=()=>new Promise(r=>resolve=r);const start=h.c.DesktopVoice.start();await tick();await h.c.DesktopVoice.stop();resolve({getTracks:()=>[h.track]});await start;assert.equal(h.calls.stopped,1);assert.equal(h.worklets.length,0);assert.equal(h.c.IvyState.get().phase,'idle');});
test('cancel ignores late transcription and never sends it to model',async()=>{const h=harness();let resolve;h.c.evieDesktop.transcribe=()=>new Promise(r=>resolve=r);await h.c.DesktopVoice.start();h.worklets[0].port.onmessage({data:new Float32Array(4800)});const finish=h.c.DesktopVoice.finish();await tick();await h.c.DesktopVoice.stop();resolve({ok:true,data:{text:'late'}});await finish;assert.equal(h.calls.ask,0);assert.equal(h.c.IvyState.get().phase,'idle');});
test('cancel ignores late TTS and leaves no output AudioContext',async()=>{const h=harness();let resolve;h.c.evieDesktop.speak=()=>new Promise(r=>resolve=r);const speech=h.c.DesktopVoice.speak('QA');await tick();await h.c.DesktopVoice.stop();resolve({ok:true,data:{audio:new Uint8Array(44)}});await speech;assert.equal(h.contexts.length,0);assert.equal(h.c.DesktopVoice.stats().mode,'idle');});
test('VAD requires voice and 1100ms silence; steady ambient never dispatches',()=>{const v=harness().c.DesktopVoice.createVAD(),block=x=>new Float32Array(4800).fill(x);for(let i=0;i<100;i++)assert.equal(v.push(block(.004),48000),false);assert.equal(v.heard,false);for(let i=0;i<4;i++)assert.equal(v.push(block(.12),48000),false);assert.equal(v.heard,true);for(let i=0;i<10;i++)assert.equal(v.push(block(0),48000),false);assert.equal(v.push(block(0),48000),true);assert.equal(v.push(block(0),48000),false);const noise=harness().c.DesktopVoice.createVAD();for(let i=0;i<500;i++)assert.equal(noise.push(block(.08),48000),false);});
test('continuous session sends one utterance then waits for actual TTS end before listening',async()=>{const h=harness();h.c.DesktopUI.ask=async()=>{h.calls.ask++;await h.c.DesktopVoice.speak('Respuesta');return true;};await h.c.DesktopVoice.beginSession();const push=x=>h.worklets[0].port.onmessage({data:new Float32Array(4800).fill(x)});for(let i=0;i<4;i++)push(0);for(let i=0;i<4;i++)push(.1);for(let i=0;i<11;i++)push(0);await tick();assert.equal(h.calls.transcribe,1);assert.equal(h.calls.ask,1);assert.equal(h.c.DesktopVoice.stats().mode,'speaking');assert.equal(h.c.DesktopVoice.stats().tracks,0);assert.equal(h.worklets.length,1);h.players[0].onended();await tick();assert.equal(h.c.DesktopVoice.stats().mode,'listening');assert.equal(h.worklets.length,2);await h.c.DesktopVoice.stop();assert.equal(h.c.DesktopVoice.stats().session,false);assert.equal(h.c.DesktopVoice.stats().tracks,0);});
test('stop during continuous playback resolves pending speech without reopening microphone',async()=>{const h=harness();await h.c.DesktopVoice.beginSession();const speech=h.c.DesktopVoice.speak('Respuesta');await tick();await h.c.DesktopVoice.stop();await speech;assert.equal(h.c.DesktopVoice.stats().tracks,0);assert.equal(h.c.DesktopVoice.stats().session,false);assert.equal(h.worklets.length,1);});
test('denied session permission stops once with no retry timer',async()=>{const h=harness();let attempts=0;h.c.navigator.mediaDevices.getUserMedia=async()=>{attempts++;const e=new Error('denied');e.name='NotAllowedError';throw e;};await assert.rejects(h.c.DesktopVoice.beginSession(),/denegado/);assert.equal(attempts,1);assert.equal(h.c.DesktopVoice.stats().session,false);assert.equal(h.timers.size,0);});
test('desktop state helper retains illegal transition rejection and cancels executing safely',()=>{const h=harness(),v=h.c.DesktopVoice;assert.throws(()=>v.state('success'));assert.throws(()=>v.state('unknown'));v.state('thinking');v.state('awaiting_confirmation');v.state('executing');v.state('idle');assert.equal(h.c.IvyState.get().phase,'idle');});
