'use strict';
const {app,BrowserWindow,protocol,net,ipcMain,dialog,shell,Notification,Tray,Menu,globalShortcut,screen,session,nativeImage,safeStorage}=require('electron');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),{randomUUID}=require('node:crypto');
const {validate,object,text,enumeration,tool,rateLimit}=require('../security/contracts.cjs');
const {createRegistry}=require('../tools/registry.cjs');const {windowsTools,executable,grantKey}=require('../tools/windows.cjs');const {createCatalog}=require('../tools/catalog.cjs');const {createConfirmation}=require('../security/confirmation.cjs');
const {OllamaProvider,createConversation}=require('../ai/ollama.cjs');const {createVoice,validateWav}=require('../voice/local-voice.cjs');const processes=require('../voice/process.cjs');
const ROOT=path.resolve(__dirname,'../..'),PUBLIC=path.join(ROOT,'public'),ORIGIN='evie://app';
app.setName('EVIE CRM V2');app.setPath('userData',path.join(app.getPath('appData'),'EVIE-CRM-V2'));app.setAppUserModelId('com.evie.crm.v2');
protocol.registerSchemesAsPrivileged([{scheme:'evie',privileges:{standard:true,secure:true,supportFetchAPI:true,stream:true}}]);
const csp="default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self'; media-src 'self' blob:; connect-src 'self'; object-src 'none'; base-uri 'none'; form-action 'none'; frame-src 'none'; frame-ancestors 'none'";
let win,tray,settings,voice,conversation,registry,google,catalog,confirmation,micPrompt=null,quitting=false;const pending=new Map();
// URL.origin for custom schemes can be null; validate scheme, host and main frame explicitly.
function isTrusted(event){if(!win||win.isDestroyed()||event.sender!==win.webContents||event.senderFrame!==win.webContents.mainFrame)return false;try{const u=new URL(event.senderFrame.url);return u.protocol==='evie:'&&u.host==='app';}catch{return false;}}
function send(action){if(win&&!win.isDestroyed())win.webContents.send('evie:action',action);}
function crm(action,payload={}){return new Promise((resolve,reject)=>{const id=randomUUID(),timer=setTimeout(()=>{pending.delete(id);reject(Error('El CRM no respondió. Abre EVIE y vuelve a intentarlo.'));},15000);pending.set(id,{resolve,reject,timer});win.webContents.send('evie:crm',{id,action,payload});});}
function trustedOrigin(raw){try{const u=new URL(raw);return u.protocol==='evie:'&&u.host==='app';}catch{return false;}}
async function microphoneConsent(force=false){
 const s=settings.get();if(!force&&s.microphoneAsked)return s.microphoneConsent===true;
 if(micPrompt)return micPrompt;
 micPrompt=(async()=>{const r=await dialog.showMessageBox(win,{type:'question',message:'¿Permitir el micrófono a Ivy?',detail:'Solo al activar una sesión. Whisper procesa el audio localmente y lo descarta. Este permiso se conserva; puedes revocarlo en Configuración. Windows conserva su propio control de privacidad.',buttons:['No permitir','Permitir'],defaultId:0,cancelId:0});settings.microphone(r.response===1);return r.response===1;})();
 try{return await micPrompt;}finally{micPrompt=null;}
}
function status(phase){send({type:'state',phase});}
function cancelWork(){conversation?.cancel();registry?.cancel();confirmation?.cancel();processes.stop();send({type:'stop'});}
async function confirm(action){status('awaiting_confirmation');const approved=await confirmation.request(action);if(approved)status('executing');return approved;}
function helper(name){return app.isPackaged?path.join(process.resourcesPath,'scripts',name):path.join(ROOT,'scripts',name);}
function registerShortcut(){globalShortcut.unregisterAll();if(settings.get().globalShortcut){const ok=globalShortcut.register('CommandOrControl+Space',()=>{win.show();send({type:'listen'});});if(!ok)send({type:'notice',text:'Ctrl+Espacio global no está disponible.'});}}
function createWindow(){let bounds={x:0,y:0,width:1440,height:940};try{const b=JSON.parse(fs.readFileSync(path.join(app.getPath('userData'),'window.json'),'utf8'));if(Number.isFinite(b.width)&&Number.isFinite(b.height))bounds=b;}catch{}const area=screen.getDisplayMatching(bounds).workArea;bounds={width:Math.max(800,Math.min(bounds.width,area.width)),height:Math.max(600,Math.min(bounds.height,area.height)),x:Math.max(area.x,Math.min(bounds.x??area.x,area.x+area.width-800)),y:Math.max(area.y,Math.min(bounds.y??area.y,area.y+area.height-600))};
 const s=settings.get(),mode=process.platform==='win32'?s.appearance:'solid',overlay=mode==='transparent';
 win=new BrowserWindow({...bounds,title:'EVIE CRM V2',frame:false,transparent:overlay,backgroundColor:overlay?'#00000000':'#080b10',...(mode==='acrylic'?{backgroundMaterial:'acrylic'}:{}),resizable:!overlay,maximizable:!overlay,icon:path.join(PUBLIC,'icons/ivy-512.png'),show:false,webPreferences:{preload:path.join(ROOT,'electron/preload/preload.cjs'),contextIsolation:true,nodeIntegration:false,sandbox:true,webSecurity:true,allowRunningInsecureContent:false,spellcheck:false,devTools:!app.isPackaged}});
 win.setMenu(null);win.webContents.setWindowOpenHandler(()=>({action:'deny'}));win.webContents.on('will-navigate',(e,url)=>{if(url.split('#')[0]!==ORIGIN+'/index.html')e.preventDefault();});win.webContents.on('will-attach-webview',e=>e.preventDefault());win.on('ready-to-show',()=>win.show());
 let timer;win.on('move',saveBounds);win.on('resize',saveBounds);function saveBounds(){clearTimeout(timer);timer=setTimeout(()=>{if(win&&!win.isDestroyed()&&!win.isMinimized()&&!win.isMaximized())fs.writeFileSync(path.join(app.getPath('userData'),'window.json'),JSON.stringify(win.getBounds()));},400);}
 win.on('close',()=>{cancelWork();clearTimeout(timer);});win.on('closed',()=>{for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('Ventana cerrada.'));}pending.clear();win=null;});
 win.loadURL(ORIGIN+'/index.html');registerShortcut();
 tray=new Tray(nativeImage.createFromPath(path.join(PUBLIC,'icons/ivy-192.png')).resize({width:20,height:20}));tray.setToolTip('EVIE CRM V2');tray.setContextMenu(Menu.buildFromTemplate([{label:'Abrir EVIE',click:()=>win?.show()},{label:'Escuchar',click:()=>{win?.show();send({type:'listen'});}},{label:'Dejar de escuchar',click:cancelWork},{label:'Diagnóstico',click:()=>{win?.show();send({type:'diagnostics'});}},{type:'separator'},{label:'Salir',click:()=>app.quit()}]));tray.on('double-click',()=>win?.show());
}
async function install(){fs.mkdirSync(app.getPath('userData'),{recursive:true});
 const accountOrigin=process.env.EVIE_ACCOUNT_API_ORIGIN||'';
 settings=require('./scoped-settings.cjs')(app.getPath('userData'),{enabled:!!accountOrigin});
 const accountSession=session.fromPartition('persist:evie-accounts');
 const account=require('./account-host.cjs').createAccountHost({origin:accountOrigin,fetcher:(url,options)=>accountSession.fetch(url,options),onChange:id=>{
  cancelWork();for(const p of pending.values()){clearTimeout(p.timer);p.reject(Error('La cuenta cambió.'));}pending.clear();settings.select(id);
  if(id)google=require('../calendar/google.cjs')({dir:path.join(app.getPath('userData'),'accounts',id,settings.deviceId),safeStorage,shell,dialog,getWindow:()=>win});
  else if(accountOrigin)google={status:()=>({connected:false}),configure:async()=>{throw Error('Inicia sesión.');},connect:async()=>{throw Error('Inicia sesión.');},disconnect:async()=>true};
  registerShortcut();
 }});
 protocol.handle('evie',async request=>{const u=new URL(request.url);let file;try{if(u.host!=='app'||!['GET','HEAD'].includes(request.method))return new Response('Not found',{status:404});file=path.resolve(PUBLIC,'.'+decodeURIComponent(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(PUBLIC+path.sep)||!fs.statSync(file).isFile())return new Response('Not found',{status:404});}catch{return new Response('Not found',{status:404});}const response=await net.fetch(pathToFileURL(file).href);const headers=new Headers(response.headers);headers.set('Content-Security-Policy',csp);headers.set('X-Content-Type-Options','nosniff');return new Response(response.body,{status:response.status,headers});});
 session.defaultSession.setPermissionCheckHandler((wc,permission,origin,details)=>wc===win?.webContents&&permission==='media'&&trustedOrigin(origin)&&details?.mediaType==='audio'&&settings.get().microphoneConsent===true);
 session.defaultSession.setPermissionRequestHandler(async(wc,permission,callback,details)=>{if(wc!==win?.webContents||permission!=='media'||details.isMainFrame===false||!trustedOrigin(details.requestingUrl)||!details.mediaTypes?.length||details.mediaTypes.some(t=>t!=='audio'))return callback(false);try{callback(await microphoneConsent());}catch{callback(false);}});
 const provider=new OllamaProvider();voice=createVoice({settings:settings.get,helper:helper('windows-tts.ps1')});google=accountOrigin?{status:()=>({connected:false})}:require('../calendar/google.cjs')({dir:app.getPath('userData'),safeStorage,shell,dialog,getWindow:()=>win});
 confirmation=createConfirmation({send});catalog=createCatalog({settings:settings.get,helper:helper('discover-apps.ps1'),getIcon:async file=>(await app.getFileIcon(file,{size:'small'})).toDataURL()});
 const windows=windowsTools({settings:settings.get,shell,Notification,helper:helper('windows-tools.ps1'),updateFile:(id,file)=>settings.mapping('files',id,file)});registry=createRegistry({crm,windows,confirm,audit:require('../security/audit.cjs')(app.getPath('userData')),settings:settings.get});const executeTool=registry.execute;registry.execute=async(name,args)=>{status('thinking');const result=await executeTool(name,args);status(result.ok?'success':'error');return result;};conversation=createConversation({provider,registry,settings:settings.get,status,context:()=>crm('diagnostics')});
 ipcMain.on('evie:crm-result',(event,msg)=>{if(!isTrusted(event)||!msg||typeof msg.id!=='string'||!pending.has(msg.id))return;const p=pending.get(msg.id);pending.delete(msg.id);clearTimeout(p.timer);try{if(JSON.stringify(msg.result).length>150000)throw Error('Respuesta demasiado grande.');if(msg.result?.ok===false)throw Error(msg.result.error||'Agenda rechazó la solicitud.');p.resolve(msg.result);}catch(e){p.reject(e);}});
 const limit=rateLimit(90),voiceLimit=rateLimit(60),requests={
  account:args=>account.request(args),
  'settings.get':async()=>settings.get(),'settings.patch':async args=>{validate(require('./settings.cjs').schema,args);const previous=settings.get();for(const key of ['model','fastModel','preciseModel'])if(args[key]&&args[key]!==previous[key]){if(!(await provider.models()).includes(args[key])||!await provider.supportsTools(args[key]))throw Error('Selecciona un modelo instalado compatible. No se descargó ni cambió el modelo.');}if(args.appearance&&args.appearance!==previous.appearance){const r=await dialog.showMessageBox(win,{message:'El modo de ventana requiere reiniciar EVIE. Guarda tus formularios antes de continuar.',buttons:['Cancelar','Guardar modo y reiniciar'],defaultId:0,cancelId:0});if(!r.response)return previous;const s=settings.patch(args);app.relaunch();app.quit();return s;}const s=settings.patch(args);registerShortcut();return s;},
  models:async()=>provider.compatibleModels(),
  'apps.list':async()=>catalog.list(),'apps.discover':async()=>catalog.discover(),
  'apps.icon':async args=>{validate(object({id:text(80)}),args);return catalog.icon(args.id);},
  'apps.authorize':async args=>{validate(object({id:text(80)}),args);const item=catalog.candidate(args.id);const r=await dialog.showMessageBox(win,{message:'¿Autorizar '+item.name+'?',detail:JSON.stringify(item,null,2)+'\nSolo apertura y control de ventana no destructivo. Cerrar siempre pide confirmación.',buttons:['Cancelar','Autorizar aplicación'],defaultId:0,cancelId:0});if(!r.response)return false;settings.mapping('apps',args.id,item);settings.grant(grantKey('windows.open_app',{appId:args.id}),true);return true;},
  'apps.revoke':async args=>{validate(object({id:text(80)}),args);settings.mapping('apps',args.id,null);for(const key of Object.keys(settings.get().grants))if(key.includes(':'+args.id))settings.grant(key,false);return true;},
  'mapping.revoke':async args=>{validate(object({kind:enumeration(['locations','files']),id:text(80)}),args);settings.mapping(args.kind,args.id,null);return true;},
  'grant.revoke':async args=>{validate(object({key:text(200)}),args);settings.grant(args.key,false);return true;},
  'confirmation.answer':async args=>{validate(object({token:text(80),approved:{type:'boolean'},always:{type:'boolean'}},['token','approved']),args);const action=confirmation.inspect(args.token);if(args.always&&args.approved){if(action.permission!=='light'||!action.name.startsWith('windows.'))throw Error('Esta acción siempre requiere confirmación.');settings.grant(grantKey(action.name,action.args),true);}return confirmation.answer(args.token,args.approved);},
  'confirmation.audio':async args=>{if(Object.keys(args).sort().join(',')!=='token,wav')throw Error('Audio de confirmación inválido.');validate(text(80),args.token);confirmation.inspect(args.token);validateWav(args.wav);voiceLimit();const result=await voice.transcribe(args.wav);return confirmation.spoken(args.token,result.text);},
  microphone:async args=>{validate(object({action:enumeration(['authorize','revoke'])}),args);if(args.action==='revoke'){settings.microphone(false);cancelWork();return false;}return microphoneConsent(true);},
  window:async args=>{validate(object({action:enumeration(['minimize','maximize','close'])}),args);if(args.action==='close')win.close();if(args.action==='minimize')win.minimize();if(args.action==='maximize'){if(!win.isMaximizable())throw Error('El modo transparente usa tamaño fijo.');win.isMaximized()?win.unmaximize():win.maximize();}return true;},
  chat:async args=>{validate(object({text:text(8000)}),args);voiceLimit();return conversation.ask(args.text);},cancel:async()=>{cancelWork();return true;},
  transcribe:async args=>{if(Object.keys(args).length!==1)throw Error('Audio inválido.');validateWav(args.wav);voiceLimit();return voice.transcribe(args.wav);},speak:async args=>{validate(object({text:text(5000)}),args);voiceLimit();return voice.speak(args.text);},voices:async()=>voice.voices(),
  tool:async args=>{if(!args||Object.keys(args).sort().join(',')!=='args,name')throw Error('Solicitud de herramienta inválida.');tool(args.name,args.args);return registry.execute(args.name,args.args);},
  mapping:async args=>{validate(object({kind:enumeration(['apps','locations','files']),id:{...text(40),pattern:'^[a-zA-Z0-9-]+$'}}),args);const r=await dialog.showOpenDialog(win,{title:'Autorizar '+args.id+' · selecciona solo una aplicación/carpeta de confianza',properties:args.kind==='locations'?['openDirectory']:['openFile'],...(args.kind==='apps'?{filters:[{name:'Aplicación Windows',extensions:['exe']}]}:{})});if(r.canceled)return false;const file=r.filePaths[0];if(args.kind==='apps')executable(file);if(args.kind==='files')require('../tools/files.cjs').selection(file);settings.mapping(args.kind,args.id,args.kind==='apps'?{path:file}:file);return true;},
  asset:async args=>{validate(object({kind:enumeration(['whisperBinary','whisperModel'])}),args);const r=await dialog.showOpenDialog(win,{title:'Configurar componente local de confianza',properties:['openFile'],filters:[{name:args.kind,extensions:args.kind==='whisperModel'?['bin']:['exe']}]});if(r.canceled)return false;const file=r.filePaths[0];if(args.kind==='whisperBinary'&&path.basename(file).toLowerCase()!=='whisper-cli.exe')throw Error('Selecciona whisper-cli.exe de la distribución oficial.');settings.asset(args.kind,file);return true;},
  domain:async args=>{validate(object({host:text(253)}),args);const r=await dialog.showMessageBox(win,{message:'¿Permitir abrir HTTPS de '+args.host+'?',buttons:['Cancelar','Autorizar dominio'],defaultId:0,cancelId:0});if(r.response)settings.domain(args.host);return !!r.response;},
  google:async args=>{validate(object({action:enumeration(['configure','connect','disconnect','status'])}),args);return google[args.action]();},
  diagnostics:async()=>{let models=[],ollamaError='',voices=[],ttsError='';try{models=await provider.models();}catch(e){ollamaError=e.message;}try{voices=await voice.voices();}catch(e){ttsError=e.message;}let agenda;try{agenda=await crm('diagnostics');}catch(e){agenda={readable:false,error:e.message};}const s=settings.get();return {platform:process.platform,electron:process.versions.electron,microphonePermission:s.microphoneConsent===true,ollama:{running:!ollamaError,models,error:ollamaError},whisper:{binary:fs.existsSync(s.whisperBinary),model:fs.existsSync(s.whisperModel)},tts:{voices,error:ttsError},bridge:true,agenda,google:google.status(),appearance:process.platform==='win32'?s.appearance:'solid'};}
 };
 const empty=new Set(['settings.get','diagnostics','cancel','voices','models','apps.list','apps.discover']);
 ipcMain.handle('evie:request',async(event,message)=>{try{if(!isTrusted(event))throw Error('Origen IPC no autorizado.');limit();if(!message||Object.keys(message).sort().join(',')!=='args,method'||typeof message.method!=='string'||!Object.hasOwn(requests,message.method)||!message.args||typeof message.args!=='object'||Array.isArray(message.args))throw Error('Contrato IPC inválido.');if(empty.has(message.method))validate(object(),message.args);if(settings.locked()&&!['account','window','cancel'].includes(message.method))throw Error('Inicia sesión antes de usar funciones de escritorio.');const run=()=>requests[message.method](message.args);return {ok:true,data:await (message.method==='account'?run():settings.run(run))};}catch(error){return {ok:false,error:error.message,...(Number.isInteger(error.status)?{status:error.status}:{})};}});
 createWindow();
}
if(require('electron-squirrel-startup'))app.quit();else if(!app.requestSingleInstanceLock())app.quit();else{app.on('second-instance',()=>{if(win){if(win.isMinimized())win.restore();win.show();win.focus();}});app.whenReady().then(install).catch(error=>{console.error('EVIE startup:',error.message);dialog.showErrorBox('EVIE','No se pudo iniciar el host local. Revisa dependencias e instalación.');app.quit();});}
app.on('window-all-closed',()=>app.quit());app.on('before-quit',()=>{globalShortcut.unregisterAll();conversation?.cancel();processes.stop();tray?.destroy();if(!quitting){quitting=true;void voice?.clean();} });
