'use strict';
// Optional installed-app OAuth. Local Agenda remains the authoritative provider.
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),crypto=require('node:crypto');
class GoogleCalendarProvider{
 constructor(accessToken){this.accessToken=accessToken;this.id='google';}
 async listEvents(calendarId='primary'){const r=await fetch('https://www.googleapis.com/calendar/v3/calendars/'+encodeURIComponent(calendarId)+'/events?singleEvents=true&maxResults=100',{headers:{Authorization:'Bearer '+await this.accessToken()},signal:AbortSignal.timeout(15000),redirect:'error'});if(!r.ok)throw Error('Google Calendar no pudo leer el calendario.');return r.json();}
}
module.exports=function({dir,safeStorage,shell,dialog,getWindow}){const configFile=path.join(dir,'google-config.enc'),tokenFile=path.join(dir,'google-token.enc');let connecting=false;
 const available=()=>safeStorage.isEncryptionAvailable();
 function read(file){if(!available()||!fs.existsSync(file))return null;return JSON.parse(safeStorage.decryptString(fs.readFileSync(file)));}
 function save(file,value){if(!available())throw Error('Cifrado del sistema no disponible. Google permanece desconectado.');fs.writeFileSync(file,safeStorage.encryptString(JSON.stringify(value)),{mode:0o600});}
 async function token(body){const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams(body),redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('Google rechazó la autorización. Comprueba el cliente OAuth de escritorio.');return r.json();}
 return {status(){return {provider:'LocalAgendaProvider',googleConfigured:fs.existsSync(configFile),googleConnected:fs.existsSync(tokenFile)&&available(),encryptedStorage:available(),note:'La conexión opcional no sincroniza ni modifica Agenda automáticamente.'};},async configure(){if(!available())throw Error('safeStorage no disponible.');const r=await dialog.showOpenDialog(getWindow(),{title:'Importar OAuth de escritorio descargado de Google (solo almacenamiento cifrado)',properties:['openFile'],filters:[{name:'Desktop OAuth JSON',extensions:['json']}]});if(r.canceled)return {configured:false};if(fs.statSync(r.filePaths[0]).size>20000)throw Error('Archivo OAuth inválido.');const c=JSON.parse(fs.readFileSync(r.filePaths[0],'utf8')).installed;if(!c||typeof c.client_id!=='string'||!c.client_id.endsWith('.apps.googleusercontent.com')||typeof(c.client_secret||'')!=='string')throw Error('Se requiere cliente OAuth de tipo Desktop.');save(configFile,{client_id:c.client_id,client_secret:c.client_secret||''});return {configured:true};},async connect(){if(connecting)throw Error('Hay una conexión en curso.');const c=read(configFile);if(!c)throw Error('Configura primero el cliente OAuth Desktop. Consulta docs/GOOGLE_CALENDAR_SETUP.md.');const r=await dialog.showMessageBox(getWindow(),{message:'Conectar Google Calendar (opcional)',detail:'Permiso calendar.events: leer y editar eventos. Esta fase mantiene Agenda local; no sincroniza ni escribe en Google automáticamente. Tokens cifrados únicamente en este equipo.',buttons:['Cancelar','Continuar con Google'],cancelId:0,defaultId:0});if(!r.response)return {connected:false};connecting=true;
 const state=crypto.randomBytes(32).toString('base64url'),verifier=crypto.randomBytes(48).toString('base64url'),challenge=crypto.createHash('sha256').update(verifier).digest('base64url');let server;
 try{const code=await new Promise((resolve,reject)=>{let timer;server=http.createServer((req,res)=>{const u=new URL(req.url,'http://127.0.0.1');if(req.method!=='GET'||u.pathname!=='/oauth/callback'||u.searchParams.get('state')!==state){res.writeHead(400);res.end('Invalid callback');return;}res.setHeader('Content-Type','text/plain; charset=utf-8');res.end('Puedes volver a EVIE.');clearTimeout(timer);u.searchParams.get('code')?resolve(u.searchParams.get('code')):reject(Error('Consentimiento no concedido.'));});server.on('error',reject);server.listen(0,'127.0.0.1',()=>{const redirect_uri='http://127.0.0.1:'+server.address().port+'/oauth/callback';server.redirectURI=redirect_uri;const u=new URL('https://accounts.google.com/o/oauth2/v2/auth');u.search=new URLSearchParams({client_id:c.client_id,redirect_uri,response_type:'code',scope:'https://www.googleapis.com/auth/calendar.events',access_type:'offline',prompt:'consent',state,code_challenge:challenge,code_challenge_method:'S256'}).toString();shell.openExternal(u.href).catch(reject);});timer=setTimeout(()=>reject(Error('Autorización caducada.')),120000);timer.unref();});const result=await token({...c,code,code_verifier:verifier,redirect_uri:server.redirectURI,grant_type:'authorization_code'});save(tokenFile,{...result,expires_at:Date.now()+result.expires_in*1000});return {connected:true};}finally{server?.close();connecting=false;}},async disconnect(){fs.rmSync(tokenFile,{force:true});return {connected:false,note:'Token eliminado localmente. Puedes revocar el permiso también en tu cuenta Google.'};},provider:new GoogleCalendarProvider(async()=>{let t=read(tokenFile);if(!t)throw Error('Google no conectado.');if(t.expires_at<Date.now()+60000){const c=read(configFile),renewed=await token({...c,grant_type:'refresh_token',refresh_token:t.refresh_token});t={...t,...renewed,expires_at:Date.now()+renewed.expires_in*1000};save(tokenFile,t);}return t.access_token;})};
};
module.exports.GoogleCalendarProvider=GoogleCalendarProvider;
