'use strict';
const fs=require('node:fs'),path=require('node:path'),{createHash}=require('node:crypto');
const {run}=require('../voice/process.cjs');
const protocols=Object.freeze({spotify:'spotify:',roblox:'roblox:',whatsapp:'whatsapp:',discord:'discord:',steam:'steam://open/main','com.epicgames.launcher':'com.epicgames.launcher://'});
const blocked=/(?:^|[\\/\s._-])(cmd|powershell|pwsh|wscript|cscript|mshta|rundll32|regsvr32|regedit|reg|shutdown|schtasks|taskschd|services|sc|mmc|msiexec|installutil|certutil|bitsadmin|bcdedit|netsh|net|rstrui|control|taskmgr|runas|python\d*|node|ruby|perl|bash|wsl|wt|terminal|setup|installer|uninstall\w*|update|updater|winget|choco|scoop|anydesk|teamviewer|mstsc|rustdesk|vnc\w*|keepass\w*|bitwarden|1password|lastpass|dashlane|wallet|ledger|trezor)(?:$|[\\/\s._-])/i;
function executable(file){if(typeof file!=='string'||!path.isAbsolute(file)||file.startsWith('\\\\')||path.extname(file).toLowerCase()!=='.exe'||blocked.test(file)||!fs.statSync(file).isFile())throw Error('Aplicación no permitida: selecciona un .exe local, no herramientas administrativas, intérpretes, instaladores, acceso remoto o credenciales.');const real=fs.realpathSync(file);if(blocked.test(real)||real.startsWith('\\\\'))throw Error('Destino no permitido.');return real;}
function validateApp(app){if(!app||blocked.test(String(app.name||'')))throw Error('Aplicación bloqueada.');const kind=app.kind||'exe';if(kind==='exe'){executable(app.path);}else if(kind==='store'){if(typeof app.aumid!=='string'||!/^[A-Za-z0-9_.-]+![A-Za-z0-9_.-]+$/.test(app.aumid)||blocked.test(app.aumid))throw Error('AppUserModelID inválido.');}else if(kind==='protocol'){if(!Object.hasOwn(protocols,app.protocol))throw Error('Protocolo no permitido.');}else throw Error('Tipo de aplicación no permitido.');return app;}
const target=app=>app.kind==='store'?app.aumid:app.kind==='protocol'?protocols[app.protocol]:app.path;
function capabilities(app){return ['open',...((app.kind||'exe')==='exe'?['focus','minimize','maximize','restore','close-confirmed']:[]),...(app.protocol==='spotify'?['spotify-search']:[]),...(app.protocol==='whatsapp'?['whatsapp-draft-confirmed']:[])];}
function createCatalog({settings,helper,getIcon=async()=>null,platform=process.platform,runner=run}){
 let candidates=new Map();
 async function discover(){if(platform!=='win32')throw Error('Descubrimiento disponible en Windows.');const ps=path.join(process.env.SystemRoot,'System32','WindowsPowerShell','v1.0','powershell.exe');const result=JSON.parse(await runner(ps,['-NoProfile','-NonInteractive','-File',helper],{timeout:30000}));if(!Array.isArray(result)||result.length>2500)throw Error('Catálogo inválido.');const next=new Map();for(const raw of result){try{const item={kind:raw.kind,name:String(raw.name).slice(0,160),publisher:String(raw.publisher||'').slice(0,160),source:String(raw.source||'').slice(0,500),...(raw.kind==='exe'?{path:executable(raw.path)}:raw.kind==='store'?{aumid:raw.aumid}:{protocol:raw.protocol})};validateApp(item);item.id='app-'+createHash('sha256').update(item.kind+':'+target(item)).digest('hex').slice(0,24);item.capabilities=capabilities(item);next.set(item.id,item);}catch{}}
 candidates=next;return list();}
 function list(){const approved=settings().apps||{},all=new Map([...Object.entries(approved).map(([id,item])=>[id,{...item,id,name:item.name||id,capabilities:capabilities(item)}]),...candidates]);return [...all.values()].map(item=>({...item,authorized:Object.hasOwn(approved,item.id)})).sort((a,b)=>a.name.localeCompare(b.name));}
 async function icon(id){const item=candidates.get(id)||settings().apps[id];if(!item||item.kind!=='exe')return null;validateApp(item);return getIcon(item.path);}
 function candidate(id){const item=candidates.get(id);if(!item)throw Error('Vuelve a buscar y selecciona una aplicación del catálogo.');validateApp(item);return structuredClone(item);}
 return {discover,list,icon,candidate};
}
module.exports={createCatalog,validateApp,executable,capabilities,target,protocols,blocked};
